In [1]:
# Cell 1: set local project paths
import json
import os
import random
import sys

import pandas as pd
from IPython.display import display

notebook_dir = os.getcwd()

if os.path.basename(notebook_dir).lower() == "test":
    project_root = os.path.abspath(os.path.join(notebook_dir, ".."))
else:
    project_root = notebook_dir

backend_root = os.path.join(project_root, "backend")
dataset_root = os.path.join(project_root, "dataset")
liar_root = os.path.join(dataset_root, "LIAR")
output_root = os.path.join(project_root, "test", "outputs")

assert os.path.isdir(backend_root), f"Missing backend folder: {backend_root}"
assert os.path.isdir(liar_root), f"Missing LIAR dataset folder: {liar_root}"
os.makedirs(output_root, exist_ok=True)

if backend_root not in sys.path:
    sys.path.insert(0, backend_root)

print("project_root:", project_root)
print("backend_root:", backend_root)
print("liar_root:", liar_root)
print("output_root:", output_root)

project_root: f:\Desktop\UoP\COMP3000\dual_dimension_misinformation_analyzer
backend_root: f:\Desktop\UoP\COMP3000\dual_dimension_misinformation_analyzer\backend
liar_root: f:\Desktop\UoP\COMP3000\dual_dimension_misinformation_analyzer\dataset\LIAR
output_root: f:\Desktop\UoP\COMP3000\dual_dimension_misinformation_analyzer\test\outputs

In [2]:
# Cell 2: set API keys before backend imports
# If your keys are already set in the terminal or notebook kernel, leave these two lines commented.
os.environ["TAVILY_API_KEY"] = "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"
os.environ["GEMINI_API_KEY"] = "AIzaSyC5CfBmlrTDBPMqoDMe4OUaW_ODSduG_Lk"

missing_keys = []
for key_name in ["TAVILY_API_KEY", "GEMINI_API_KEY"]:
    if not os.environ.get(key_name):
        missing_keys.append(key_name)

if missing_keys:
    raise RuntimeError("Missing API key(s): " + ", ".join(missing_keys))

print("TAVILY_API_KEY set:", bool(os.environ.get("TAVILY_API_KEY")))
print("GEMINI_API_KEY set:", bool(os.environ.get("GEMINI_API_KEY")))

TAVILY_API_KEY set: True
GEMINI_API_KEY set: True

In [3]:
# Cell 3: import fact-checking entry point and choose options
from api_contract import AnalysisOptions
from fact_checking.fact_check_service import analyze_fact_check_claims

options = AnalysisOptions(
    use_query_rewrite=True,
    relevance_threshold=0.1,
    use_oversampling_retry=True,
    use_selective_stabilization=True,
    top_k=3,
    use_all_eligible_evidence=False,
    retrieval_results=8,
)

options.model_dump()

s:\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

{'use_query_rewrite': True,
 'relevance_threshold': 0.1,
 'use_oversampling_retry': True,
 'use_selective_stabilization': True,
 'top_k': 3,
 'use_all_eligible_evidence': False,
 'retrieval_results': 8}

In [4]:
# Cell 4: load the local LIAR test dataset
liar_columns = [
    "id",
    "label",
    "statement",
    "subjects",
    "speaker",
    "speaker_job",
    "state",
    "party",
    "barely_true_count",
    "false_count",
    "half_true_count",
    "mostly_true_count",
    "pants_fire_count",
    "context",
]

liar_test_path = os.path.join(liar_root, "test.tsv")
liar_df = pd.read_csv(liar_test_path, sep="\t", header=None, names=liar_columns)
liar_df["row_index"] = liar_df.index

print("LIAR test path:", liar_test_path)
print("Rows:", len(liar_df))
display(liar_df[["row_index", "label", "statement", "speaker", "context"]].head())
display(liar_df["label"].value_counts().rename_axis("label").reset_index(name="count"))

LIAR test path: f:\Desktop\UoP\COMP3000\dual_dimension_misinformation_analyzer\dataset\LIAR\test.tsv
Rows: 1267

,row_index,label,statement,speaker,context
0,0,true,Building a wall on the U.S.-Mexico border will...,rick-perry,Radio interview
1,1,false,Wisconsin is on pace to double the number of l...,katrina-shankland,a news conference
2,2,false,Says John McCain has done nothing to help the ...,donald-trump,comments on ABC's This Week.
3,3,half-true,Suzanne Bonamici supports a plan that will cut...,rob-cornilles,a radio show
4,4,pants-fire,When asked by a reporter whether hes at the ce...,state-democratic-party-wisconsin,a web video

         label  count
0    half-true    265
1        false    249
2  mostly-true    241
3  barely-true    212
4         true    208
5   pants-fire     92

In [5]:
# Cell 5: choose LIAR rows for a small local smoke test
RANDOM_SEED = 7
SAMPLE_SIZE = 5

random.seed(RANDOM_SEED)
sample_indices = random.sample(range(len(liar_df)), SAMPLE_SIZE)
sample_indices.sort()

sample_df = liar_df.loc[sample_indices, ["row_index", "label", "statement", "speaker", "context"]].copy()
sample_df.reset_index(drop=True, inplace=True)

print("sample_indices:", sample_indices)
display(sample_df)

sample_indices: [98, 148, 308, 663, 808]

,row_index,label,statement,speaker,context
0,98,barely-true,Citizens Property Insurance has over $500 bill...,rick-scott,comments to the press
1,148,half-true,When the union says I want to eliminate tenure...,chris-christie,a speech at the Harvard Graduate School of Edu...
2,308,half-true,"More than 250 (voter registration) groups, ran...",lenny-curry,"an ""Orlando Sentinel"" opinion piece"
3,663,mostly-true,"Were spending less money today, in upcoming fi...",chris-christie,"an interview on NJ101.5 FM's ""Ask the Governor..."
4,808,true,Says Charlie Crist implemented Jeb Bushs A+ Plan.,progressive-choice,a campaign mailer

In [6]:
# Cell 6: convert LIAR rows into the backend claim group schema
liar_label_to_verdict = {
    "true": "True",
    "mostly-true": "Mostly True",
    "half-true": "Neutral",
    "barely-true": "Mostly False",
    "false": "False",
    "pants-fire": "False",
}

claim_groups = []
gold_rows = []

for claim_group_id, row in enumerate(sample_df.to_dict(orient="records"), start=1):
    claim_text = str(row["statement"]).strip()
    claim_groups.append({
        "claim_group_id": claim_group_id,
        "original_sentence": claim_text,
        "text_feature_text": claim_text,
        "atomization_applied": False,
        "factual_claims": [
            {
                "fact_claim_id": 1,
                "claim": claim_text,
            }
        ],
    })
    gold_rows.append({
        "claim_group_id": claim_group_id,
        "row_index": row["row_index"],
        "liar_label": row["label"],
        "mapped_expected_verdict": liar_label_to_verdict.get(row["label"], ""),
        "speaker": row["speaker"],
        "context": row["context"],
    })

gold_df = pd.DataFrame(gold_rows)
display(gold_df)
print(json.dumps(claim_groups, indent=2, ensure_ascii=False))

,claim_group_id,row_index,liar_label,mapped_expected_verdict,speaker,context
0,1,98,barely-true,Mostly False,rick-scott,comments to the press
1,2,148,half-true,Neutral,chris-christie,a speech at the Harvard Graduate School of Edu...
2,3,308,half-true,Neutral,lenny-curry,"an ""Orlando Sentinel"" opinion piece"
3,4,663,mostly-true,Mostly True,chris-christie,"an interview on NJ101.5 FM's ""Ask the Governor..."
4,5,808,true,True,progressive-choice,a campaign mailer

[
  {
    "claim_group_id": 1,
    "original_sentence": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
    "text_feature_text": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
    "atomization_applied": false,
    "factual_claims": [
      {
        "fact_claim_id": 1,
        "claim": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus."
      }
    ]
  },
  {
    "claim_group_id": 2,
    "original_sentence": "When the union says I want to eliminate tenure, thats not true.",
    "text_feature_text": "When the union says I want to eliminate tenure, thats not true.",
    "atomization_applied": false,
    "factual_claims": [
      {
        "fact_claim_id": 1,
        "claim": "When the union says I want to eliminate tenure, thats not true."
      }
    ]
  },
  {
    "claim_group_id": 3,
    "original_sentence": "More than 250 (voter registration) groups, ranging across the entire political spectrum, have filed with the state and are registering voters right now.",
    "text_feature_text": "More than 250 (voter registration) groups, ranging across the entire political spectrum, have filed with the state and are registering voters right now.",
    "atomization_applied": false,
    "factual_claims": [
      {
        "fact_claim_id": 1,
        "claim": "More than 250 (voter registration) groups, ranging across the entire political spectrum, have filed with the state and are registering voters right now."
      }
    ]
  },
  {
    "claim_group_id": 4,
    "original_sentence": "Were spending less money today, in upcoming fiscal year 2014 than the Corzine-Buono budget spent in fiscal year 2008.",
    "text_feature_text": "Were spending less money today, in upcoming fiscal year 2014 than the Corzine-Buono budget spent in fiscal year 2008.",
    "atomization_applied": false,
    "factual_claims": [
      {
        "fact_claim_id": 1,
        "claim": "Were spending less money today, in upcoming fiscal year 2014 than the Corzine-Buono budget spent in fiscal year 2008."
      }
    ]
  },
  {
    "claim_group_id": 5,
    "original_sentence": "Says Charlie Crist implemented Jeb Bushs A+ Plan.",
    "text_feature_text": "Says Charlie Crist implemented Jeb Bushs A+ Plan.",
    "atomization_applied": false,
    "factual_claims": [
      {
        "fact_claim_id": 1,
        "claim": "Says Charlie Crist implemented Jeb Bushs A+ Plan."
      }
    ]
  }
]

In [7]:
# Cell 7: run fact-checking and save the raw schema output
fact_checking_result = analyze_fact_check_claims(claim_groups, options)
schema_output = fact_checking_result.model_dump()

output_path = os.path.join(output_root, "liar_fact_checking_schema_output.json")
with open(output_path, "w", encoding="utf-8") as output_file:
    json.dump(schema_output, output_file, indent=2, ensure_ascii=False)

print("Saved schema output:", output_path)
print(json.dumps(schema_output, indent=2, ensure_ascii=False))

[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[NLI Filter] Loading model: cross-encoder/nli-deberta-v3-base

s:\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\YZJ24\.cache\huggingface\hub\models--cross-encoder--nli-deberta-v3-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 202/202 [00:00<00:00, 6840.55it/s]

[NLI Filter] Model loaded.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 2 | Deduplicated: 0
[NLI Filter] Warning: Evidence was somewhat related, but still not close enough to the claim.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
Saved schema output: f:\Desktop\UoP\COMP3000\dual_dimension_misinformation_analyzer\test\outputs\liar_fact_checking_schema_output.json
{
  "status": "partial_success",
  "truth_score": null,
  "verdict": null,
  "explanation": "",
  "factual_claims": [
    {
      "claim_group_id": 1,
      "fact_claim_id": 1,
      "original_sentence": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
      "text_feature_text": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
      "claim": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
      "status": "insufficient_evidence",
      "truth_score": null,
      "verdict": null,
      "explanation": "Selected evidence was mostly background context and did not provide enough direct supporting or contradicting signal for a verdict.",
      "decision_confidence": "low",
      "evidence_sufficiency": "sufficient",
      "evidence": [
        {
          "stance": "background",
          "evidence_quality": "strong",
          "url": "https://www.marketbeat.com/earnings/reports/2026-4-23-the-blackstone-group-inc-stock/",
          "content": "# BX Q1 2026 Earnings Report on 4/23/2026. 10 stocks to dump today (Ad)Image 2: tc pixel. Adobe Leads 3 Big Buyback Programs Worth Up to 25% of Market Cap. Elon Musk’s $1 Quadrillion AI IPO (Ad)Image 3: tc pixel. Follow the Flow: 3 Stocks Absorbing the Market's Biggest Rotation. *   10 Stocks Set to Soar in 2026 New. *   7 AI Stocks to Invest In New. *   7 Magnificent Stocks in 2026. *   10 Best AI Stocks to Own in 2026. *   Image 17: Valmont Industries logo overlaid on a field scene featuring a center-pivot irrigation system and utility infrastructure.1 Stock Is Powering the AI Boom and the Next Farm Supercycle. *   HelpView our library of help videos to learn how to use the tools on the MarketBeat website. *   Positive Sentiment: Fundraising and scale were strong — **$69 billion** of inflows in Q1 and nearly **$250 billion** over the last 12 months, driving AUM to a record >**$1.3 trillion**. Good day, and welcome to the Blackstone First Quarter 2026 Investor Call.",
          "ai_analysis": "This evidence discusses financial news and market performance but does not mention \"Citizens Property Insurance\" or the specific financial details of the claim."
        },
        {
          "stance": "background",
          "evidence_quality": "usable",
          "url": "https://www.granvillecounty.org/m/NewsFlash",
          "content": "Fair housing means all people have equal opportunity to be considered for rental units, purchase of property, housing loans, and property insurance. If you",
          "ai_analysis": "This evidence defines fair housing and its relation to property insurance in general terms, but it does not mention \"Citizens Property Insurance\" or its specific financial situation."
        },
        {
          "stance": "background",
          "evidence_quality": "usable",
          "url": "https://www.abilenecityhall.com/m/newsflash?cat=10",
          "content": "The 811 Dig Safe Conference focuses on safe excavation practices, utility locating, and equipment demonstrations to reduce the risk of damage to underground infrastructure.Ongoing training like this helps staff stay up to date on best practices, maintain compliance, and continue providing safe, reliable utility services to the community.Municipal Court TrainingAbilene Municipal Court Clerk Madison Anguiano attended the 2026 Municipal Court Clerks Conference in Wichita on March 26–27.The conference provides municipal court clerks with updates on court processes and an opportunity to connect with other clerks.↑ Back to topUpcoming Work on K-15 — Detour Details Work is scheduled to address a drainage issue near the Union Pacific Railroad that has caused flooding during heavy rain near Buckeye and NW 2nd Street.Work is expected to begin April 28, weather permitting, and last approximately two days.To complete the work, a detour will be in place on Buckeye/K-15 between NW 14th Street and E 1st Street.TRAFFIC IMPACTS:Truck route detour: Trucks will be routed around the closure using the posted detour.Local traffic: Access will remain open from NW 14th Street and E 1st Street using staggered barricades.Railroad Crossing: The Union Pacific Railroad crossing on Buckeye will be closed to all traffic.",
          "ai_analysis": "This evidence discusses utility work and a conference for municipal court clerks. It does not contain any information about \"Citizens Property Insurance\" or its financial standing."
        }
      ],
      "metadata": {
        "retrieval_query_used": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
        "fallback_used": false,
        "search_raw_evidence_count": 8,
        "selected_evidence_count": 3
      }
    },
    {
      "claim_group_id": 2,
      "fact_claim_id": 1,
      "original_sentence": "When the union says I want to eliminate tenure, thats not true.",
      "text_feature_text": "When the union says I want to eliminate tenure, thats not true.",
      "claim": "When the union says I want to eliminate tenure, thats not true.",
      "status": "success",
      "truth_score": 0.9,
      "verdict": "True",
      "explanation": "The claim states that the union's assertion about the speaker wanting to eliminate tenure is untrue. Evidence 1 directly quotes the speaker making this exact statement, confirming the claim. Evidence 2 and 3 discuss tenure in general or related actions but do not directly address the speaker's denial or the union's specific claim about the speaker's intentions.",
      "decision_confidence": "low",
      "evidence_sufficiency": "sufficient",
      "evidence": [
        {
          "stance": "supports",
          "evidence_quality": "strong",
          "url": "https://www.politifact.com/factchecks/2011/jun/21/chris-christie/gov-chris-christie-says-he-doesnt-want-eliminate-t/",
          "content": "\"So when the union says I want to eliminate tenure that's not true,\" Christie said during a speech to students and professors at the Harvard Graduate School of",
          "ai_analysis": "This evidence directly quotes the speaker denying the union's claim that they want to eliminate tenure, which precisely matches the claim."
        },
        {
          "stance": "background",
          "evidence_quality": "usable",
          "url": "https://murraystatenews.org/205354/news/campus-union-demands-gop-stop-tenure-attacks/",
          "content": "After the state legislature introduced a new bill challenging faculty tenure positions, Murray State professors demand an end to attacks",
          "ai_analysis": "This evidence discusses a bill challenging faculty tenure and professors' reactions, but it does not mention the speaker or their specific claim about the union."
        },
        {
          "stance": "background",
          "evidence_quality": "weak",
          "url": "http://stevendkrause.com/2015/06/12/seven-observations-about-why-tenure-is-not-all-that/",
          "content": "Whenever there are moves to curtail or eliminate tenure, academic-types usually first appeal to how tenure is about protecting academic freedom.",
          "ai_analysis": "This evidence discusses the general argument for tenure protection, particularly in response to curtailment efforts, but it does not directly address the specific claim made in the user's prompt."
        }
      ],
      "metadata": {
        "retrieval_query_used": "When the union says I want to eliminate tenure, thats not true.",
        "fallback_used": true,
        "search_raw_evidence_count": 8,
        "selected_evidence_count": 3
      }
    },
    {
      "claim_group_id": 3,
      "fact_claim_id": 1,
      "original_sentence": "More than 250 (voter registration) groups, ranging across the entire political spectrum, have filed with the state and are registering voters right now.",
      "text_feature_text": "More than 250 (voter registration) groups, ranging across the entire political spectrum, have filed with the state and are registering voters right now.",
      "claim": "More than 250 (voter registration) groups, ranging across the entire political spectrum, have filed with the state and are registering voters right now.",
      "status": "insufficient_evidence",
      "truth_score": null,
      "verdict": null,
      "explanation": "Retrieved evidence was found, but it did not line up closely enough with the specific claim to support a verdict.",
      "decision_confidence": "low",
      "evidence_sufficiency": "insufficient",
      "evidence": [],
      "metadata": {
        "retrieval_query_used": "More than 250 voter registration groups have filed with the state and are registering voters right now.",
        "fallback_used": false,
        "search_raw_evidence_count": 6,
        "selected_evidence_count": 0
      }
    },
    {
      "claim_group_id": 4,
      "fact_claim_id": 1,
      "original_sentence": "Were spending less money today, in upcoming fiscal year 2014 than the Corzine-Buono budget spent in fiscal year 2008.",
      "text_feature_text": "Were spending less money today, in upcoming fiscal year 2014 than the Corzine-Buono budget spent in fiscal year 2008.",
      "claim": "Were spending less money today, in upcoming fiscal year 2014 than the Corzine-Buono budget spent in fiscal year 2008.",
      "status": "insufficient_evidence",
      "truth_score": null,
      "verdict": null,
      "explanation": "No reliable evidence found for this claim.",
      "decision_confidence": "low",
      "evidence_sufficiency": "insufficient",
      "evidence": [],
      "metadata": {
        "retrieval_query_used": "We are spending less money in fiscal year 2014 than the Corzine-Buono budget spent in fiscal year 2008.",
        "fallback_used": false,
        "search_raw_evidence_count": 0,
        "selected_evidence_count": 0
      }
    },
    {
      "claim_group_id": 5,
      "fact_claim_id": 1,
      "original_sentence": "Says Charlie Crist implemented Jeb Bushs A+ Plan.",
      "text_feature_text": "Says Charlie Crist implemented Jeb Bushs A+ Plan.",
      "claim": "Says Charlie Crist implemented Jeb Bushs A+ Plan.",
      "status": "insufficient_evidence",
      "truth_score": null,
      "verdict": null,
      "explanation": "Selected evidence was mostly background context and did not provide enough direct supporting or contradicting signal for a verdict.",
      "decision_confidence": "low",
      "evidence_sufficiency": "insufficient",
      "evidence": [
        {
          "stance": "background",
          "evidence_quality": "weak",
          "url": "https://www.independentwomen.com/2023/02/21/former-florida-governor-jeb-bush-opportunity-scholarship/",
          "content": "... introduced his A+ plan for education in 1999. Tap ... says that ... And other than the last few years of Charlie Crist, one term, he was a Republican.",
          "ai_analysis": "This source mentions Charlie Crist and the A+ plan, but primarily focuses on Crist's political party affiliation changes and his past as a Republican. It does not directly confirm or deny his implementation of Jeb Bush's A+ Plan."
        },
        {
          "stance": "supports",
          "evidence_quality": "weak",
          "url": "https://www.palmbeachpost.com/story/news/2014/08/13/editorial-crist-is-democrats-best/7085338007/",
          "content": "As a Republican education commissioner, he implemented then-Gov. Jeb Bush's A+ Plan, which expanded the use of the much-maligned Florida Comprehensive",
          "ai_analysis": "This source directly supports the claim by stating that Charlie Crist, as a Republican education commissioner, implemented then-Governor Jeb Bush's A+ Plan."
        }
      ],
      "metadata": {
        "retrieval_query_used": "Says Charlie Crist implemented Jeb Bushs A+ Plan.",
        "fallback_used": true,
        "search_raw_evidence_count": 8,
        "selected_evidence_count": 2
      }
    }
  ]
}

In [8]:
# Cell 8: build a compact verdict table from the schema output
summary_rows = []

for factual_claim in fact_checking_result.factual_claims:
    gold = gold_df.loc[gold_df["claim_group_id"] == factual_claim.claim_group_id].iloc[0]
    summary_rows.append({
        "claim_group_id": factual_claim.claim_group_id,
        "row_index": gold["row_index"],
        "claim": factual_claim.claim,
        "liar_label": gold["liar_label"],
        "mapped_expected_verdict": gold["mapped_expected_verdict"],
        "backend_status": factual_claim.status,
        "backend_verdict": factual_claim.verdict,
        "truth_score": factual_claim.truth_score,
        "decision_confidence": factual_claim.decision_confidence,
        "evidence_sufficiency": factual_claim.evidence_sufficiency,
        "raw_evidence_count": factual_claim.metadata.search_raw_evidence_count,
        "selected_evidence_count": factual_claim.metadata.selected_evidence_count,
        "retrieval_query_used": factual_claim.metadata.retrieval_query_used,
        "verdict_matches_label_map": factual_claim.verdict == gold["mapped_expected_verdict"],
    })

summary_df = pd.DataFrame(summary_rows)
display(summary_df)

,claim_group_id,row_index,claim,liar_label,mapped_expected_verdict,backend_status,backend_verdict,truth_score,decision_confidence,evidence_sufficiency,raw_evidence_count,selected_evidence_count,retrieval_query_used,verdict_matches_label_map
0,1,98,Citizens Property Insurance has over $500 bill...,barely-true,Mostly False,insufficient_evidence,NaN,NaN,low,sufficient,8,3,Citizens Property Insurance has over $500 bill...,False
1,2,148,When the union says I want to eliminate tenure...,half-true,Neutral,success,True,0.9,low,sufficient,8,3,When the union says I want to eliminate tenure...,False
2,3,308,"More than 250 (voter registration) groups, ran...",half-true,Neutral,insufficient_evidence,NaN,NaN,low,insufficient,6,0,More than 250 voter registration groups have f...,False
3,4,663,"Were spending less money today, in upcoming fi...",mostly-true,Mostly True,insufficient_evidence,NaN,NaN,low,insufficient,0,0,We are spending less money in fiscal year 2014...,False
4,5,808,Says Charlie Crist implemented Jeb Bushs A+ Plan.,true,True,insufficient_evidence,NaN,NaN,low,insufficient,8,2,Says Charlie Crist implemented Jeb Bushs A+ Plan.,False

In [9]:
# Cell 9: inspect selected evidence behind each verdict
evidence_rows = []

for factual_claim in fact_checking_result.factual_claims:
    for evidence_index, evidence in enumerate(factual_claim.evidence, start=1):
        evidence_rows.append({
            "claim_group_id": factual_claim.claim_group_id,
            "fact_claim_id": factual_claim.fact_claim_id,
            "evidence_index": evidence_index,
            "stance": evidence.stance,
            "evidence_quality": evidence.evidence_quality,
            "url": evidence.url,
            "content_preview": evidence.content[:500],
            "ai_analysis": evidence.ai_analysis,
        })

evidence_df = pd.DataFrame(evidence_rows)
display(evidence_df)

,claim_group_id,fact_claim_id,evidence_index,stance,evidence_quality,url,content_preview,ai_analysis
0,1,1,1,background,strong,https://www.marketbeat.com/earnings/reports/20...,# BX Q1 2026 Earnings Report on 4/23/2026. 10 ...,This evidence discusses financial news and mar...
1,1,1,2,background,usable,https://www.granvillecounty.org/m/NewsFlash,Fair housing means all people have equal oppor...,This evidence defines fair housing and its rel...
2,1,1,3,background,usable,https://www.abilenecityhall.com/m/newsflash?ca...,The 811 Dig Safe Conference focuses on safe ex...,This evidence discusses utility work and a con...
3,2,1,1,supports,strong,https://www.politifact.com/factchecks/2011/jun...,"""So when the union says I want to eliminate te...",This evidence directly quotes the speaker deny...
4,2,1,2,background,usable,https://murraystatenews.org/205354/news/campus...,After the state legislature introduced a new b...,This evidence discusses a bill challenging fac...
5,2,1,3,background,weak,http://stevendkrause.com/2015/06/12/seven-obse...,Whenever there are moves to curtail or elimina...,This evidence discusses the general argument f...
6,5,1,1,background,weak,https://www.independentwomen.com/2023/02/21/fo...,... introduced his A+ plan for education in 19...,This source mentions Charlie Crist and the A+ ...
7,5,1,2,supports,weak,https://www.palmbeachpost.com/story/news/2014/...,"As a Republican education commissioner, he imp...",This source directly supports the claim by sta...

In [10]:
# Cell 10: run one chosen LIAR row as a deep dive
TARGET_ROW_INDEX = int(sample_df.loc[0, "row_index"])

target_row = liar_df.loc[TARGET_ROW_INDEX]
target_claim = str(target_row["statement"]).strip()
target_claim_groups = [
    {
        "claim_group_id": 1,
        "original_sentence": target_claim,
        "text_feature_text": target_claim,
        "atomization_applied": False,
        "factual_claims": [
            {
                "fact_claim_id": 1,
                "claim": target_claim,
            }
        ],
    }
]

target_result = analyze_fact_check_claims(target_claim_groups, options)

print("row_index:", TARGET_ROW_INDEX)
print("liar_label:", target_row["label"])
print("mapped_expected_verdict:", liar_label_to_verdict.get(target_row["label"], ""))
print("claim:", target_claim)
print(json.dumps(target_result.model_dump(), indent=2, ensure_ascii=False))

[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
row_index: 98
liar_label: barely-true
mapped_expected_verdict: Mostly False
claim: Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.
{
  "status": "insufficient_evidence",
  "truth_score": null,
  "verdict": null,
  "explanation": "",
  "factual_claims": [
    {
      "claim_group_id": 1,
      "fact_claim_id": 1,
      "original_sentence": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
      "text_feature_text": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
      "claim": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
      "status": "insufficient_evidence",
      "truth_score": null,
      "verdict": null,
      "explanation": "Selected evidence was mostly background context and did not provide enough direct supporting or contradicting signal for a verdict.",
      "decision_confidence": "low",
      "evidence_sufficiency": "sufficient",
      "evidence": [
        {
          "stance": "background",
          "evidence_quality": "strong",
          "url": "https://www.marketbeat.com/earnings/reports/2026-4-23-the-blackstone-group-inc-stock/",
          "content": "# BX Q1 2026 Earnings Report on 4/23/2026. 10 stocks to dump today (Ad)Image 2: tc pixel. Adobe Leads 3 Big Buyback Programs Worth Up to 25% of Market Cap. Elon Musk’s $1 Quadrillion AI IPO (Ad)Image 3: tc pixel. Follow the Flow: 3 Stocks Absorbing the Market's Biggest Rotation. *   10 Stocks Set to Soar in 2026 New. *   7 AI Stocks to Invest In New. *   7 Magnificent Stocks in 2026. *   10 Best AI Stocks to Own in 2026. *   Image 17: Valmont Industries logo overlaid on a field scene featuring a center-pivot irrigation system and utility infrastructure.1 Stock Is Powering the AI Boom and the Next Farm Supercycle. *   HelpView our library of help videos to learn how to use the tools on the MarketBeat website. *   Positive Sentiment: Fundraising and scale were strong — **$69 billion** of inflows in Q1 and nearly **$250 billion** over the last 12 months, driving AUM to a record >**$1.3 trillion**. Good day, and welcome to the Blackstone First Quarter 2026 Investor Call.",
          "ai_analysis": "This evidence discusses financial news and market trends, but does not mention Citizens Property Insurance or its financial figures, making it irrelevant to the claim."
        },
        {
          "stance": "background",
          "evidence_quality": "usable",
          "url": "https://www.granvillecounty.org/m/NewsFlash",
          "content": "Fair housing means all people have equal opportunity to be considered for rental units, purchase of property, housing loans, and property insurance. If you",
          "ai_analysis": "This evidence defines fair housing and mentions property insurance in a general context, but does not provide specific financial details about Citizens Property Insurance."
        },
        {
          "stance": "background",
          "evidence_quality": "usable",
          "url": "https://www.abilenecityhall.com/m/newsflash?cat=10",
          "content": "The 811 Dig Safe Conference focuses on safe excavation practices, utility locating, and equipment demonstrations to reduce the risk of damage to underground infrastructure.Ongoing training like this helps staff stay up to date on best practices, maintain compliance, and continue providing safe, reliable utility services to the community.Municipal Court TrainingAbilene Municipal Court Clerk Madison Anguiano attended the 2026 Municipal Court Clerks Conference in Wichita on March 26–27.The conference provides municipal court clerks with updates on court processes and an opportunity to connect with other clerks.↑ Back to topUpcoming Work on K-15 — Detour Details Work is scheduled to address a drainage issue near the Union Pacific Railroad that has caused flooding during heavy rain near Buckeye and NW 2nd Street.Work is expected to begin April 28, weather permitting, and last approximately two days.To complete the work, a detour will be in place on Buckeye/K-15 between NW 14th Street and E 1st Street.TRAFFIC IMPACTS:Truck route detour: Trucks will be routed around the closure using the posted detour.Local traffic: Access will remain open from NW 14th Street and E 1st Street using staggered barricades.Railroad Crossing: The Union Pacific Railroad crossing on Buckeye will be closed to all traffic.",
          "ai_analysis": "This evidence focuses on utility infrastructure safety and municipal court training, with no mention of Citizens Property Insurance or its financial risk and surplus."
        }
      ],
      "metadata": {
        "retrieval_query_used": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
        "fallback_used": false,
        "search_raw_evidence_count": 8,
        "selected_evidence_count": 3
      }
    }
  ]
}

In [11]:
# Cell 11: rerun the deep dive with looser evidence selection
looser_options = AnalysisOptions(
    use_query_rewrite=True,
    relevance_threshold=0.05,
    use_oversampling_retry=True,
    use_selective_stabilization=True,
    top_k=5,
    use_all_eligible_evidence=False,
    retrieval_results=12,
)

looser_result = analyze_fact_check_claims(target_claim_groups, looser_options)
print(json.dumps(looser_result.model_dump(), indent=2, ensure_ascii=False))

[Search] Retrieved 12 results | Filtered shell: 0 | Deduplicated: 0
{
  "status": "insufficient_evidence",
  "truth_score": null,
  "verdict": null,
  "explanation": "",
  "factual_claims": [
    {
      "claim_group_id": 1,
      "fact_claim_id": 1,
      "original_sentence": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
      "text_feature_text": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
      "claim": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
      "status": "insufficient_evidence",
      "truth_score": null,
      "verdict": null,
      "explanation": "Selected evidence was mostly background context and did not provide enough direct supporting or contradicting signal for a verdict.",
      "decision_confidence": "low",
      "evidence_sufficiency": "sufficient",
      "evidence": [
        {
          "stance": "background",
          "evidence_quality": "usable",
          "url": "https://www.ishares.com/us/literature/sai/sai-ishares-trust-2-28.pdf",
          "content": "1 Annual Report for each of the below funds, for which JPMorgan or State Street, as applicable, serves as administrator, custodian and transfer agent: iShares 0-3 Month Treasury Bond ETF, iShares 1-3 Year Treasury Bond ETF, iShares 3-7 Year Treasury Bond ETF, iShares 7-10 Year Treasury Bond ETF, iShares 10-20 Year Treasury Bond ETF, iShares 20+ Year Treasury Bond ETF, iShares 25+ Year Treasury STRIPS Bond ETF, iShares Agency Bond ETF, iShares California Muni Bond ETF, iShares Core 5-10 Year USD Bond ETF, iShares Core 10+ Year USD Bond ETF, iShares Government/Credit Bond ETF, iShares iBoxx $ High Yield Corporate Bond ETF, iShares iBoxx $ Investment Grade Corporate Bond ETF, iShares High Yield Systematic Bond ETF, iShares Intermediate Government/Credit Bond ETF, iShares Investment Grade Systematic Bond ETF ,iShares MBS ETF, iShares National Muni Bond ETF, iShares New York Muni Bond ETF, iShares Short-Term National Muni Bond ETF and iShares Short Treasury Bond ETF 2 Annual Report for each of the below funds, for which JPMorgan or State Street, as applicable, serves as administrator, custodian and transfer agent: iShares 1-5 Year Investment Grade Corporate Bond ETF, iShares 5-10 Year Investment Grade Corporate Bond ETF, iShares 10+ Year Investment Grade Corporate Bond ETF, iShares BBB Rated Corporate Bond ETF, iShares Broad USD Investment Grade Corporate Bond ETF, iShares Core U.S. Aggregate Bond ETF, iShares ESG Advanced Investment Grade Corporate Bond ETF, iShares ESG Advanced Total USD Bond Market ETF, iShares ESG Aware 1-5 Year USD Corporate Bond ETF, iShares ESG Aware U.S. Aggregate Bond ETF, and iShares ESG Aware USD Corporate Bond ETF Table of Contents TABLE OF CONTENTS Page General Description of the Trust and its Funds 1 Exchange Listing and Trading 2 Investment Strategies and Risks 2 Asset-Backed Securities Risk 4 Bonds 5 Borrowing 5 Brady Bonds 6 Commercial Mortgage-Backed Securities Risk 6 Corporate Bonds 6 Diversification Status 6 Futures, Options on Futures and Securities Options 8 High Yield Securities",
          "ai_analysis": "This evidence lists various iShares bond ETFs and discusses general investment strategies and risks related to bonds, but it does not mention Citizens Property Insurance or any financial figures related to it."
        },
        {
          "stance": "background",
          "evidence_quality": "usable",
          "url": "https://www.abilenecityhall.com/m/newsflash?cat=10",
          "content": "The 811 Dig Safe Conference focuses on safe excavation practices, utility locating, and equipment demonstrations to reduce the risk of damage to underground infrastructure.Ongoing training like this helps staff stay up to date on best practices, maintain compliance, and continue providing safe, reliable utility services to the community.Municipal Court TrainingAbilene Municipal Court Clerk Madison Anguiano attended the 2026 Municipal Court Clerks Conference in Wichita on March 26–27.The conference provides municipal court clerks with updates on court processes and an opportunity to connect with other clerks.↑ Back to topUpcoming Work on K-15 — Detour Details Work is scheduled to address a drainage issue near the Union Pacific Railroad that has caused flooding during heavy rain near Buckeye and NW 2nd Street.Work is expected to begin April 28, weather permitting, and last approximately two days.To complete the work, a detour will be in place on Buckeye/K-15 between NW 14th Street and E 1st Street.TRAFFIC IMPACTS:Truck route detour: Trucks will be routed around the closure using the posted detour.Local traffic: Access will remain open from NW 14th Street and E 1st Street using staggered barricades.Railroad Crossing: The Union Pacific Railroad crossing on Buckeye will be closed to all traffic.",
          "ai_analysis": "This evidence discusses a Dig Safe Conference, municipal court training, and upcoming road work. It does not contain any information about Citizens Property Insurance or its financial status."
        },
        {
          "stance": "background",
          "evidence_quality": "usable",
          "url": "https://www.carltoncountymn.gov/DocumentCenter/View/5683",
          "content": "Included in this year's total fund balance is a surplus of. $37,185,262 in the County's General Fund. The overall decrease in the governmental",
          "ai_analysis": "This evidence mentions a surplus in a County's General Fund but does not refer to Citizens Property Insurance or the specific financial figures claimed."
        },
        {
          "stance": "background",
          "evidence_quality": "weak",
          "url": "https://www.snoqualmiewa.gov/CivicAlerts.asp?CID=6",
          "content": "Over the course of two City Council meetings in March 2026, more than 150 community members participated in public comment on the proposed battery energy storage project in unincorporated King County near Snoqualmie. Over the course of two City Council meetings in March 2026, more than 150 community members participated in public comment on the proposed battery energy storage project in unincorporated King County near Snoqualmie. Over the course of two City Council meetings in March 2026, more than 150 community members participated in public comment on the proposed battery energy storage project in unincorporated King County near Snoqualmie. On May 22, 2025, the Snoqualmie City Council directed staff to use steps necessary, from negotiation through litigation, to have the City of North Bend confer law enforcement authority to the Snoqualmie Police Department to ensure public safety is maintained while the two cities work on a contractual dispute regarding the 2025 Police Services Interlocal Agreement (ILA).",
          "ai_analysis": "This evidence details public comments on a battery energy storage project and a dispute between two cities regarding law enforcement services. It does not contain any information relevant to Citizens Property Insurance's financial risk or surplus."
        },
        {
          "stance": "background",
          "evidence_quality": "weak",
          "url": "https://www.granvillecounty.org/m/NewsFlash",
          "content": "NOTICE IS HEREBY GIVEN that on April 20, 2026, at 7:00 p.m., or as soon thereafter as the matter can be heard, the Board of Commissioners (the “Board”) of the County of Granville, North Carolina (the “County”) will hold a public hearing as required by and in compliance with the provisions of Section 147(f) of the Internal Revenue Code of 1986, as amended (the “Code”), and Section 66.0304(11)(a) of the Wisconsin Statutes, as amended, on the proposed issuance of Project Revenue Bonds (eNCore Connects), Series 2026 (the “Bonds”), issued in one or more series, issuances and/or advances, on a tax-exempt or taxable basis, in an aggregate maximum stated principal amount not to exceed $25,000,000 by the Public Finance Authority (the “Authority”), a commission organized under and pursuant to the provisions of Sections 66.0301, 66.0303 and 66.0304 of the Wisconsin Statutes, as amended (the “Act”).",
          "ai_analysis": "This evidence is a notice about a public hearing for the proposed issuance of Project Revenue Bonds and mentions a maximum principal amount. It does not relate to Citizens Property Insurance or the specific financial figures in the claim."
        }
      ],
      "metadata": {
        "retrieval_query_used": "Citizens Property Insurance has over $500 billion worth of risk, with less than $10 billion worth of surplus.",
        "fallback_used": false,
        "search_raw_evidence_count": 12,
        "selected_evidence_count": 5
      }
    }
  ]
}

In [ ]:
# Cell 12: audit raw retrieval and evidence filtering for one claim
from fact_checking.gemini_agent import prepare_claim_for_fact_checking
from fact_checking.retrieval_service import choose_evidence, retrieve_evidence

AUDIT_ROW_INDEX = TARGET_ROW_INDEX

audit_row = liar_df.loc[AUDIT_ROW_INDEX]
audit_claim = str(audit_row["statement"]).strip()
claim_check = prepare_claim_for_fact_checking(
    audit_claim,
    use_query_rewrite=options.use_query_rewrite,
)

print("row_index:", AUDIT_ROW_INDEX)
print("liar_label:", audit_row["label"])
print("claim:", audit_claim)
print("claim_valid:", claim_check.is_valid_claim)
print("final_claim_for_search:", claim_check.final_claim)

retrieval = retrieve_evidence(
    original_claim=audit_claim,
    final_claim=claim_check.final_claim,
    retrieval_results=options.retrieval_results,
    use_oversampling_retry=options.use_oversampling_retry,
)

raw_rows = []
for index, evidence_item in enumerate(retrieval.raw_evidence, start=1):
    raw_rows.append({
        "raw_index": index,
        "url": evidence_item.get("url", ""),
        "source_quality": evidence_item.get("source_quality", ""),
        "source_quality_score": evidence_item.get("source_quality_score", ""),
        "content_preview": evidence_item.get("content", "")[:500],
    })

print("retrieval_query_used:", retrieval.final_claim)
print("retrieval_error_type:", retrieval.error_type)
print("retrieval_error_message:", retrieval.error_message)
print("raw_evidence_count:", retrieval.search_raw_count)
display(pd.DataFrame(raw_rows))

if retrieval.raw_evidence:
    selection = choose_evidence(
        original_claim=audit_claim,
        final_claim=retrieval.final_claim,
        raw_evidence=retrieval.raw_evidence,
        relevance_threshold=options.relevance_threshold,
        top_k=options.top_k,
        use_all_eligible_evidence=options.use_all_eligible_evidence,
        retrieval_results=options.retrieval_results,
        use_oversampling_retry=options.use_oversampling_retry,
    )

    selected_urls = {evidence.url for evidence in selection.selected_evidence}
    scored_rows = []
    for item in selection.filter_debug.get("scored_evidence", []):
        scored_rows.append({
            "selected_for_verdict": item.get("url", "") in selected_urls,
            "filter_reason": item.get("filter_reason", ""),
            "passed_threshold": item.get("passed_threshold", ""),
            "evidence_quality": item.get("evidence_quality", ""),
            "source_quality": item.get("source_quality", ""),
            "relevance_score": item.get("relevance_score", ""),
            "claim_match_score": item.get("claim_match_score", ""),
            "number_score": item.get("number_score", ""),
            "number_status": item.get("number_status", ""),
            "final_match_score": item.get("final_match_score", ""),
            "selection_priority": item.get("selection_priority", ""),
            "url": item.get("url", ""),
            "content_preview": item.get("content_preview", ""),
        })

    selected_rows = []
    for index, evidence in enumerate(selection.selected_evidence, start=1):
        selected_rows.append({
            "selected_index": index,
            "evidence_quality": evidence.evidence_quality,
            "url": evidence.url,
            "content_preview": evidence.content[:500],
        })

    print("selection_final_claim:", selection.final_claim)
    print("selection_fallback_used:", selection.fallback_used)
    print("selected_evidence_count:", len(selection.selected_evidence))
    display(pd.DataFrame(scored_rows))
    display(pd.DataFrame(selected_rows))