In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
# Cell 1: install Colab dependencies
!pip install -q pydantic transformers sentencepiece google-genai pandas requests

In [23]:
# Cell 2: mount Drive and set project paths
import json
import os
import random
import sys

import pandas as pd
from IPython.display import display
from google.colab import drive
import os
import sys
import json
import random
import pandas as pd
from IPython.display import display

project_root = '/content/drive/MyDrive/UoP/COMP3000/dual_dimension_misinformation_analyzer'
frontend_root = os.path.join(project_root, 'frontend')
backend_root = os.path.join(project_root, 'backend')
atomizer_root = os.path.join(backend_root, 'atomizer')
dataset_root = os.path.join(project_root, 'dataset')
fever_dataset_root = os.path.join(dataset_root, 'FEVER')
liar_root = os.path.join(dataset_root, "LIAR")


assert os.path.exists(project_root), f'Missing project_root: {project_root}'
assert os.path.exists(backend_root), f'Missing backend_root: {backend_root}'
assert os.path.exists(dataset_root), f'Missing dataset_root: {dataset_root}'

if backend_root not in sys.path:
    sys.path.append(backend_root)

print('project_root:', project_root)
print('backend_root:', backend_root)
print('dataset_root:', dataset_root)

project_root: /content/drive/MyDrive/UoP/COMP3000/dual_dimension_misinformation_analyzer
backend_root: /content/drive/MyDrive/UoP/COMP3000/dual_dimension_misinformation_analyzer/backend
dataset_root: /content/drive/MyDrive/UoP/COMP3000/dual_dimension_misinformation_analyzer/dataset

In [24]:
# Cell 3: set API keys before backend imports
import os

# Option 1: set them manually here
os.environ["TAVILY_API_KEY"] = "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"
os.environ["GEMINI_API_KEY"] = "AIzaSyC5CfBmlrTDBPMqoDMe4OUaW_ODSduG_Lk"


print('TAVILY_API_KEY set:', 'TAVILY_API_KEY' in os.environ)
print('GEMINI_API_KEY set:', 'GEMINI_API_KEY' in os.environ)

TAVILY_API_KEY set: True
GEMINI_API_KEY set: True

In [25]:
# Cell 4: import fact-checking services and choose options
from api_contract import AnalysisOptions
from fact_checking.fact_check_service import analyze_fact_check_claims

options = AnalysisOptions(
    use_query_rewrite=True,
    relevance_threshold=0.1,
    use_oversampling_retry=True,
    use_selective_stabilization=True,
    top_k=3,
    use_all_eligible_evidence=False,
    retrieval_results=8,
)

options.model_dump()

{'use_query_rewrite': True,
 'relevance_threshold': 0.1,
 'use_oversampling_retry': True,
 'use_selective_stabilization': True,
 'top_k': 3,
 'use_all_eligible_evidence': False,
 'retrieval_results': 8}

In [26]:
# Cell 5: load the LIAR test dataset from Drive
liar_columns = [
    "id",
    "label",
    "statement",
    "subjects",
    "speaker",
    "speaker_job",
    "state",
    "party",
    "barely_true_count",
    "false_count",
    "half_true_count",
    "mostly_true_count",
    "pants_fire_count",
    "context",
]

liar_test_path = os.path.join(liar_root, "test.tsv")
liar_df = pd.read_csv(liar_test_path, sep="\t", header=None, names=liar_columns)
liar_df["row_index"] = liar_df.index

print("LIAR test path:", liar_test_path)
print("Rows:", len(liar_df))
display(liar_df[["row_index", "label", "statement", "speaker", "context"]].head())
display(liar_df["label"].value_counts().rename_axis("label").reset_index(name="count"))

LIAR test path: /content/drive/MyDrive/UoP/COMP3000/dual_dimension_misinformation_analyzer/dataset/LIAR/test.tsv
Rows: 1267

,row_index,label,statement,speaker,context
0,0,true,Building a wall on the U.S.-Mexico border will...,rick-perry,Radio interview
1,1,false,Wisconsin is on pace to double the number of l...,katrina-shankland,a news conference
2,2,false,Says John McCain has done nothing to help the ...,donald-trump,comments on ABC's This Week.
3,3,half-true,Suzanne Bonamici supports a plan that will cut...,rob-cornilles,a radio show
4,4,pants-fire,When asked by a reporter whether hes at the ce...,state-democratic-party-wisconsin,a web video

         label  count
0    half-true    265
1        false    249
2  mostly-true    241
3  barely-true    212
4         true    208
5   pants-fire     92

In [27]:
# Cell 6: choose a balanced LIAR smoke sample
RANDOM_SEED = 7
LABELS_TO_SAMPLE = ["true", "mostly-true", "half-true", "barely-true", "false"]

sample_rows = []
for label in LABELS_TO_SAMPLE:
    label_rows = liar_df[liar_df["label"] == label]
    if not label_rows.empty:
        sample_rows.append(label_rows.sample(n=1, random_state=RANDOM_SEED).iloc[0])

sample_df = pd.DataFrame(sample_rows).reset_index(drop=True)
display(sample_df[["row_index", "label", "statement", "speaker", "context"]])

,row_index,label,statement,speaker,context
0,62,true,Says Bill and Hillary Clinton attended Donald ...,carlos-curbelo,a radio interview
1,432,mostly-true,"We have an Army that just cut 40,000 spots.",marco-rubio,a speech at the Iowa State Fair
2,763,half-true,"When you read the Koran, it talks about dont t...",sean-hannity,"a segment on ""Hannity"""
3,466,barely-true,Were taxing our small businesses now at rates ...,paul-ryan,an interview
4,745,false,The minimum wage has risen $2.35 in the last t...,leonidas-raptakis,testimony before the House Committee on Labor

In [28]:
# Cell 7: convert LIAR rows into backend claim groups
liar_label_to_verdict = {
    "true": "True",
    "mostly-true": "Mostly True",
    "half-true": "Neutral",
    "barely-true": "Mostly False",
    "false": "False",
    "pants-fire": "False",
}

claim_groups = []
gold_rows = []

for claim_group_id, row in enumerate(sample_df.to_dict(orient="records"), start=1):
    claim_text = str(row["statement"]).strip()
    claim_groups.append({
        "claim_group_id": claim_group_id,
        "original_sentence": claim_text,
        "text_feature_text": claim_text,
        "atomization_applied": False,
        "factual_claims": [
            {
                "fact_claim_id": 1,
                "claim": claim_text,
            }
        ],
    })
    gold_rows.append({
        "claim_group_id": claim_group_id,
        "row_index": row["row_index"],
        "liar_label": row["label"],
        "mapped_expected_verdict": liar_label_to_verdict.get(row["label"], ""),
        "speaker": row["speaker"],
        "context": row["context"],
    })

gold_df = pd.DataFrame(gold_rows)
display(gold_df)
print(json.dumps(claim_groups, indent=2, ensure_ascii=False))

,claim_group_id,row_index,liar_label,mapped_expected_verdict,speaker,context
0,1,62,true,True,carlos-curbelo,a radio interview
1,2,432,mostly-true,Mostly True,marco-rubio,a speech at the Iowa State Fair
2,3,763,half-true,Neutral,sean-hannity,"a segment on ""Hannity"""
3,4,466,barely-true,Mostly False,paul-ryan,an interview
4,5,745,false,False,leonidas-raptakis,testimony before the House Committee on Labor

[
  {
    "claim_group_id": 1,
    "original_sentence": "Says Bill and Hillary Clinton attended Donald Trumps last wedding.",
    "text_feature_text": "Says Bill and Hillary Clinton attended Donald Trumps last wedding.",
    "atomization_applied": false,
    "factual_claims": [
      {
        "fact_claim_id": 1,
        "claim": "Says Bill and Hillary Clinton attended Donald Trumps last wedding."
      }
    ]
  },
  {
    "claim_group_id": 2,
    "original_sentence": "We have an Army that just cut 40,000 spots.",
    "text_feature_text": "We have an Army that just cut 40,000 spots.",
    "atomization_applied": false,
    "factual_claims": [
      {
        "fact_claim_id": 1,
        "claim": "We have an Army that just cut 40,000 spots."
      }
    ]
  },
  {
    "claim_group_id": 3,
    "original_sentence": "When you read the Koran, it talks about dont take Christians and Jews as your friends.",
    "text_feature_text": "When you read the Koran, it talks about dont take Christians and Jews as your friends.",
    "atomization_applied": false,
    "factual_claims": [
      {
        "fact_claim_id": 1,
        "claim": "When you read the Koran, it talks about dont take Christians and Jews as your friends."
      }
    ]
  },
  {
    "claim_group_id": 4,
    "original_sentence": "Were taxing our small businesses now at rates higher than corporations.",
    "text_feature_text": "Were taxing our small businesses now at rates higher than corporations.",
    "atomization_applied": false,
    "factual_claims": [
      {
        "fact_claim_id": 1,
        "claim": "Were taxing our small businesses now at rates higher than corporations."
      }
    ]
  },
  {
    "claim_group_id": 5,
    "original_sentence": "The minimum wage has risen $2.35 in the last two years. Thats 31 percent.",
    "text_feature_text": "The minimum wage has risen $2.35 in the last two years. Thats 31 percent.",
    "atomization_applied": false,
    "factual_claims": [
      {
        "fact_claim_id": 1,
        "claim": "The minimum wage has risen $2.35 in the last two years. Thats 31 percent."
      }
    ]
  }
]

In [29]:
# Cell 8: run fact-checking and save schema output
fact_checking_result = analyze_fact_check_claims(claim_groups, options)
schema_output = fact_checking_result.model_dump()


print(json.dumps(schema_output, indent=2, ensure_ascii=False))

[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
{
  "status": "success",
  "truth_score": 0.47333333333333333,
  "verdict": "Neutral",
  "explanation": "Aggregated mean truth score over 5 successful factual claim(s).",
  "factual_claims": [
    {
      "claim_group_id": 1,
      "fact_claim_id": 1,
      "original_sentence": "Says Bill and Hillary Clinton attended Donald Trumps last wedding.",
      "text_feature_text": "Says Bill and Hillary Clinton attended Donald Trumps last wedding.",
      "claim": "Says Bill and Hillary Clinton attended Donald Trumps last wedding.",
      "status": "success",
      "truth_score": 0.9,
      "verdict": "True",
      "explanation": "Evidence 1 directly states that Bill and Hillary Clinton attended Donald Trump's last wedding, providing the date and location, and mentioning they chatted with him during the reception. Evidence 2 corroborates this by stating they were VIP guests at Trump's wedding to Melania. Evidence 3, however, discusses Donald Trump wanting to attend Chelsea Clinton's wedding and mentions Trump had invited Bill and Hillary to his own wedding years earlier, which is background context and does not directly confirm or deny their attendance at his *last* wedding.",
      "decision_confidence": "medium",
      "evidence_sufficiency": "sufficient",
      "evidence": [
        {
          "stance": "supports",
          "evidence_quality": "strong",
          "url": "https://www.politifact.com/factchecks/2015/jul/21/carlos-curbelo/clintons-really-did-attend-donald-trumps-2005-wedd/",
          "content": "Says Bill and Hillary Clinton attended Donald Trump's last wedding. Bill and Hillary Clinton chat with Donald Trump during the reception for his wedding to Melania Knauss in Palm Beach, Fla., on Jan. 22, 2005. Bill and Hillary Clinton chat with Donald Trump during the reception for his wedding to Melania Knauss in Palm Beach, Fla., on Jan. 22, 2005. (Getty Images)    Bill and Hillary Clinton chat with Donald Trump during the reception for his wedding to Melania Knauss in Palm Beach, Fla., on Jan. 22, 2005. Republican presidential candidate Donald Trump’s controversial campaign could just be a ruse to sabotage the GOP, said U.S. Rep. Carlos Curbelo, R-Fla. After all, the billionaire is so friendly with Hillary Clinton, Trump invited her to his nuptials. Curbelo said Bill and Hillary Clinton were at Donald Trump's last wedding. Bloomberg, \"FYI: Hillary Clinton Had a Front-Pew Seat at Donald Trump's Wedding,\" June 16, 2015. MSNBC, \"Donald Trump’s change of heart on Hillary Clinton,\" July 8, 2015.",
          "ai_analysis": "This evidence explicitly states that Bill and Hillary Clinton were at Donald Trump's last wedding and provides details about the event, directly supporting the claim."
        },
        {
          "stance": "supports",
          "evidence_quality": "strong",
          "url": "https://people.com/celebrity/hillary-clinton-and-bill-clinton-at-donald-trumps-wedding-photo/",
          "content": "Back in 2005, Bill and Hillary Clinton were VIP guests at Donald Trump's wedding to his wife Melania – and it sure looks like all four had a pretty good time.",
          "ai_analysis": "This source confirms that Bill and Hillary Clinton were guests at Donald Trump's wedding to Melania, which is presented as his last wedding in the claim, thus supporting it."
        },
        {
          "stance": "background",
          "evidence_quality": "weak",
          "url": "https://www.vanityfair.com/news/2016/08/donald-trump-chelsea-clinton-wedding?srsltid=AfmBOoobZyWX8exleLm87N2vQWj-IVQx3q2_0XaHJ78YOTg419slN69_",
          "content": "# Donald Trump Was Reportedly Desperate to Attend Chelsea Clinton’s Wedding. Image may contain Chelsea Clinton Marc Mezvinsky Clothing Apparel Human Person Fashion Robe Gown and Wedding. But there was perhaps no hotter ticket in 2010 than **Chelsea Clinton’s** 500-person, several million-dollar wedding in upstate New York. This was *the* wedding, so of course **Donald Trump** wanted to be there. Trump, now somewhat infamously, had invited Bill and **Hillary** to his own third wedding years earlier. “The real estate mogul was the sort of person who, though not an actual friend, still aspired to attend Chelsea’s wedding, which he clearly considered a prestigious event,” Conason writes. “I’m supposed to be at the wedding, Doug,” Trump said, according to Conason. But it is good to know that Trump, transgressor of societal norms, politeness, and often, general decency, draws the line somewhere, and apparently it stops at wedding crashing. This image may contain Human Person Clothing Apparel and Ivana Trump.",
          "ai_analysis": "This evidence mentions Donald Trump inviting Bill and Hillary Clinton to his own wedding years earlier, but it focuses on Trump's desire to attend Chelsea Clinton's wedding. It does not directly confirm or deny their attendance at his last wedding."
        }
      ],
      "metadata": {
        "retrieval_query_used": "Bill and Hillary Clinton attended Donald Trump's last wedding.",
        "fallback_used": false,
        "search_raw_evidence_count": 8,
        "selected_evidence_count": 3
      }
    },
    {
      "claim_group_id": 2,
      "fact_claim_id": 1,
      "original_sentence": "We have an Army that just cut 40,000 spots.",
      "text_feature_text": "We have an Army that just cut 40,000 spots.",
      "claim": "We have an Army that just cut 40,000 spots.",
      "status": "success",
      "truth_score": 0.9,
      "verdict": "True",
      "explanation": "The evidence collectively supports the claim that the Army is undergoing significant troop reductions. Multiple sources confirm plans for substantial cuts, with one specifically mentioning 40,000 spots being eliminated. The context provided explains the reasons for these cuts, such as budget constraints and sequestration.",
      "decision_confidence": "medium",
      "evidence_sufficiency": "sufficient",
      "evidence": [
        {
          "stance": "supports",
          "evidence_quality": "strong",
          "url": "https://www.defensenews.com/breaking-news/2015/07/09/us-army-cuts-would-hit-nearly-every-base/",
          "content": "WASHINGTON — The US Army announced a plan to cut 40,000 troops that would impact nearly every Army installation, warning that the reductions could grow if Congress cannot reach a deal to avert sequestration budget cuts. \"With global instability only increasing, and with just 33 percent of the Army's brigade combat teams ready for deployment and decisive operations, there is simply no strategic basis to cut Army force structure below the pre-9/11 level of 490,000,\" McCain, R-Ariz., said. Senior Army officials have said, and George repeated, that Army end-strength would fall to 420,000 under sequestration budget cuts; it would then risk being incapable of meeting the nation's national security guidance. \"Unless provisions of the Budget Control Act are changed or reversed, the Army will have to cut an additional 30,000 by 2019,\" George said, adding later: \"Cuts below this would put us at significant risk.\".",
          "ai_analysis": "This source directly states that the US Army announced a plan to cut 40,000 troops, which fully supports the claim."
        },
        {
          "stance": "supports",
          "evidence_quality": "usable",
          "url": "https://www.news-leader.com/story/news/local/ozarks/2015/07/09/us-army-cut-positions-fort-leonard-wood/29912805/",
          "content": "# U.S. Army to cut 774 positions at Fort Leonard Wood. The U.S. Army will cut 774 of 5,168 active uniformed positions at Missouri's Fort Leonard Wood over the next two years, as part of 40,000 cuts across the force. In a joint statement, U.S. Senators Roy Blunt (R) and Claire McCaskill (D) and U.S. Representative Vicky Hartzler (R-Harrisonville) said: \"The announced reductions to active duty personnel, while significant, are lower than the cuts at many other Army posts across the nation and lower than the level of cuts Fort Leonard Wood experienced in 2013. Fort Leonard Wood's core mission has always been training, Driskill said, and the 774 positions to be cut appeared to be primarily deployable forces, leaving that mission largely unscathed. The cuts are Fort Leonard Wood amount to about 15 percent of its permanent uniformed members, which doesn't include the thousands that come through the base for training each year.",
          "ai_analysis": "This source confirms the 40,000 cuts across the force and provides a specific example of these cuts at Fort Leonard Wood, thereby supporting the claim."
        },
        {
          "stance": "supports",
          "evidence_quality": "weak",
          "url": "https://www.thetowntalk.com/story/news/2015/08/10/army-dangerously-close-being-cut-too-deep/31407771/",
          "content": "that increases the threats and danger to the United States,” Odierno said in an exclusive sit-down with Army Times. This is why the Army must make sure the force it has is the “best Army possible,” Odierno said. “We’ve been able to meet our current commitments, we’ve done it under budget constraints and with an Army that has downsized 80,000 soldiers and getting ready to [lose] 40,000 more, and we’ve been able to look to the future and really establish a way ahead that’s really solid,” Odierno said. As threats grow and resources diminish, “very difficult decisions have to be made,” Odierno said, adding that he had hoped to be able to resolve the Army’s drawdown before he retired. “The Army is about soldiers, it’s about people, and those interactions and the sacrifice they make, those are things we’ll never forget,” Odierno said.",
          "ai_analysis": "This source mentions that the Army is 'getting ready to [lose] 40,000 more,' which directly supports the claim about Army troop cuts."
        }
      ],
      "metadata": {
        "retrieval_query_used": "We have an Army that just cut 40,000 spots.",
        "fallback_used": false,
        "search_raw_evidence_count": 8,
        "selected_evidence_count": 3
      }
    },
    {
      "claim_group_id": 3,
      "fact_claim_id": 1,
      "original_sentence": "When you read the Koran, it talks about dont take Christians and Jews as your friends.",
      "text_feature_text": "When you read the Koran, it talks about dont take Christians and Jews as your friends.",
      "claim": "When you read the Koran, it talks about dont take Christians and Jews as your friends.",
      "status": "success",
      "truth_score": 0.3666666666666667,
      "verdict": "Mostly False",
      "explanation": "Evidence 1 directly quotes the Quran and provides an interpretation that Muslims should not take Christians and Jews as friends, aligning with the claim. Evidence 2 and 3, however, offer a nuanced view, suggesting that the Quranic verses cited in the claim are specific to a historical context and not applicable to contemporary Christians and Jews.",
      "decision_confidence": "medium",
      "evidence_sufficiency": "sufficient",
      "evidence": [
        {
          "stance": "supports",
          "evidence_quality": "strong",
          "url": "https://myislam.org/surah-maidah/ayat-51/",
          "content": "The My Islam App is the ultimate ad-free companion app to help you explore the Qur'an, learn new du'as, and update you on the latest prayer times. O you who have believed, do not take the Jews and the Christians as allies. Do not take the Jews and the Christians for your allies. Take not the Jews and the Christians for friends. You who believe, do not take the Jews and Christians as allies:they are allies only to each other. Do not take the Jews and the Christians for your allies. Allah forbids His believing servants from having Jews and Christians as friends, because they are the enemies of Islam and its people, may Allah curse them. Take not the Jews and the Christians as friends, )” Allah said,. (saying: “We fear lest some misfortune of a disaster may befall us.”) They thus offer this excuse for their friendship and allegiances to the disbelievers, saying that they fear that the disbelievers might defeat the Muslims, so they want to be in favor with the Jews and Christians, to use this favor for their benefit in that eventuality!",
          "ai_analysis": "This evidence directly quotes the Qur'an multiple times with phrasing such as 'do not take the Jews and the Christians as friends' and 'Take not the Jews and the Christians for friends', which strongly supports the claim."
        },
        {
          "stance": "contradicts",
          "evidence_quality": "strong",
          "url": "https://www.alislam.org/articles/is-it-true-that-quran-says-to-not-take-jews-christians-for-friends/",
          "content": "# Is it true that the Quran says to not take the Jews and Christians for friends? I think the biggest misconception among people is that this verse refers to Christians and Jews of all times. There is a fallacy that the Quran commands Muslims to not befriend Jews and Christians based on Chapter 5 verse 52. If we look at the context of the verse, we see that it refers to the lifetime of the Prophet Muhammad(sa) when Jews and Christians were at war with Muslims. Even so, the subsequent verses 58 and 59 clarify the reasons for discouraging friendships with Jews and Christians of that time, who used to make fun of Muslims for adhering to their faith. In any case, remember that rather than creating differences, Islam teaches respect and acceptance of all prophets including Jesus and Moses, thus uniting us under one God. I hope it is clear now that the verse in question does not apply to the Jews and Christians of today.",
          "ai_analysis": "This evidence claims that the verse often cited for the original statement is a 'misconception' and that it refers to a specific historical context during the Prophet Muhammad's time, not to contemporary Christians and Jews, thereby contradicting the claim."
        },
        {
          "stance": "contradicts",
          "evidence_quality": "strong",
          "url": "https://ask.ghamidi.org/forums/discussion/11242/",
          "content": "Allah forbids His believing servants from having Jews and Christians as friends, because they are the enemies of Islam and its people, may Allah curse them. The verse 5:51 refers only to those Christians and Jews who showed clearly enmity towards the Prophet saw and tried to harm him. This hadith does NOT mention expel only specific Jews/Christians who harmed the Prophet.. The verse and hadith are quite clear (even if applicable to only at the time of Prophet) to not have friendship with ANY Jew/Christians. So, what is the point of throwing Jews/Christians from Arabia even at the time of Prophet ? “Sameer the Prophet saw did not say to throw out all the Christians and Jews. This applies only to those Christians and Jews who were Mushrik and opposed the Prophet saw even when the message of the Qur’an was clearly conveyed to them and they still would not accept him”.",
          "ai_analysis": "This evidence argues that the verse refers only to specific Christians and Jews who showed enmity towards the Prophet, and that the verse and hadith are not applicable to all Jews and Christians today, which contradicts the general nature of the claim."
        }
      ],
      "metadata": {
        "retrieval_query_used": "When you read the Koran, it talks about don't take Christians and Jews as your friends.",
        "fallback_used": false,
        "search_raw_evidence_count": 8,
        "selected_evidence_count": 3
      }
    },
    {
      "claim_group_id": 4,
      "fact_claim_id": 1,
      "original_sentence": "Were taxing our small businesses now at rates higher than corporations.",
      "text_feature_text": "Were taxing our small businesses now at rates higher than corporations.",
      "claim": "Were taxing our small businesses now at rates higher than corporations.",
      "status": "success",
      "truth_score": 0.09999999999999998,
      "verdict": "False",
      "explanation": "Evidence 1 states that small businesses are given preferential tax rates compared to corporations. This directly contradicts the claim that small businesses are taxed at higher rates than corporations. Evidence 2 mentions a specific small business tax rate but does not provide a comparative rate for corporations, making its stance on the claim unclear.",
      "decision_confidence": "low",
      "evidence_sufficiency": "sufficient",
      "evidence": [
        {
          "stance": "contradicts",
          "evidence_quality": "strong",
          "url": "https://cdhowe.org/publication/big-bang-tax-reform-unleashing-growth-in-the-canadian-economy/",
          "content": "Small businesses are given preferential corporate income and payroll tax rates. Canadian-controlled private corporations face a small",
          "ai_analysis": "This evidence explicitly states that small businesses receive preferential corporate income and payroll tax rates, directly opposing the claim that they are taxed at higher rates than corporations."
        },
        {
          "stance": "background",
          "evidence_quality": "usable",
          "url": "https://www.bnnbloomberg.ca/business/2025/09/11/canadian-small-businesses-pay-about-20-per-cent-more-in-taxes-than-us-companies-cfib/",
          "content": "Canadian small businesses pay more taxes than a corporation of ... “Currently, the federal small business income tax rate is nine per cent.",
          "ai_analysis": "This evidence mentions a specific federal small business income tax rate but does not provide a comparative rate for corporations. Therefore, it does not offer enough information to support or contradict the claim about relative tax rates."
        }
      ],
      "metadata": {
        "retrieval_query_used": "Were taxing our small businesses now at rates higher than corporations.",
        "fallback_used": false,
        "search_raw_evidence_count": 8,
        "selected_evidence_count": 2
      }
    },
    {
      "claim_group_id": 5,
      "fact_claim_id": 1,
      "original_sentence": "The minimum wage has risen $2.35 in the last two years. Thats 31 percent.",
      "text_feature_text": "The minimum wage has risen $2.35 in the last two years. Thats 31 percent.",
      "claim": "The minimum wage has risen $2.35 in the last two years. Thats 31 percent.",
      "status": "success",
      "truth_score": 0.09999999999999998,
      "verdict": "False",
      "explanation": "Evidence 1 directly addresses the claim regarding a $2.35 or 31 percent minimum wage increase in two years, stating that Senator Raptakis's claim was misrepresented. It clarifies that the senator was referring to a potential future increase and that the actual increase over the past two years was significantly less, thereby contradicting the claim.",
      "decision_confidence": "low",
      "evidence_sufficiency": "insufficient",
      "evidence": [
        {
          "stance": "contradicts",
          "evidence_quality": "usable",
          "url": "https://www.politifact.com/factchecks/2015/feb/16/leonidas-raptakis/ri-sen-leonidas-raptakis-says-state-minimum-wage-r/",

In [30]:
# Cell 9: build a compact verdict table
summary_rows = []

for factual_claim in fact_checking_result.factual_claims:
    gold = gold_df.loc[gold_df["claim_group_id"] == factual_claim.claim_group_id].iloc[0]
    summary_rows.append({
        "claim_group_id": factual_claim.claim_group_id,
        "row_index": gold["row_index"],
        "claim": factual_claim.claim,
        "liar_label": gold["liar_label"],
        "mapped_expected_verdict": gold["mapped_expected_verdict"],
        "backend_status": factual_claim.status,
        "backend_verdict": factual_claim.verdict,
        "truth_score": factual_claim.truth_score,
        "decision_confidence": factual_claim.decision_confidence,
        "evidence_sufficiency": factual_claim.evidence_sufficiency,
        "raw_evidence_count": factual_claim.metadata.search_raw_evidence_count,
        "selected_evidence_count": factual_claim.metadata.selected_evidence_count,
        "retrieval_query_used": factual_claim.metadata.retrieval_query_used,
        "verdict_matches_label_map": factual_claim.verdict == gold["mapped_expected_verdict"],
    })

summary_df = pd.DataFrame(summary_rows)
print("overall_status:", fact_checking_result.status)
print("overall_truth_score:", fact_checking_result.truth_score)
print("overall_verdict:", fact_checking_result.verdict)
print("overall_explanation:", fact_checking_result.explanation)
display(summary_df)

overall_status: success
overall_truth_score: 0.47333333333333333
overall_verdict: Neutral
overall_explanation: Aggregated mean truth score over 5 successful factual claim(s).

,claim_group_id,row_index,claim,liar_label,mapped_expected_verdict,backend_status,backend_verdict,truth_score,decision_confidence,evidence_sufficiency,raw_evidence_count,selected_evidence_count,retrieval_query_used,verdict_matches_label_map
0,1,62,Says Bill and Hillary Clinton attended Donald ...,true,True,success,True,0.900000,medium,sufficient,8,3,Bill and Hillary Clinton attended Donald Trump...,True
1,2,432,"We have an Army that just cut 40,000 spots.",mostly-true,Mostly True,success,True,0.900000,medium,sufficient,8,3,"We have an Army that just cut 40,000 spots.",False
2,3,763,"When you read the Koran, it talks about dont t...",half-true,Neutral,success,Mostly False,0.366667,medium,sufficient,8,3,"When you read the Koran, it talks about don't ...",False
3,4,466,Were taxing our small businesses now at rates ...,barely-true,Mostly False,success,False,0.100000,low,sufficient,8,2,Were taxing our small businesses now at rates ...,False
4,5,745,The minimum wage has risen $2.35 in the last t...,false,False,success,False,0.100000,low,insufficient,8,3,The minimum wage has risen $2.35 in the last t...,True

In [31]:
# Cell 10: inspect selected evidence behind each verdict
evidence_rows = []

for factual_claim in fact_checking_result.factual_claims:
    for evidence_index, evidence in enumerate(factual_claim.evidence, start=1):
        evidence_rows.append({
            "claim_group_id": factual_claim.claim_group_id,
            "fact_claim_id": factual_claim.fact_claim_id,
            "evidence_index": evidence_index,
            "stance": evidence.stance,
            "evidence_quality": evidence.evidence_quality,
            "url": evidence.url,
            "content_preview": evidence.content[:500],
            "ai_analysis": evidence.ai_analysis,
        })

evidence_df = pd.DataFrame(evidence_rows)
display(evidence_df)

,claim_group_id,fact_claim_id,evidence_index,stance,evidence_quality,url,content_preview,ai_analysis
0,1,1,1,supports,strong,https://www.politifact.com/factchecks/2015/jul...,Says Bill and Hillary Clinton attended Donald ...,This evidence explicitly states that Bill and ...
1,1,1,2,supports,strong,https://people.com/celebrity/hillary-clinton-a...,"Back in 2005, Bill and Hillary Clinton were VI...",This source confirms that Bill and Hillary Cli...
2,1,1,3,background,weak,https://www.vanityfair.com/news/2016/08/donald...,# Donald Trump Was Reportedly Desperate to Att...,This evidence mentions Donald Trump inviting B...
3,2,1,1,supports,strong,https://www.defensenews.com/breaking-news/2015...,WASHINGTON — The US Army announced a plan to c...,This source directly states that the US Army a...
4,2,1,2,supports,usable,https://www.news-leader.com/story/news/local/o...,# U.S. Army to cut 774 positions at Fort Leona...,"This source confirms the 40,000 cuts across th..."
5,2,1,3,supports,weak,https://www.thetowntalk.com/story/news/2015/08...,that increases the threats and danger to the U...,This source mentions that the Army is 'getting...
6,3,1,1,supports,strong,https://myislam.org/surah-maidah/ayat-51/,The My Islam App is the ultimate ad-free compa...,This evidence directly quotes the Qur'an multi...
7,3,1,2,contradicts,strong,https://www.alislam.org/articles/is-it-true-th...,# Is it true that the Quran says to not take t...,This evidence claims that the verse often cite...
8,3,1,3,contradicts,strong,https://ask.ghamidi.org/forums/discussion/11242/,Allah forbids His believing servants from havi...,This evidence argues that the verse refers onl...
9,4,1,1,contradicts,strong,https://cdhowe.org/publication/big-bang-tax-re...,Small businesses are given preferential corpor...,This evidence explicitly states that small bus...
10,4,1,2,background,usable,https://www.bnnbloomberg.ca/business/2025/09/1...,Canadian small businesses pay more taxes than ...,This evidence mentions a specific federal smal...
11,5,1,1,contradicts,usable,https://www.politifact.com/factchecks/2015/feb...,# R.I. Sen. Leonidas Raptakis says state minim...,This evidence contradicts the claim by stating...
12,5,1,2,background,weak,https://dol.ny.gov/history-minimum-wage-new-yo...,# History of the Minimum Wage in New York Stat...,This evidence provides historical data on mini...
13,5,1,3,background,weak,https://www.littler.com/news-analysis/asap/202...,"Effective December 31, 2020, such employers ma...",This evidence discusses minimum wage and tip c...

In [32]:
# Cell 11: run one chosen LIAR row as a deep dive
TARGET_ROW_INDEX = int(sample_df.loc[0, "row_index"])

target_row = liar_df.loc[TARGET_ROW_INDEX]
target_claim = str(target_row["statement"]).strip()
target_claim_groups = [
    {
        "claim_group_id": 1,
        "original_sentence": target_claim,
        "text_feature_text": target_claim,
        "atomization_applied": False,
        "factual_claims": [
            {
                "fact_claim_id": 1,
                "claim": target_claim,
            }
        ],
    }
]

target_result = analyze_fact_check_claims(target_claim_groups, options)

print("row_index:", TARGET_ROW_INDEX)
print("liar_label:", target_row["label"])
print("mapped_expected_verdict:", liar_label_to_verdict.get(target_row["label"], ""))
print("claim:", target_claim)
print(json.dumps(target_result.model_dump(), indent=2, ensure_ascii=False))

[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
row_index: 62
liar_label: true
mapped_expected_verdict: True
claim: Says Bill and Hillary Clinton attended Donald Trumps last wedding.
{
  "status": "success",
  "truth_score": 0.9,
  "verdict": "True",
  "explanation": "Aggregated mean truth score over 1 successful factual claim(s).",
  "factual_claims": [
    {
      "claim_group_id": 1,
      "fact_claim_id": 1,
      "original_sentence": "Says Bill and Hillary Clinton attended Donald Trumps last wedding.",
      "text_feature_text": "Says Bill and Hillary Clinton attended Donald Trumps last wedding.",
      "claim": "Says Bill and Hillary Clinton attended Donald Trumps last wedding.",
      "status": "success",
      "truth_score": 0.9,
      "verdict": "True",
      "explanation": "The evidence directly states that Bill and Hillary Clinton attended Donald Trump's wedding to Melania Knauss on January 22, 2005. Multiple pieces of evidence corroborate this, including a Bloomberg article title and MSNBC reporting on Trump's invitation to Hillary Clinton for his nuptials. Therefore, the claim is supported by the provided evidence.",
      "decision_confidence": "medium",
      "evidence_sufficiency": "sufficient",
      "evidence": [
        {
          "stance": "supports",
          "evidence_quality": "strong",
          "url": "https://www.politifact.com/factchecks/2015/jul/21/carlos-curbelo/clintons-really-did-attend-donald-trumps-2005-wedd/",
          "content": "Says Bill and Hillary Clinton attended Donald Trump's last wedding. Bill and Hillary Clinton chat with Donald Trump during the reception for his wedding to Melania Knauss in Palm Beach, Fla., on Jan. 22, 2005. Bill and Hillary Clinton chat with Donald Trump during the reception for his wedding to Melania Knauss in Palm Beach, Fla., on Jan. 22, 2005. (Getty Images)    Bill and Hillary Clinton chat with Donald Trump during the reception for his wedding to Melania Knauss in Palm Beach, Fla., on Jan. 22, 2005. Republican presidential candidate Donald Trump’s controversial campaign could just be a ruse to sabotage the GOP, said U.S. Rep. Carlos Curbelo, R-Fla. After all, the billionaire is so friendly with Hillary Clinton, Trump invited her to his nuptials. Curbelo said Bill and Hillary Clinton were at Donald Trump's last wedding. Bloomberg, \"FYI: Hillary Clinton Had a Front-Pew Seat at Donald Trump's Wedding,\" June 16, 2015. MSNBC, \"Donald Trump’s change of heart on Hillary Clinton,\" July 8, 2015.",
          "ai_analysis": "This evidence directly supports the claim by stating that Bill and Hillary Clinton attended Donald Trump's wedding to Melania Knauss on January 22, 2005. It mentions they were at the reception and quotes a congressman stating they were at Trump's last wedding. The inclusion of article titles from Bloomberg and MSNBC further reinforces this."
        },
        {
          "stance": "supports",
          "evidence_quality": "strong",
          "url": "https://people.com/celebrity/hillary-clinton-and-bill-clinton-at-donald-trumps-wedding-photo/",
          "content": "Back in 2005, Bill and Hillary Clinton were VIP guests at Donald Trump's wedding to his wife Melania – and it sure looks like all four had a pretty good time.",
          "ai_analysis": "This evidence directly supports the claim by stating that Bill and Hillary Clinton were VIP guests at Donald Trump's wedding to Melania in 2005 and that they appeared to have had a good time."
        },
        {
          "stance": "background",
          "evidence_quality": "weak",
          "url": "https://www.vanityfair.com/news/2016/08/donald-trump-chelsea-clinton-wedding?srsltid=AfmBOoobZyWX8exleLm87N2vQWj-IVQx3q2_0XaHJ78YOTg419slN69_",
          "content": "# Donald Trump Was Reportedly Desperate to Attend Chelsea Clinton’s Wedding. Image may contain Chelsea Clinton Marc Mezvinsky Clothing Apparel Human Person Fashion Robe Gown and Wedding. But there was perhaps no hotter ticket in 2010 than **Chelsea Clinton’s** 500-person, several million-dollar wedding in upstate New York. This was *the* wedding, so of course **Donald Trump** wanted to be there. Trump, now somewhat infamously, had invited Bill and **Hillary** to his own third wedding years earlier. “The real estate mogul was the sort of person who, though not an actual friend, still aspired to attend Chelsea’s wedding, which he clearly considered a prestigious event,” Conason writes. “I’m supposed to be at the wedding, Doug,” Trump said, according to Conason. But it is good to know that Trump, transgressor of societal norms, politeness, and often, general decency, draws the line somewhere, and apparently it stops at wedding crashing. This image may contain Human Person Clothing Apparel and Ivana Trump.",
          "ai_analysis": "This evidence discusses Donald Trump's desire to attend Chelsea Clinton's wedding and mentions that Trump had invited Bill and Hillary Clinton to his own third wedding years earlier. While it references Trump's wedding invitation to the Clintons, its primary focus is on Trump's interest in Chelsea's wedding, making it background information rather than direct support or contradiction of the claim about the Clintons attending Trump's last wedding."
        }
      ],
      "metadata": {
        "retrieval_query_used": "Bill and Hillary Clinton attended Donald Trump's last wedding.",
        "fallback_used": false,
        "search_raw_evidence_count": 8,
        "selected_evidence_count": 3
      }
    }
  ]
}

In [33]:
# Cell 12: rerun the deep dive with looser evidence selection
looser_options = AnalysisOptions(
    use_query_rewrite=True,
    relevance_threshold=0.05,
    use_oversampling_retry=True,
    use_selective_stabilization=True,
    top_k=5,
    use_all_eligible_evidence=False,
    retrieval_results=12,
)

looser_result = analyze_fact_check_claims(target_claim_groups, looser_options)
print(json.dumps(looser_result.model_dump(), indent=2, ensure_ascii=False))

[Search] Retrieved 12 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 12 results | Filtered shell: 0 | Deduplicated: 0
{
  "status": "success",
  "truth_score": 0.9,
  "verdict": "True",
  "explanation": "Aggregated mean truth score over 1 successful factual claim(s).",
  "factual_claims": [
    {
      "claim_group_id": 1,
      "fact_claim_id": 1,
      "original_sentence": "Says Bill and Hillary Clinton attended Donald Trumps last wedding.",
      "text_feature_text": "Says Bill and Hillary Clinton attended Donald Trumps last wedding.",
      "claim": "Says Bill and Hillary Clinton attended Donald Trumps last wedding.",
      "status": "success",
      "truth_score": 0.9,
      "verdict": "True",
      "explanation": "The provided evidence consistently states that Bill and Hillary Clinton attended Donald Trump's wedding to Melania Knauss in 2005. Multiple sources confirm their presence at the event, some even mentioning them chatting with Donald Trump during the reception. This directly supports the claim that they attended his last wedding.",
      "decision_confidence": "high",
      "evidence_sufficiency": "sufficient",
      "evidence": [
        {
          "stance": "supports",
          "evidence_quality": "strong",
          "url": "https://www.politifact.com/factchecks/2015/jul/21/carlos-curbelo/clintons-really-did-attend-donald-trumps-2005-wedd/",
          "content": "Says Bill and Hillary Clinton attended Donald Trump's last wedding. Bill and Hillary Clinton chat with Donald Trump during the reception for his wedding to Melania Knauss in Palm Beach, Fla., on Jan. 22, 2005. Bill and Hillary Clinton chat with Donald Trump during the reception for his wedding to Melania Knauss in Palm Beach, Fla., on Jan. 22, 2005. (Getty Images)    Bill and Hillary Clinton chat with Donald Trump during the reception for his wedding to Melania Knauss in Palm Beach, Fla., on Jan. 22, 2005. Republican presidential candidate Donald Trump’s controversial campaign could just be a ruse to sabotage the GOP, said U.S. Rep. Carlos Curbelo, R-Fla. After all, the billionaire is so friendly with Hillary Clinton, Trump invited her to his nuptials. Curbelo said Bill and Hillary Clinton were at Donald Trump's last wedding. Bloomberg, \"FYI: Hillary Clinton Had a Front-Pew Seat at Donald Trump's Wedding,\" June 16, 2015. MSNBC, \"Donald Trump’s change of heart on Hillary Clinton,\" July 8, 2015.",
          "ai_analysis": "This evidence explicitly states that Bill and Hillary Clinton attended Donald Trump's wedding to Melania Knauss on January 22, 2005, and includes a quote from a Congressman mentioning their attendance. It directly supports the claim."
        },
        {
          "stance": "supports",
          "evidence_quality": "strong",
          "url": "https://people.com/celebrity/hillary-clinton-and-bill-clinton-at-donald-trumps-wedding-photo/",
          "content": "Back in 2005, Bill and Hillary Clinton were VIP guests at Donald Trump's wedding to his wife Melania – and it sure looks like all four had a pretty good time.",
          "ai_analysis": "This source confirms that Bill and Hillary Clinton were 'VIP guests' at Donald Trump's wedding to Melania in 2005, directly supporting the claim."
        },
        {
          "stance": "supports",
          "evidence_quality": "strong",
          "url": "https://www.pinterest.com/dangerousdan9317/bill-clinton-and-hillary-clinton-attend-donald-tru/",
          "content": "Explore a hand-picked collection of Pins about bill clinton and hillary clinton attend donald trump and melania trump wedding 2005 on Pinterest.",
          "ai_analysis": "This evidence refers to Pins about 'bill clinton and hillary clinton attend donald trump and melania trump wedding 2005', indicating their attendance and thus supporting the claim."
        },
        {
          "stance": "supports",
          "evidence_quality": "usable",
          "url": "https://www.scmp.com/magazines/style/celebrity/article/3152889/5-surprising-celebrity-guests-donald-and-melania-trumps",
          "content": "# 5 surprising celebrity guests at Donald and Melania Trump’s wedding – Anna Wintour, Elton John and Gayle King attended, but were Bill and Hillary Clinton really paid to go? Celebrities like Elton John, Hillary Clinton, Anna Wintour and Gayle King attended Donald and Melania Trump’s 2005 wedding ... ### * Vogue’s Anna Wintour, Billy Joel and Oprah’s pal Gayle King all attended the lavish Mar-a-Lago ceremony – but didn’t support the Trump presidency * The reality TV star almost gave Kim Jong-un a copy of Elton John’s single Rocket Man even though the singer refused to associate his music with Trump’s campaign. British singer Elton John performs during his Farewell Yellow Brick Road tour at the 53rd Montreux Jazz Festival (MJF), in Montreux, Switzerland, in June 2019. Photo: AP, in Montreux, Switzerland, in June 2019. Elton John and Donald Trump appear to have been acquainted in the past.",
          "ai_analysis": "This source lists Bill and Hillary Clinton among celebrity guests who attended Donald and Melania Trump's 2005 wedding, directly supporting the claim."
        },
        {
          "stance": "supports",
          "evidence_quality": "weak",
          "url": "https://abcnews.com/Politics/trump-money-drew-hillary-clinton-wedding/story?id=32936868",
          "content": "### ABC News Live. # Donald Trump Says His Money Drew Hillary Clinton to His Wedding. \"She had no choice because I gave to a foundation,\" the Donald said. &#151; -- Donald Trump’s millions have snagged him favors from several prominent politicians -– including Democratic rival Hillary Clinton, he said tonight. “Hillary Clinton, I said be at my wedding, and she came to my wedding,\" the reality-star-turned-politician said at the first GOP presidential debate in Cleveland. Then-Sen. Hillary Clinton was present at Trump’s 2005 wedding to model Melania Knauss -– and Clinton and her husband attended the reception together. “I gave to many people before this,” Trump said at the debate today. You explained away those donations saying you did that to get business-related affairs,” Paul said. “You better believe it,” Trump responded. The Clinton campaign spokeswoman Jennifer Palmieri said Trump's comment \"hurts [Sec. Clinton's] feelings.\". ## Roommate charged with murder of 2 USF doctoral students: Sheriff.",
          "ai_analysis": "This evidence confirms that Hillary Clinton attended Trump's 2005 wedding and that her husband, Bill Clinton, also attended the reception with her, directly supporting the claim."
        }
      ],
      "metadata": {
        "retrieval_query_used": "Bill and Hillary Clinton attended Donald Trump's last wedding.",
        "fallback_used": false,
        "search_raw_evidence_count": 12,
        "selected_evidence_count": 5
      }
    }
  ]
}

In [34]:
# Cell 13: audit raw retrieval and evidence filtering for one claim
from fact_checking.gemini_agent import prepare_claim_for_fact_checking
from fact_checking.retrieval_service import choose_evidence, retrieve_evidence

AUDIT_ROW_INDEX = TARGET_ROW_INDEX

audit_row = liar_df.loc[AUDIT_ROW_INDEX]
audit_claim = str(audit_row["statement"]).strip()
claim_check = prepare_claim_for_fact_checking(
    audit_claim,
    use_query_rewrite=options.use_query_rewrite,
)

print("row_index:", AUDIT_ROW_INDEX)
print("liar_label:", audit_row["label"])
print("claim:", audit_claim)
print("claim_valid:", claim_check.is_valid_claim)
print("final_claim_for_search:", claim_check.final_claim)

retrieval = retrieve_evidence(
    original_claim=audit_claim,
    final_claim=claim_check.final_claim,
    retrieval_results=options.retrieval_results,
    use_oversampling_retry=options.use_oversampling_retry,
)

raw_rows = []
for index, evidence_item in enumerate(retrieval.raw_evidence, start=1):
    raw_rows.append({
        "raw_index": index,
        "url": evidence_item.get("url", ""),
        "source_quality": evidence_item.get("source_quality", ""),
        "source_quality_score": evidence_item.get("source_quality_score", ""),
        "content_preview": evidence_item.get("content", "")[:500],
    })

print("retrieval_query_used:", retrieval.final_claim)
print("retrieval_error_type:", retrieval.error_type)
print("retrieval_error_message:", retrieval.error_message)
print("raw_evidence_count:", retrieval.search_raw_count)
display(pd.DataFrame(raw_rows))

if retrieval.raw_evidence:
    selection = choose_evidence(
        original_claim=audit_claim,
        final_claim=retrieval.final_claim,
        raw_evidence=retrieval.raw_evidence,
        relevance_threshold=options.relevance_threshold,
        top_k=options.top_k,
        use_all_eligible_evidence=options.use_all_eligible_evidence,
        retrieval_results=options.retrieval_results,
        use_oversampling_retry=options.use_oversampling_retry,
    )

    selected_urls = {evidence.url for evidence in selection.selected_evidence}
    scored_rows = []
    for item in selection.filter_debug.get("scored_evidence", []):
        scored_rows.append({
            "selected_for_verdict": item.get("url", "") in selected_urls,
            "filter_reason": item.get("filter_reason", ""),
            "passed_threshold": item.get("passed_threshold", ""),
            "evidence_quality": item.get("evidence_quality", ""),
            "source_quality": item.get("source_quality", ""),
            "relevance_score": item.get("relevance_score", ""),
            "claim_match_score": item.get("claim_match_score", ""),
            "number_score": item.get("number_score", ""),
            "number_status": item.get("number_status", ""),
            "final_match_score": item.get("final_match_score", ""),
            "selection_priority": item.get("selection_priority", ""),
            "url": item.get("url", ""),
            "content_preview": item.get("content_preview", ""),
        })

    selected_rows = []
    for index, evidence in enumerate(selection.selected_evidence, start=1):
        selected_rows.append({
            "selected_index": index,
            "evidence_quality": evidence.evidence_quality,
            "url": evidence.url,
            "content_preview": evidence.content[:500],
        })

    print("selection_final_claim:", selection.final_claim)
    print("selection_fallback_used:", selection.fallback_used)
    print("selected_evidence_count:", len(selection.selected_evidence))
    display(pd.DataFrame(scored_rows))
    display(pd.DataFrame(selected_rows))

row_index: 62
liar_label: true
claim: Says Bill and Hillary Clinton attended Donald Trumps last wedding.
claim_valid: True
final_claim_for_search: Bill and Hillary Clinton attended Donald Trump's last wedding.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
retrieval_query_used: Bill and Hillary Clinton attended Donald Trump's last wedding.
retrieval_error_type:
retrieval_error_message:
raw_evidence_count: 8

,raw_index,url,source_quality,source_quality_score,content_preview
0,1,https://www.politifact.com/factchecks/2015/jul...,fact_check,0.95,Says Bill and Hillary Clinton attended Donald ...
1,2,https://people.com/celebrity/hillary-clinton-a...,general_web,0.65,"Back in 2005, Bill and Hillary Clinton were VI..."
2,3,https://www.imdb.com/news/ni62002572/,general_web,0.65,Donald Trump and Hillary Clinton used to be so...
3,4,https://www.vanityfair.com/news/2016/08/donald...,general_web,0.65,# Donald Trump Was Reportedly Desperate to Att...
4,5,https://www.cnn.com/2015/08/10/politics/clinto...,general_web,0.65,Why did Hillary Clinton go to Donald Trump's 2...
5,6,https://www.politico.com/magazine/story/2015/0...,general_web,0.65,Bo Dietl went to Donald Trump's third wedding ...
6,7,https://time.com/3988313/donald-trump-hillary-...,general_web,0.65,Donald Trump was hit in both the undercard and...
7,8,https://www.npr.org/2016/07/07/485058639/exami...,general_web,0.65,SANDERS: D'Antonio says the relationship betwe...

selection_final_claim: Bill and Hillary Clinton attended Donald Trump's last wedding.
selection_fallback_used: False
selected_evidence_count: 3

,selected_for_verdict,filter_reason,passed_threshold,evidence_quality,source_quality,relevance_score,claim_match_score,number_score,number_status,final_match_score,selection_priority,url,content_preview
0,True,passed,True,strong,fact_check,0.992877,1.000000,0.5,not_needed,0.921082,0.916794,https://www.politifact.com/factchecks/2015/jul...,Says Bill and Hillary Clinton attended Donald ...
1,True,passed,True,strong,general_web,0.992102,0.762238,0.5,not_needed,0.849327,0.815117,https://people.com/celebrity/hillary-clinton-a...,"Back in 2005, Bill and Hillary Clinton were VI..."
2,True,passed,True,weak,general_web,0.002077,0.643357,0.5,not_needed,0.269149,0.333942,https://www.vanityfair.com/news/2016/08/donald...,# Donald Trump Was Reportedly Desperate to Att...
3,False,passed,True,weak,general_web,0.002760,0.594406,0.5,not_needed,0.254840,0.319564,https://www.cnn.com/2015/08/10/politics/clinto...,Why did Hillary Clinton go to Donald Trump's 2...
4,False,passed,True,weak,general_web,0.011277,0.566434,0.5,not_needed,0.251132,0.315005,https://www.imdb.com/news/ni62002572/,Donald Trump and Hillary Clinton used to be so...
5,False,passed,True,weak,general_web,0.001696,0.545455,0.5,not_needed,0.239569,0.304399,https://www.npr.org/2016/07/07/485058639/exami...,SANDERS: D'Antonio says the relationship betwe...
6,False,low_claim_match,False,weak,general_web,0.031486,0.356643,0.5,not_needed,0.199310,0.261162,https://www.politico.com/magazine/story/2015/0...,Bo Dietl went to Donald Trump's third wedding ...
7,False,low_claim_match,False,weak,general_web,0.000383,0.307692,0.5,not_needed,0.167518,0.232480,https://time.com/3988313/donald-trump-hillary-...,Donald Trump was hit in both the undercard and...

,selected_index,evidence_quality,url,content_preview
0,1,strong,https://www.politifact.com/factchecks/2015/jul...,Says Bill and Hillary Clinton attended Donald ...
1,2,strong,https://people.com/celebrity/hillary-clinton-a...,"Back in 2005, Bill and Hillary Clinton were VI..."
2,3,weak,https://www.vanityfair.com/news/2016/08/donald...,# Donald Trump Was Reportedly Desperate to Att...

In [35]:
# Cell 13.466: audit raw retrieval and evidence filtering for one claim
from fact_checking.gemini_agent import prepare_claim_for_fact_checking
from fact_checking.retrieval_service import choose_evidence, retrieve_evidence

AUDIT_ROW_INDEX = 466

audit_row = liar_df.loc[AUDIT_ROW_INDEX]
audit_claim = str(audit_row["statement"]).strip()
claim_check = prepare_claim_for_fact_checking(
    audit_claim,
    use_query_rewrite=options.use_query_rewrite,
)

print("row_index:", AUDIT_ROW_INDEX)
print("liar_label:", audit_row["label"])
print("claim:", audit_claim)
print("claim_valid:", claim_check.is_valid_claim)
print("final_claim_for_search:", claim_check.final_claim)

retrieval = retrieve_evidence(
    original_claim=audit_claim,
    final_claim=claim_check.final_claim,
    retrieval_results=options.retrieval_results,
    use_oversampling_retry=options.use_oversampling_retry,
)

raw_rows = []
for index, evidence_item in enumerate(retrieval.raw_evidence, start=1):
    raw_rows.append({
        "raw_index": index,
        "url": evidence_item.get("url", ""),
        "source_quality": evidence_item.get("source_quality", ""),
        "source_quality_score": evidence_item.get("source_quality_score", ""),
        "content_preview": evidence_item.get("content", "")[:500],
    })

print("retrieval_query_used:", retrieval.final_claim)
print("retrieval_error_type:", retrieval.error_type)
print("retrieval_error_message:", retrieval.error_message)
print("raw_evidence_count:", retrieval.search_raw_count)
display(pd.DataFrame(raw_rows))

if retrieval.raw_evidence:
    selection = choose_evidence(
        original_claim=audit_claim,
        final_claim=retrieval.final_claim,
        raw_evidence=retrieval.raw_evidence,
        relevance_threshold=options.relevance_threshold,
        top_k=options.top_k,
        use_all_eligible_evidence=options.use_all_eligible_evidence,
        retrieval_results=options.retrieval_results,
        use_oversampling_retry=options.use_oversampling_retry,
    )

    selected_urls = {evidence.url for evidence in selection.selected_evidence}
    scored_rows = []
    for item in selection.filter_debug.get("scored_evidence", []):
        scored_rows.append({
            "selected_for_verdict": item.get("url", "") in selected_urls,
            "filter_reason": item.get("filter_reason", ""),
            "passed_threshold": item.get("passed_threshold", ""),
            "evidence_quality": item.get("evidence_quality", ""),
            "source_quality": item.get("source_quality", ""),
            "relevance_score": item.get("relevance_score", ""),
            "claim_match_score": item.get("claim_match_score", ""),
            "number_score": item.get("number_score", ""),
            "number_status": item.get("number_status", ""),
            "final_match_score": item.get("final_match_score", ""),
            "selection_priority": item.get("selection_priority", ""),
            "url": item.get("url", ""),
            "content_preview": item.get("content_preview", ""),
        })

    selected_rows = []
    for index, evidence in enumerate(selection.selected_evidence, start=1):
        selected_rows.append({
            "selected_index": index,
            "evidence_quality": evidence.evidence_quality,
            "url": evidence.url,
            "content_preview": evidence.content[:500],
        })

    print("selection_final_claim:", selection.final_claim)
    print("selection_fallback_used:", selection.fallback_used)
    print("selected_evidence_count:", len(selection.selected_evidence))
    display(pd.DataFrame(scored_rows))
    display(pd.DataFrame(selected_rows))

row_index: 466
liar_label: barely-true
claim: Were taxing our small businesses now at rates higher than corporations.
claim_valid: True
final_claim_for_search: Were taxing our small businesses now at rates higher than corporations.
[Search] Retrieved 8 results | Filtered shell: 1 | Deduplicated: 0
retrieval_query_used: Were taxing our small businesses now at rates higher than corporations.
retrieval_error_type:
retrieval_error_message:
raw_evidence_count: 7

,raw_index,url,source_quality,source_quality_score,content_preview
0,1,https://waysandmeans.house.gov/2024/12/17/top-...,official,0.90,Twenty-six million businesses could see their ...
1,2,https://www.nationwide.com/business/solutions-...,general_web,0.65,The average for all small businesses may be 19...
2,3,https://www.uschamber.com/taxes/how-higher-cor...,general_web,0.65,Studies have shown that raising the corporate ...
3,4,https://www.sciencedirect.com/science/article/...,general_web,0.65,We study the impact of corporate taxes on firm...
4,5,https://equitablegrowth.org/six-years-later-mo...,general_web,0.65,"In total, 81 percent of the gains from the Tax..."
5,6,https://www.brookings.edu/articles/9-facts-abo...,official,0.90,Pass-through businesses pay lower tax rates th...
6,7,https://www.pgpf.org/article/six-charts-that-s...,general_web,0.65,The federal statutory tax rate on corporate in...

selection_final_claim: Were taxing our small businesses now at rates higher than corporations.
selection_fallback_used: False
selected_evidence_count: 1

,selected_for_verdict,filter_reason,passed_threshold,evidence_quality,source_quality,relevance_score,claim_match_score,number_score,number_status,final_match_score,selection_priority,url,content_preview
0,False,low_claim_match,False,weak,general_web,0.985502,0.00000,0.5,not_needed,0.617026,0.583476,https://www.sciencedirect.com/science/article/...,We study the impact of corporate taxes on firm...
1,False,low_claim_match,False,weak,general_web,0.970493,0.00000,0.5,not_needed,0.608771,0.576722,https://www.uschamber.com/taxes/how-higher-cor...,Studies have shown that raising the corporate ...
2,False,low_claim_match,False,weak,general_web,0.741211,0.08750,0.5,not_needed,0.508916,0.499795,https://equitablegrowth.org/six-years-later-mo...,"In total, 81 percent of the gains from the Tax..."
3,True,passed,True,weak,official,0.294786,0.53125,0.5,not_needed,0.396507,0.457029,https://www.brookings.edu/articles/9-facts-abo...,Pass-through businesses pay lower tax rates th...
4,False,low_claim_match,False,weak,general_web,0.060843,0.33750,0.5,not_needed,0.209714,0.268630,https://www.nationwide.com/business/solutions-...,The average for all small businesses may be 19...
5,False,low_claim_match,False,weak,official,0.012498,0.31875,0.5,not_needed,0.177499,0.266249,https://waysandmeans.house.gov/2024/12/17/top-...,Twenty-six million businesses could see their ...
6,False,low_claim_match,False,weak,general_web,0.002207,0.00000,0.5,not_needed,0.076214,0.140993,https://www.pgpf.org/article/six-charts-that-s...,The federal statutory tax rate on corporate in...

,selected_index,evidence_quality,url,content_preview
0,1,weak,https://www.brookings.edu/articles/9-facts-abo...,Pass-through businesses pay lower tax rates th...

In [36]:
# Cell 13.745: audit raw retrieval and evidence filtering for one claim
from fact_checking.gemini_agent import prepare_claim_for_fact_checking
from fact_checking.retrieval_service import choose_evidence, retrieve_evidence

AUDIT_ROW_INDEX = 745

audit_row = liar_df.loc[AUDIT_ROW_INDEX]
audit_claim = str(audit_row["statement"]).strip()
claim_check = prepare_claim_for_fact_checking(
    audit_claim,
    use_query_rewrite=options.use_query_rewrite,
)

print("row_index:", AUDIT_ROW_INDEX)
print("liar_label:", audit_row["label"])
print("claim:", audit_claim)
print("claim_valid:", claim_check.is_valid_claim)
print("final_claim_for_search:", claim_check.final_claim)

retrieval = retrieve_evidence(
    original_claim=audit_claim,
    final_claim=claim_check.final_claim,
    retrieval_results=options.retrieval_results,
    use_oversampling_retry=options.use_oversampling_retry,
)

raw_rows = []
for index, evidence_item in enumerate(retrieval.raw_evidence, start=1):
    raw_rows.append({
        "raw_index": index,
        "url": evidence_item.get("url", ""),
        "source_quality": evidence_item.get("source_quality", ""),
        "source_quality_score": evidence_item.get("source_quality_score", ""),
        "content_preview": evidence_item.get("content", "")[:500],
    })

print("retrieval_query_used:", retrieval.final_claim)
print("retrieval_error_type:", retrieval.error_type)
print("retrieval_error_message:", retrieval.error_message)
print("raw_evidence_count:", retrieval.search_raw_count)
display(pd.DataFrame(raw_rows))

if retrieval.raw_evidence:
    selection = choose_evidence(
        original_claim=audit_claim,
        final_claim=retrieval.final_claim,
        raw_evidence=retrieval.raw_evidence,
        relevance_threshold=options.relevance_threshold,
        top_k=options.top_k,
        use_all_eligible_evidence=options.use_all_eligible_evidence,
        retrieval_results=options.retrieval_results,
        use_oversampling_retry=options.use_oversampling_retry,
    )

    selected_urls = {evidence.url for evidence in selection.selected_evidence}
    scored_rows = []
    for item in selection.filter_debug.get("scored_evidence", []):
        scored_rows.append({
            "selected_for_verdict": item.get("url", "") in selected_urls,
            "filter_reason": item.get("filter_reason", ""),
            "passed_threshold": item.get("passed_threshold", ""),
            "evidence_quality": item.get("evidence_quality", ""),
            "source_quality": item.get("source_quality", ""),
            "relevance_score": item.get("relevance_score", ""),
            "claim_match_score": item.get("claim_match_score", ""),
            "number_score": item.get("number_score", ""),
            "number_status": item.get("number_status", ""),
            "final_match_score": item.get("final_match_score", ""),
            "selection_priority": item.get("selection_priority", ""),
            "url": item.get("url", ""),
            "content_preview": item.get("content_preview", ""),
        })

    selected_rows = []
    for index, evidence in enumerate(selection.selected_evidence, start=1):
        selected_rows.append({
            "selected_index": index,
            "evidence_quality": evidence.evidence_quality,
            "url": evidence.url,
            "content_preview": evidence.content[:500],
        })

    print("selection_final_claim:", selection.final_claim)
    print("selection_fallback_used:", selection.fallback_used)
    print("selected_evidence_count:", len(selection.selected_evidence))
    display(pd.DataFrame(scored_rows))
    display(pd.DataFrame(selected_rows))

row_index: 745
liar_label: false
claim: The minimum wage has risen $2.35 in the last two years. Thats 31 percent.
claim_valid: True
final_claim_for_search: The minimum wage has risen $2.35 in the last two years, which is 31 percent.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
retrieval_query_used: The minimum wage has risen $2.35 in the last two years, which is 31 percent.
retrieval_error_type:
retrieval_error_message:
raw_evidence_count: 8

,raw_index,url,source_quality,source_quality_score,content_preview
0,1,https://www.politifact.com/factchecks/2015/feb...,fact_check,0.95,# R.I. Sen. Leonidas Raptakis says state minim...
1,2,https://dol.ny.gov/history-minimum-wage-new-yo...,official,0.90,# History of the Minimum Wage in New York Stat...
2,3,https://erd.dli.mt.gov/labor-standards/wage-an...,official,0.90,Javascript is disabled in your browser. Certai...
3,4,https://stacker.com/stories/business-economy/h...,general_web,0.65,Stacker took a look at all 50 states plus the ...
4,5,https://www.dol.gov/agencies/whd/minimum-wage/...,official,0.90,The table of federal minimum wage rates under ...
5,6,https://www.epi.org/minimum-wage-tracker/,general_web,0.65,Many states and localities have raised their o...
6,7,https://ogletree.com/insights-resources/blog-p...,general_web,0.65,##### Insights. #### Subscribe. The following ...
7,8,https://www.littler.com/news-analysis/asap/202...,general_web,0.65,"Effective December 31, 2020, such employers ma..."

selection_final_claim: The minimum wage has risen $2.35 in the last two years, which is 31 percent.
selection_fallback_used: False
selected_evidence_count: 3

,selected_for_verdict,filter_reason,passed_threshold,evidence_quality,source_quality,relevance_score,claim_match_score,number_score,number_status,final_match_score,selection_priority,url,content_preview
0,True,passed,True,usable,fact_check,0.180079,0.869159,1.0,exact_match,0.509791,0.586783,https://www.politifact.com/factchecks/2015/feb...,# R.I. Sen. Leonidas Raptakis says state minim...
1,True,passed,True,weak,official,0.003929,0.425234,1.0,exact_match,0.279731,0.369338,https://dol.ny.gov/history-minimum-wage-new-yo...,# History of the Minimum Wage in New York Stat...
2,True,passed,True,weak,general_web,0.003409,0.471963,1.0,exact_match,0.293464,0.358123,https://www.littler.com/news-analysis/asap/202...,"Effective December 31, 2020, such employers ma..."
3,False,passed,True,weak,official,0.123638,0.186916,1.0,exact_match,0.274075,0.351712,https://erd.dli.mt.gov/labor-standards/wage-an...,Javascript is disabled in your browser. Certai...
4,False,conflicting_claim_details,False,weak,general_web,0.003598,0.425234,0.2,conflict,0.159549,0.224189,https://stacker.com/stories/business-economy/h...,Stacker took a look at all 50 states plus the ...
5,False,conflicting_claim_details,False,weak,official,0.000211,0.285047,0.2,conflict,0.115630,0.205609,https://www.dol.gov/agencies/whd/minimum-wage/...,The table of federal minimum wage rates under ...
6,False,conflicting_claim_details,False,weak,general_web,0.001951,0.350467,0.2,conflict,0.136213,0.201018,https://ogletree.com/insights-resources/blog-p...,##### Insights. #### Subscribe. The following ...
7,False,below_relevance_threshold,False,weak,general_web,0.000179,0.126168,0.4,missing,0.097949,0.162931,https://www.epi.org/minimum-wage-tracker/,Many states and localities have raised their o...

,selected_index,evidence_quality,url,content_preview
0,1,usable,https://www.politifact.com/factchecks/2015/feb...,# R.I. Sen. Leonidas Raptakis says state minim...
1,2,weak,https://dol.ny.gov/history-minimum-wage-new-yo...,# History of the Minimum Wage in New York Stat...
2,3,weak,https://www.littler.com/news-analysis/asap/202...,"Effective December 31, 2020, such employers ma..."

In [37]:
# Cell 14: choose a larger balanced LIAR stability sample
STABILITY_RANDOM_SEED = 42
ROWS_PER_LABEL = 4
STABILITY_LABELS = ["true", "mostly-true", "half-true", "barely-true", "false", "pants-fire"]

stability_rows = []

for label in STABILITY_LABELS:
    label_rows = liar_df[liar_df["label"] == label]
    if label_rows.empty:
        continue

    n = min(ROWS_PER_LABEL, len(label_rows))
    stability_rows.append(label_rows.sample(n=n, random_state=STABILITY_RANDOM_SEED))

stability_df = pd.concat(stability_rows, ignore_index=True)
stability_df = stability_df.sample(frac=1, random_state=STABILITY_RANDOM_SEED).reset_index(drop=True)

print("Stability sample size:", len(stability_df))
display(stability_df[["row_index", "label", "statement", "speaker", "context"]])

Stability sample size: 24

,row_index,label,statement,speaker,context
0,822,half-true,"There are 60,000 fewer jobs today in this stat...",ovide-lamontagne,a Republican gubernatorial debate at Franklin ...
1,685,false,All the talk about socialism during the campai...,michael-moore,the movie Capitalism: A Love Story
2,971,true,Says Marco Rubio knows full well I voted for h...,ted-cruz,a Republican presidential debate in North Char...
3,519,false,Says in Texas its legal to shoot someone whos ...,robert-reich,a blog post
4,115,half-true,More (student-athletes) graduate than the stud...,mark-emmert,"comments on ABC's ""This Week"""
5,574,half-true,"As state treasurer, Alexi Giannoulias lost $73...",mark-kirk,a TV ad
6,1079,barely-true,"Says Texas has more than 80,000 abortions each...",jonathan-stickland,a tweet
7,89,true,"Pepper ... kicked off a jock tax, imposing a l...",dave-yost,a campaign video
8,213,pants-fire,Four state Assembly Democrats scored a death b...,scott-suder,a news release
9,52,mostly-true,"Already, a prototype driverless car has travel...",jeb-bush,a speech at CPAC
10,413,true,There is nothing in the current state public r...,matt-lundy,a news release
11,170,barely-true,We spend in tax loopholes annually $1.1 trilli...,jeanne-shaheen,an interview with the editorial board of 'The ...
12,440,barely-true,Since the beginning of the year weve created a...,john-kasich,a television interview
13,566,true,He was a member of the Iraq Study Group and wa...,john-mccain,Interview on Fox News
14,160,mostly-true,"Says, In Oregon in 2010, 49 percent of all pre...",carolyn-tomei,a House floor speech
15,662,pants-fire,"Says McCain was a ""Hanoi Hilton songbird"" who ...",vietnam-veterans-against-john-mccain,a flyer sent to news organizations in South Ca...
16,31,false,"Under Rosemary Lehmberg, the Travis County D.A...",sarah-palin,a commentary
17,472,pants-fire,Says Larry Taylor gave in-state tuition to ill...,conservative-voters-texas-pac,whylarrywhy.com
18,1019,pants-fire,Politician Reid Ribble wants to phase out Soci...,steve-kagen,a campaign TV ad
19,1086,mostly-true,Fewer black and Latino men participate in the ...,barack-obama,an event at the White House
20,503,half-true,Says Mitch McConnell voted two times against t...,alison-lundergan-grimes,a campaign ad
21,899,barely-true,The war spending bill actually spends more mon...,lynn-westmoreland,a press release on the House GOP's blog.
22,306,false,Giant companies like Toyota will not locate in...,stephen-laffey,a radio interview
23,1152,mostly-true,I cut spending while serving in the state Legi...,marilinda-garcia,a tweet

In [38]:
# Cell 15: run LIAR stability sample one claim at a time
import time
import traceback

stability_outputs = []
stability_records = []

def build_single_claim_group(row):
    claim_text = str(row["statement"]).strip()
    return [
        {
            "claim_group_id": 1,
            "original_sentence": claim_text,
            "text_feature_text": claim_text,
            "atomization_applied": False,
            "factual_claims": [
                {
                    "fact_claim_id": 1,
                    "claim": claim_text,
                }
            ],
        }
    ]

for run_index, row in stability_df.iterrows():
    row_index = int(row["row_index"])
    claim_text = str(row["statement"]).strip()

    print(f"\n[{run_index + 1}/{len(stability_df)}] row_index={row_index} label={row['label']}")
    print(claim_text)

    started_at = time.time()

    try:
        result = analyze_fact_check_claims(build_single_claim_group(row), options)
        output = result.model_dump()
        stability_outputs.append({
            "row_index": row_index,
            "liar_label": row["label"],
            "claim": claim_text,
            "output": output,
        })

        if result.factual_claims:
            claim_result = result.factual_claims[0]
            metadata = claim_result.metadata

            record = {
                "run_index": run_index + 1,
                "row_index": row_index,
                "liar_label": row["label"],
                "mapped_expected_verdict": liar_label_to_verdict.get(row["label"], ""),
                "claim": claim_text,
                "branch_status": result.status,
                "claim_status": claim_result.status,
                "backend_verdict": claim_result.verdict,
                "truth_score": claim_result.truth_score,
                "decision_confidence": claim_result.decision_confidence,
                "evidence_sufficiency": claim_result.evidence_sufficiency,
                "raw_evidence_count": metadata.search_raw_evidence_count,
                "selected_evidence_count": metadata.selected_evidence_count,
                "returned_evidence_count": len(claim_result.evidence),
                "retrieval_query_used": metadata.retrieval_query_used,
                "runtime_seconds": round(time.time() - started_at, 2),
                "error": "",
            }
        else:
            record = {
                "run_index": run_index + 1,
                "row_index": row_index,
                "liar_label": row["label"],
                "mapped_expected_verdict": liar_label_to_verdict.get(row["label"], ""),
                "claim": claim_text,
                "branch_status": result.status,
                "claim_status": "missing_claim_result",
                "backend_verdict": None,
                "truth_score": None,
                "decision_confidence": None,
                "evidence_sufficiency": "",
                "raw_evidence_count": None,
                "selected_evidence_count": None,
                "returned_evidence_count": 0,
                "retrieval_query_used": "",
                "runtime_seconds": round(time.time() - started_at, 2),
                "error": "No factual_claims returned",
            }

    except Exception as error:
        record = {
            "run_index": run_index + 1,
            "row_index": row_index,
            "liar_label": row["label"],
            "mapped_expected_verdict": liar_label_to_verdict.get(row["label"], ""),
            "claim": claim_text,
            "branch_status": "exception",
            "claim_status": "exception",
            "backend_verdict": None,
            "truth_score": None,
            "decision_confidence": None,
            "evidence_sufficiency": "",
            "raw_evidence_count": None,
            "selected_evidence_count": None,
            "returned_evidence_count": 0,
            "retrieval_query_used": "",
            "runtime_seconds": round(time.time() - started_at, 2),
            "error": repr(error),
        }

        print("ERROR:", repr(error))
        print(traceback.format_exc())

    stability_records.append(record)

stability_result_df = pd.DataFrame(stability_records)
display(stability_result_df)

[1/24] row_index=822 label=half-true
There are 60,000 fewer jobs today in this state than we had in 2008.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0

[2/24] row_index=685 label=false
All the talk about socialism during the campaign made young people more interested in it by Election Day.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0

[3/24] row_index=971 label=true
Says Marco Rubio knows full well I voted for his amendment to increase military spending to $697 billion.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 5 | Deduplicated: 0

[4/24] row_index=519 label=false
Says in Texas its legal to shoot someone whos committing a public nuisance under the cover of dark.
[Search] Retrieved 5 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0

[5/24] row_index=115 label=half-true
More (student-athletes) graduate than the students who arent student-athletes.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0

[6/24] row_index=574 label=half-true
As state treasurer, Alexi Giannoulias lost $73 million in our kids college savings.
[Search] Retrieved 8 results | Filtered shell: 2 | Deduplicated: 0

[7/24] row_index=1079 label=barely-true
Says Texas has more than 80,000 abortions each year.
[Search] Retrieved 8 results | Filtered shell: 1 | Deduplicated: 1

[8/24] row_index=89 label=true
Pepper ... kicked off a jock tax, imposing a levy on the sports and entertainment industry.
[Search] Retrieved 8 results | Filtered shell: 1 | Deduplicated: 0

[9/24] row_index=213 label=pants-fire
Four state Assembly Democrats scored a death blow to northeast Wisconsins economy by killing hundreds of jobs at a potential Bass Pro Shops near Green Bay.
[Search] Retrieved 3 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 3 results | Filtered shell: 0 | Deduplicated: 0
[NLI Filter] Warning: Evidence was somewhat related, but still not close enough to the claim.
[Search] Retrieved 2 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 2 results | Filtered shell: 0 | Deduplicated: 0
[NLI Filter] Warning: Evidence was somewhat related, but still not close enough to the claim.

[10/24] row_index=52 label=mostly-true
Already, a prototype driverless car has traveled more than 300,000 miles in the crowded maze of California streets without a single accident.
[Search] Retrieved 7 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 6 results | Filtered shell: 0 | Deduplicated: 0
[NLI Filter] Warning: Evidence was somewhat related, but still not close enough to the claim.

[11/24] row_index=413 label=true
There is nothing in the current state public records law that prohibits sensitive or confidential business information from being just that, confidential.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0

[12/24] row_index=170 label=barely-true
We spend in tax loopholes annually $1.1 trillion. Thats more than we spend on our defense budget in a year, on Medicare or Medicaid in a year.
[Search] Retrieved 8 results | Filtered shell: 1 | Deduplicated: 0

[13/24] row_index=440 label=barely-true
Since the beginning of the year weve created a net increase of 45,000 jobs.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0

[14/24] row_index=566 label=true
He was a member of the Iraq Study Group and was either fired or quit from a very important commission that was trying to figure out the way forward in Iraq.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Gemini Agent] Temporary API issue on attempt 1. Retrying in 1s...

[15/24] row_index=160 label=mostly-true
Says, In Oregon in 2010, 49 percent of all pregnancies were unintended.
[Search] Retrieved 8 results | Filtered shell: 1 | Deduplicated: 0

[16/24] row_index=662 label=pants-fire
Says McCain was a "Hanoi Hilton songbird" who collaborated with the enemy.
[Search] Retrieved 8 results | Filtered shell: 1 | Deduplicated: 0

[17/24] row_index=31 label=false
Under Rosemary Lehmberg, the Travis County D.A.s office convened the grand jury that indicted Rick Perry.

[18/24] row_index=472 label=pants-fire
Says Larry Taylor gave in-state tuition to illegal immigrants.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0

[19/24] row_index=1019 label=pants-fire
Politician Reid Ribble wants to phase out Social Security, forcing Wisconsin seniors to fend for themselves.
[Search] Retrieved 8 results | Filtered shell: 5 | Deduplicated: 0

[20/24] row_index=1086 label=mostly-true
Fewer black and Latino men participate in the labor force, compared to young white men.
[Search] Retrieved 8 results | Filtered shell: 3 | Deduplicated: 0

[21/24] row_index=503 label=half-true
Says Mitch McConnell voted two times against the Violence Against Women Act.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0

[22/24] row_index=899 label=barely-true
The war spending bill actually spends more money on the International Monetary Fund than on the war.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0

[23/24] row_index=306 label=false
Giant companies like Toyota will not locate in a state that has not passed a right-to-work law
[Search] Retrieved 8 results | Filtered shell: 1 | Deduplicated: 0

[24/24] row_index=1152 label=mostly-true
I cut spending while serving in the state Legislature
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0

,run_index,row_index,liar_label,mapped_expected_verdict,claim,branch_status,claim_status,backend_verdict,truth_score,decision_confidence,evidence_sufficiency,raw_evidence_count,selected_evidence_count,returned_evidence_count,retrieval_query_used,runtime_seconds,error
0,1,822,half-true,Neutral,"There are 60,000 fewer jobs today in this stat...",success,success,True,0.900000,low,sufficient,8,3,3,"There are 60,000 fewer jobs today in this stat...",5.99,
1,2,685,false,False,All the talk about socialism during the campai...,insufficient_evidence,insufficient_evidence,None,NaN,low,insufficient,8,1,1,All the talk about socialism during the campai...,6.92,
2,3,971,true,True,Says Marco Rubio knows full well I voted for h...,success,success,True,0.900000,low,insufficient,3,3,3,Says Marco Rubio knows full well I voted for h...,10.87,
3,4,519,false,False,Says in Texas its legal to shoot someone whos ...,success,success,Mostly False,0.366667,medium,sufficient,8,3,3,Says in Texas its legal to shoot someone whos ...,9.54,
4,5,115,half-true,Neutral,More (student-athletes) graduate than the stud...,success,success,Neutral,0.500000,medium,sufficient,8,3,3,More student-athletes graduate than students w...,9.03,
5,6,574,half-true,Neutral,"As state treasurer, Alexi Giannoulias lost $73...",success,success,Neutral,0.500000,low,limited,6,1,1,"As state treasurer, Alexi Giannoulias lost $73...",4.49,
6,7,1079,barely-true,Mostly False,"Says Texas has more than 80,000 abortions each...",success,success,True,0.900000,low,limited,6,3,3,"Texas has more than 80,000 abortions each year.",8.41,
7,8,89,true,True,"Pepper ... kicked off a jock tax, imposing a l...",success,success,True,0.900000,high,sufficient,7,3,3,"Pepper kicked off a jock tax, imposing a levy ...",6.59,
8,9,213,pants-fire,False,Four state Assembly Democrats scored a death b...,no_evidence,no_evidence,None,NaN,low,,3,0,0,Four state Assembly Democrats scored a death b...,13.26,
9,10,52,mostly-true,Mostly True,"Already, a prototype driverless car has travel...",no_evidence,no_evidence,None,NaN,low,,6,0,0,"Already, a prototype driverless car has travel...",10.51,
10,11,413,true,True,There is nothing in the current state public r...,insufficient_evidence,insufficient_evidence,None,NaN,low,insufficient,8,3,3,There is nothing in the current state public r...,7.92,
11,12,170,barely-true,Mostly False,We spend in tax loopholes annually $1.1 trilli...,insufficient_evidence,insufficient_evidence,None,NaN,low,insufficient,7,3,3,We spend in tax loopholes annually $1.1 trilli...,21.10,
12,13,440,barely-true,Mostly False,Since the beginning of the year weve created a...,success,success,True,0.900000,low,sufficient,8,3,3,"Since the beginning of the year, we have creat...",8.82,
13,14,566,true,True,He was a member of the Iraq Study Group and wa...,insufficient_evidence,insufficient_evidence,None,NaN,low,insufficient,8,2,2,He was a member of the Iraq Study Group and wa...,11.30,
14,15,160,mostly-true,Mostly True,"Says, In Oregon in 2010, 49 percent of all pre...",success,success,True,0.900000,medium,sufficient,7,3,3,"In Oregon in 2010, 49 percent of all pregnanci...",6.27,
15,16,662,pants-fire,False,"Says McCain was a ""Hanoi Hilton songbird"" who ...",success,success,True,0.900000,medium,sufficient,7,3,3,"McCain was a ""Hanoi Hilton songbird"" who colla...",7.85,
16,17,31,false,False,"Under Rosemary Lehmberg, the Travis County D.A...",no_evidence,no_evidence,None,NaN,low,,0,0,0,"Under Rosemary Lehmberg, the Travis County D.A...",4.80,
17,18,472,pants-fire,False,Says Larry Taylor gave in-state tuition to ill...,success,success,True,0.900000,high,sufficient,8,3,3,Larry Taylor gave in-state tuition to illegal ...,6.55,
18,19,1019,pants-fire,False,Politician Reid Ribble wants to phase out Soci...,success,success,False,0.100000,medium,sufficient,3,3,3,Politician Reid Ribble wants to phase out Soci...,10.81,
19,20,1086,mostly-true,Mostly True,Fewer black and Latino men participate in the ...,success,success,True,0.900000,low,sufficient,5,3,3,Fewer black and Latino men participate in the ...,5.88,
20,21,503,half-true,Neutral,Says Mitch McConnell voted two times against t...,success,success,True,0.900000,high,sufficient,8,3,3,Mitch McConnell voted two times against the Vi...,7.01,
21,22,899,barely-true,Mostly False,The war spending bill actually spends more mon...,insufficient_evidence,insufficient_evidence,None,NaN,low,insufficient,8,2,2,The war spending bill actually spends more mon...,7.66,
22,23,306,false,False,Giant companies like Toyota will not locate in...,insufficient_evidence,insufficient_evidence,None,NaN,low,insufficient,7,3,3,Giant companies like Toyota will not locate in...,5.81,
23,24,1152,mostly-true,Mostly True,I cut spending while serving in the state Legi...,insufficient_evidence,insufficient_evidence,None,NaN,low,insufficient,8,2,2,I cut spending while serving in the state Legi...,7.04,

In [39]:
# Cell 16: check stability rules instead of accuracy
def has_value(value):
    return value is not None and value != ""

audit_df = stability_result_df.copy()

audit_df["empty_evidence_but_judged"] = (
    (audit_df["selected_evidence_count"].fillna(0) == 0)
    & (~audit_df["claim_status"].isin(["no_evidence", "invalid_claim", "system_error", "exception"]))
)

audit_df["success_schema_incomplete"] = (
    (audit_df["claim_status"] == "success")
    & (
        audit_df["truth_score"].isna()
        | audit_df["backend_verdict"].isna()
        | (audit_df["backend_verdict"] == "")
    )
)

audit_df["no_evidence_with_selected_evidence"] = (
    (audit_df["claim_status"] == "no_evidence")
    & (audit_df["selected_evidence_count"].fillna(0) > 0)
)

audit_df["insufficient_without_evidence"] = (
    (audit_df["claim_status"] == "insufficient_evidence")
    & (audit_df["selected_evidence_count"].fillna(0) == 0)
)

audit_df["system_or_runtime_error"] = (
    audit_df["claim_status"].isin(["system_error", "exception", "missing_claim_result"])
)

audit_df["stability_issue"] = (
    audit_df["empty_evidence_but_judged"]
    | audit_df["success_schema_incomplete"]
    | audit_df["no_evidence_with_selected_evidence"]
    | audit_df["insufficient_without_evidence"]
    | audit_df["system_or_runtime_error"]
)

issue_columns = [
    "row_index",
    "liar_label",
    "claim_status",
    "backend_verdict",
    "truth_score",
    "evidence_sufficiency",
    "raw_evidence_count",
    "selected_evidence_count",
    "empty_evidence_but_judged",
    "success_schema_incomplete",
    "no_evidence_with_selected_evidence",
    "insufficient_without_evidence",
    "system_or_runtime_error",
    "claim",
    "error",
]

print("Total rows:", len(audit_df))
print("Rows with stability issue:", int(audit_df["stability_issue"].sum()))
display(audit_df[audit_df["stability_issue"]][issue_columns])

Total rows: 24
Rows with stability issue: 0

Empty DataFrame
Columns: [row_index, liar_label, claim_status, backend_verdict, truth_score, evidence_sufficiency, raw_evidence_count, selected_evidence_count, empty_evidence_but_judged, success_schema_incomplete, no_evidence_with_selected_evidence, insufficient_without_evidence, system_or_runtime_error, claim, error]
Index: []

In [40]:
# Cell 17: summarize LIAR stability outcomes
status_summary = (
    audit_df
    .groupby(["liar_label", "claim_status"], dropna=False)
    .size()
    .reset_index(name="count")
    .sort_values(["liar_label", "claim_status"])
)

evidence_summary = audit_df[[
    "raw_evidence_count",
    "selected_evidence_count",
    "returned_evidence_count",
    "runtime_seconds",
]].describe()

verdict_summary = (
    audit_df
    .groupby(["liar_label", "backend_verdict"], dropna=False)
    .size()
    .reset_index(name="count")
    .sort_values(["liar_label", "backend_verdict"])
)

print("Status summary:")
display(status_summary)

print("Evidence/runtime summary:")
display(evidence_summary)

print("Verdict distribution, for diagnosis only:")
display(verdict_summary)

Status summary:

     liar_label           claim_status  count
0   barely-true  insufficient_evidence      2
1   barely-true                success      2
2         false  insufficient_evidence      2
3         false            no_evidence      1
4         false                success      1
5     half-true                success      4
6   mostly-true  insufficient_evidence      1
7   mostly-true            no_evidence      1
8   mostly-true                success      2
9    pants-fire            no_evidence      1
10   pants-fire                success      3
11         true  insufficient_evidence      2
12         true                success      2

Evidence/runtime summary:

,raw_evidence_count,selected_evidence_count,returned_evidence_count,runtime_seconds
count,24.000000,24.000000,24.000000,24.000000
mean,6.458333,2.333333,2.333333,8.517917
std,2.166527,1.090140,1.090140,3.468008
min,0.000000,0.000000,0.000000,4.490000
25%,6.000000,2.000000,2.000000,6.480000
50%,7.000000,3.000000,3.000000,7.755000
75%,8.000000,3.000000,3.000000,9.782500
max,8.000000,3.000000,3.000000,21.100000

Verdict distribution, for diagnosis only:

     liar_label backend_verdict  count
0   barely-true            True      2
1   barely-true             NaN      2
2         false    Mostly False      1
3         false             NaN      3
4     half-true         Neutral      2
5     half-true            True      2
6   mostly-true            True      2
7   mostly-true             NaN      2
8    pants-fire           False      1
9    pants-fire            True      2
10   pants-fire             NaN      1
11         true            True      2
12         true             NaN      2

In [41]:
# Cell 19: calculate strict and relaxed LIAR matching metrics
STRICT_VERDICT_CLASSES = ["True", "Mostly True", "Neutral", "Mostly False", "False"]

relaxed_accepted_verdicts = {
    "true": {"True", "Mostly True"},
    "mostly-true": {"True", "Mostly True", "Neutral"},
    "half-true": {"Mostly True", "Neutral", "Mostly False"},
    "barely-true": {"Neutral", "Mostly False", "False"},
    "false": {"Mostly False", "False"},
    "pants-fire": {"Mostly False", "False"},
}

metrics_df = audit_df.copy()

metrics_df["backend_verdict_normalized"] = metrics_df["backend_verdict"].fillna("No Verdict")
metrics_df.loc[metrics_df["backend_verdict_normalized"] == "", "backend_verdict_normalized"] = "No Verdict"

metrics_df["strict_correct"] = (
    metrics_df["backend_verdict_normalized"] == metrics_df["mapped_expected_verdict"]
)

metrics_df["relaxed_correct"] = metrics_df.apply(
    lambda row: row["backend_verdict_normalized"] in relaxed_accepted_verdicts.get(row["liar_label"], set()),
    axis=1,
)

judged_metrics_df = metrics_df[metrics_df["backend_verdict_normalized"] != "No Verdict"].copy()

def calculate_macro_f1(df, gold_col, pred_col, classes):
    rows = []
    f1_values = []

    for class_name in classes:
        true_positive = ((df[gold_col] == class_name) & (df[pred_col] == class_name)).sum()
        false_positive = ((df[gold_col] != class_name) & (df[pred_col] == class_name)).sum()
        false_negative = ((df[gold_col] == class_name) & (df[pred_col] != class_name)).sum()

        precision = true_positive / (true_positive + false_positive) if (true_positive + false_positive) else 0.0
        recall = true_positive / (true_positive + false_negative) if (true_positive + false_negative) else 0.0
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0

        f1_values.append(f1)
        rows.append({
            "class": class_name,
            "tp": int(true_positive),
            "fp": int(false_positive),
            "fn": int(false_negative),
            "precision": round(precision, 3),
            "recall": round(recall, 3),
            "f1": round(f1, 3),
        })

    return sum(f1_values) / len(f1_values), pd.DataFrame(rows)

strict_macro_f1_all, strict_class_df_all = calculate_macro_f1(
    metrics_df,
    "mapped_expected_verdict",
    "backend_verdict_normalized",
    STRICT_VERDICT_CLASSES,
)

strict_macro_f1_judged, strict_class_df_judged = calculate_macro_f1(
    judged_metrics_df,
    "mapped_expected_verdict",
    "backend_verdict_normalized",
    STRICT_VERDICT_CLASSES,
)

summary_metrics = {
    "total_claims": len(metrics_df),
    "judged_claims": len(judged_metrics_df),
    "no_verdict_claims": len(metrics_df) - len(judged_metrics_df),
    "verdict_coverage": len(judged_metrics_df) / len(metrics_df) if len(metrics_df) else 0.0,
    "strict_accuracy_all": metrics_df["strict_correct"].mean(),
    "strict_accuracy_judged_only": judged_metrics_df["strict_correct"].mean() if len(judged_metrics_df) else 0.0,
    "relaxed_accuracy_all": metrics_df["relaxed_correct"].mean(),
    "relaxed_accuracy_judged_only": judged_metrics_df["relaxed_correct"].mean() if len(judged_metrics_df) else 0.0,
    "strict_macro_f1_all": strict_macro_f1_all,
    "strict_macro_f1_judged_only": strict_macro_f1_judged,
}

summary_metrics_df = pd.DataFrame([
    {"metric": key, "value": round(value, 4) if isinstance(value, float) else value}
    for key, value in summary_metrics.items()
])

per_label_relaxed_df = (
    metrics_df
    .groupby("liar_label")
    .agg(
        total=("row_index", "count"),
        judged=("backend_verdict_normalized", lambda values: (values != "No Verdict").sum()),
        strict_correct=("strict_correct", "sum"),
        relaxed_correct=("relaxed_correct", "sum"),
        strict_accuracy=("strict_correct", "mean"),
        relaxed_accuracy=("relaxed_correct", "mean"),
    )
    .reset_index()
)

per_label_relaxed_df["strict_accuracy"] = per_label_relaxed_df["strict_accuracy"].round(3)
per_label_relaxed_df["relaxed_accuracy"] = per_label_relaxed_df["relaxed_accuracy"].round(3)

print("Summary metrics:")
display(summary_metrics_df)

print("Strict per-class Macro-F1 details, all claims:")
display(strict_class_df_all)

print("Relaxed per-label match rate:")
display(per_label_relaxed_df)

print("Relaxed accepted verdicts:")
display(pd.DataFrame([
    {
        "liar_label": label,
        "accepted_system_verdicts": ", ".join(sorted(verdicts)),
    }
    for label, verdicts in relaxed_accepted_verdicts.items()
]))

Summary metrics:

                         metric    value
0                  total_claims  24.0000
1                 judged_claims  14.0000
2             no_verdict_claims  10.0000
3              verdict_coverage   0.5833
4           strict_accuracy_all   0.2083
5   strict_accuracy_judged_only   0.3571
6          relaxed_accuracy_all   0.3333
7  relaxed_accuracy_judged_only   0.5714
8           strict_macro_f1_all   0.2349
9   strict_macro_f1_judged_only   0.2800

Strict per-class Macro-F1 details, all claims:

          class  tp  fp  fn  precision  recall     f1
0          True   2   8   2        0.2   0.500  0.286
1   Mostly True   0   0   4        0.0   0.000  0.000
2       Neutral   2   0   2        1.0   0.500  0.667
3  Mostly False   0   1   4        0.0   0.000  0.000
4         False   1   0   7        1.0   0.125  0.222

Relaxed per-label match rate:

,liar_label,total,judged,strict_correct,relaxed_correct,strict_accuracy,relaxed_accuracy
0,barely-true,4,2,0,0,0.00,0.00
1,false,4,1,0,1,0.00,0.25
2,half-true,4,4,2,2,0.50,0.50
3,mostly-true,4,2,0,2,0.00,0.50
4,pants-fire,4,3,1,1,0.25,0.25
5,true,4,2,2,2,0.50,0.50

Relaxed accepted verdicts:

    liar_label            accepted_system_verdicts
0         true                   Mostly True, True
1  mostly-true          Mostly True, Neutral, True
2    half-true  Mostly False, Mostly True, Neutral
3  barely-true        False, Mostly False, Neutral
4        false                 False, Mostly False
5   pants-fire                 False, Mostly False