# Fact-Checking Test Notebook

This notebook tests the current `dual_dimension_misinformation_analyzer/backend/fact_checking` pipeline as a whole.
It keeps the full `EachFactualClaim` output visible, and then builds simple tables on top of it.

## Cell 1: Mount Google Drive
Mount Drive so Colab can access the project and dataset.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Cell 2: Set Project Paths
Define the Colab paths and add the backend folder to `sys.path`.

In [ ]:
import os
import sys
import json
import random
import pandas as pd
from IPython.display import display

project_root = '/content/drive/MyDrive/UoP/COMP3000/dual_dimension_misinformation_analyzer'
frontend_root = os.path.join(project_root, 'frontend')
backend_root = os.path.join(project_root, 'backend')
atomizer_root = os.path.join(backend_root, 'atomizer')
dataset_root = os.path.join(project_root, 'dataset')
fever_dataset_root = os.path.join(dataset_root, 'FEVER')

assert os.path.exists(project_root), f'Missing project_root: {project_root}'
assert os.path.exists(backend_root), f'Missing backend_root: {backend_root}'
assert os.path.exists(dataset_root), f'Missing dataset_root: {dataset_root}'

if backend_root not in sys.path:
    sys.path.append(backend_root)

print('project_root:', project_root)
print('backend_root:', backend_root)
print('dataset_root:', dataset_root)

project_root: /content/drive/MyDrive/UoP/COMP3000/dual_dimension_misinformation_analyzer
backend_root: /content/drive/MyDrive/UoP/COMP3000/dual_dimension_misinformation_analyzer/backend
dataset_root: /content/drive/MyDrive/UoP/COMP3000/dual_dimension_misinformation_analyzer/dataset

## Cell 3: Install Dependencies
Install the Python packages needed for the current backend pipeline in Colab.

In [3]:
!pip install -q pydantic transformers torch sentencepiece google-genai tavily-python pandas

## Cell 4: Set API Keys
Set the required API keys.

If you already stored them in Colab secrets or environment variables, you can skip the assignments and just keep the checks.

In [7]:
import os

# Option 1: set them manually here
os.environ["TAVILY_API_KEY"] = "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"
os.environ["GEMINI_API_KEY"] = "AIzaSyC5CfBmlrTDBPMqoDMe4OUaW_ODSduG_Lk"


print('TAVILY_API_KEY set:', 'TAVILY_API_KEY' in os.environ)
print('GEMINI_API_KEY set:', 'GEMINI_API_KEY' in os.environ)

TAVILY_API_KEY set: True
GEMINI_API_KEY set: True

## Cell 5: Import Current Fact-Checking Entry Point
Import the current backend contract and the current fact-checking service.

In [5]:
from api_contract import AnalysisOptions
from fact_checking.fact_check_service import run_fact_check_for_atomic_claim

[gemini_agent.py] Warning: GEMINI_API_KEY environment variable not found.

## Cell 6: Helpers for Dataset Loading and Fact-Check Execution
Resolve the LIAR path, build a clean sample dataframe, create analysis options, and run one claim through the current pipeline.

In [8]:
def resolve_liar_test_path():
    candidates = [
        os.path.join(dataset_root, 'LIAR', 'test.tsv'),
        os.path.join(project_root, 'data', 'LIAR', 'test.tsv'),
    ]

    for path in candidates:
        if os.path.exists(path):
            return path

    raise FileNotFoundError('Could not find LIAR test.tsv. Checked:' + ''.join(candidates))


def build_sampled_claims_df(sampled_df: pd.DataFrame) -> pd.DataFrame:
    cleaned_df = pd.DataFrame({
        'row_index': sampled_df.index + 1,
        'label': sampled_df.iloc[:, 1].astype(str).str.strip(),
        'claim': sampled_df.iloc[:, 2].astype(str).str.strip(),
    })
    cleaned_df.reset_index(drop=True, inplace=True)
    return cleaned_df


def make_options(**overrides):
    options = {
        'use_query_rewrite': True,
        'relevance_threshold': 0.1,
        'use_oversampling_retry': True,
        'use_selective_stabilization': True,
        'top_k': 3,
        'use_all_eligible_evidence': False,
        'retrieval_results': 8,
    }
    options.update(overrides)
    return AnalysisOptions(**options)


def run_claim(claim_text: str, claim_group_id: int = 1, fact_claim_id: int = 1, **option_overrides):
    options = make_options(**option_overrides)
    return run_fact_check_for_atomic_claim(
        atomic_claim=claim_text,
        claim_group_id=claim_group_id,
        fact_claim_id=fact_claim_id,
        original_sentence=claim_text,
        text_feature_text=claim_text,
        options=options,
    )


def factual_claim_to_dict(factual_claim):
    return factual_claim.model_dump()


def build_claim_summary_row(factual_claim_dict: dict, gold_label: str | None = None, mapped_gold_label: str | None = None):
    metadata = factual_claim_dict.get('metadata', {})
    evidence = factual_claim_dict.get('evidence', [])
    return {
        'claim_group_id': factual_claim_dict.get('claim_group_id'),
        'fact_claim_id': factual_claim_dict.get('fact_claim_id'),
        'claim': factual_claim_dict.get('claim'),
        'gold_label': gold_label,
        'mapped_gold_label': mapped_gold_label,
        'status': factual_claim_dict.get('status'),
        'truth_score': factual_claim_dict.get('truth_score'),
        'verdict': factual_claim_dict.get('verdict'),
        'decision_confidence': factual_claim_dict.get('decision_confidence'),
        'evidence_sufficiency': factual_claim_dict.get('evidence_sufficiency'),
        'selected_evidence_count': len(evidence),
        'fallback_used': metadata.get('fallback_used'),
        'search_raw_evidence_count': metadata.get('search_raw_evidence_count'),
        'retrieval_query_used': metadata.get('retrieval_query_used'),
    }


def build_evidence_rows(factual_claim_dict: dict):
    rows = []
    for index, evidence_item in enumerate(factual_claim_dict.get('evidence', []), start=1):
        rows.append({
            'claim_group_id': factual_claim_dict.get('claim_group_id'),
            'fact_claim_id': factual_claim_dict.get('fact_claim_id'),
            'claim': factual_claim_dict.get('claim'),
            'evidence_index': index,
            'stance': evidence_item.get('stance'),
            'evidence_quality': evidence_item.get('evidence_quality'),
            'url': evidence_item.get('url'),
            'content': evidence_item.get('content'),
            'ai_analysis': evidence_item.get('ai_analysis'),
        })
    return rows


liar_test_path = resolve_liar_test_path()
print('LIAR test path:', liar_test_path)

liar_df = pd.read_csv(liar_test_path, sep='	', header=None)
total_rows = len(liar_df)
print('Total LIAR test rows:', total_rows)

LIAR test path: /content/drive/MyDrive/UoP/COMP3000/dual_dimension_misinformation_analyzer/dataset/LIAR/test.tsv
Total LIAR test rows: 1267

## Cell 7: Choose a Small Smoke-Test Sample
Take a small random sample so we can quickly inspect the current pipeline before a larger batch run.

In [9]:
RANDOM_SEED = 42
SMOKE_SAMPLE_SIZE = 5

random.seed(RANDOM_SEED)
smoke_indices = random.sample(range(total_rows), SMOKE_SAMPLE_SIZE)
smoke_indices.sort()

smoke_sampled_df = build_sampled_claims_df(liar_df.iloc[smoke_indices].copy())
smoke_sampled_claims = smoke_sampled_df.to_dict(orient='records')

print('Smoke sample rows:', smoke_indices)
display(smoke_sampled_df)

Smoke sample rows: [51, 228, 457, 501, 563]

   row_index        label                                              claim
0         52  barely-true  Hillary Clinton said gun confiscation would be...
1        229  mostly-true  When it comes to income taxes, Wisconsin is on...
2        458    half-true  The Congressional Budget Office estimates that...
3        502  mostly-true  In the city of Milwaukee, weve still got a may...
4        564         true  Says he came to the Republican Party sooner in...

## Cell 8: Smoke Test Raw `EachFactualClaim` Output
Run the smoke sample and display the full raw `EachFactualClaim` objects.

This is the most direct view of the current backend output.

In [10]:
smoke_raw_outputs = []

for item in smoke_sampled_claims:
    factual_claim = run_claim(
        item['claim'],
        claim_group_id=int(item['row_index']),
        fact_claim_id=1,
    )
    smoke_raw_outputs.append(factual_claim_to_dict(factual_claim))

for output in smoke_raw_outputs:
    print('=' * 120)
    print(json.dumps(output, indent=2, ensure_ascii=False))

[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[NLI Filter] Loading model: cross-encoder/nli-deberta-v3-base

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/301 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/738M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: cross-encoder/nli-deberta-v3-base
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[NLI Filter] Model loaded.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 2 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 2 results | Filtered shell: 0 | Deduplicated: 0
[NLI Filter] Warning: Evidence discussed the topic, but key claim details conflicted.
[Search] Retrieved 1 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 1 results | Filtered shell: 0 | Deduplicated: 0
[NLI Filter] Warning: Evidence was somewhat related, but still not close enough to the claim.
[Search] Retrieved 8 results | Filtered shell: 1 | Deduplicated: 0
========================================================================================================================
{
  "claim_group_id": 52,
  "fact_claim_id": 1,
  "original_sentence": "Hillary Clinton said gun confiscation would be worth considering.",
  "text_feature_text": "Hillary Clinton said gun confiscation would be worth considering.",
  "claim": "Hillary Clinton said gun confiscation would be worth considering.",
  "status": "degraded",
  "truth_score": null,
  "verdict": null,
  "explanation": "Gemini API key is missing.",
  "decision_confidence": "low",
  "evidence_sufficiency": "sufficient",
  "evidence": [
    {
      "stance": "background",
      "evidence_quality": "strong",
      "url": "https://www.politifact.com/factchecks/2016/oct/17/national-rifle-association/nra-weakly-claims-clinton-said-gun-confiscation-wo/",
      "content": "# NRA weakly claims that Clinton said gun confiscation is 'worth considering'. The NRA and other pro-gun groups instantly seized on Clinton’s comment, saying the buyback program Clinton lauded is tantamount to a confiscation program, because it backed many gun owners into a corner: They either could sell their firearms to the government or risk prosecution for keeping them. The NRA says that when Clinton was asked about gun confiscation, she said \"I think it would be worth doing it on a national level, if that can be arranged.\". Clinton made that statement last year at a New Hampshire campaign stop, when she was asked a vague question about an Australian program that gave gun owners one year to sell certain firearms to the government before those weapons became illegal. CNN, \"NRA slams Hillary Clinton, claims she supports confiscating guns,\" Oct. 16, 2015. ### NRA weakly claims that Clinton said gun confiscation is 'worth considering'.",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "strong",
      "url": "https://www.ydr.com/story/opinion/columnists/2016/10/24/hillary-bad-news-gun-owners-column/92688738/",
      "content": "Hillary is bad news for gun owners (column). # Hillary is bad news for gun owners (column). I encourage every gun owner to do the same. Secretary Clinton said during a Democratic primary debate that Australia's gun confiscation program was \"worth looking at.\" An example gun outlawed in Australia? That is the kind of gun control Hillary Clinton thinks is \"worth looking at.\". In addition, Secretary Clinton has repeatedly refused to accept the Supreme Court's decision in the Heller gun rights case. The law overturned in Heller required guns kept in a home to be disassembled or fitted with trigger locks. Even an adult living alone had to have the gun disassembled or fitted with a trigger lock. If you are one of America's 100 million gun owners or if you are one of Pennsylvania's 750,000 hunters, you must vote against Hillary Clinton on Nov. 8 to protect your Second Amendment rights. Facebook) Twitter https://www.ydr.com/story/opinion/columnists/2016/10/24/hillary-bad-news-gun-owners-column/92688738/ via @ydrcom) Email.",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "https://shared.nrapvf.org/sharedmedia/1509247/nra-hillary-clinton-postcard.pdf",
      "content": "Presorted First Class Mail US Postage Paid Permit No. 3905 Suburban MD WHAT DID HILLARY CLINTON SAY WHEN SHE WAS ASKED ABOUT GUN CONFISCATION IN AMERICA? HER OWN WORDS CONFIRM HER PLANS TO BAN YOUR GUNS When it comes to banning guns and eliminating your rights, Hillary Clinton has big plans. And I’m going to make that case every chance I get.” (Washington Free Beacon, 10/1/15) “We’re going to start the very first day and tackle the gun lobby.” (MSNBC, 4/25/2016) “When it comes to guns, we have just too many guns.” (USA Today, 4/20/2016) Hillary Clinton wants to overturn the Heller decision, which held that you have right to keep a gun in your home for self-defense. If elected president, she will immediately nominate an anti-gun justice for the Supreme Court and overturn your right to own a gun. Hillary Clinton’s first priority in office would be to attack your rights.",
      "ai_analysis": "No specific analysis was generated for this source."
    }
  ],
  "metadata": {
    "retrieval_query_used": "Hillary Clinton said gun confiscation would be worth considering.",
    "fallback_used": false,
    "search_raw_evidence_count": 8,
    "selected_evidence_count": 3
  }
}
========================================================================================================================
{
  "claim_group_id": 229,
  "fact_claim_id": 1,
  "original_sentence": "When it comes to income taxes, Wisconsin is one of the best places in the country to be poor but top 4 or 5 worst for middle-income earners.",
  "text_feature_text": "When it comes to income taxes, Wisconsin is one of the best places in the country to be poor but top 4 or 5 worst for middle-income earners.",
  "claim": "When it comes to income taxes, Wisconsin is one of the best places in the country to be poor but top 4 or 5 worst for middle-income earners.",
  "status": "degraded",
  "truth_score": null,
  "verdict": null,
  "explanation": "Gemini API key is missing.",
  "decision_confidence": "low",
  "evidence_sufficiency": "insufficient",
  "evidence": [
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "http://www.logandaily.com/comment/columns/can-child-care-reforms-help-families-overcome-benefit-cliffs/article_542f289d-455f-4677-a740-1b72cbec4a81.html",
      "content": "In general, the bill would expand eligibility for child care for more low- and middle-income families that are above the federal poverty line.",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "weak",
      "url": "https://www.bankrate.com/retirement/best-and-worst-states-for-retirement/",
      "content": "According to Bankrate’s 2025 Best and Worst States to Retire Study, the answer is — New Hampshire, where the state’s motto is “Live Free or Die.” The Granite State unseats last year’s top scorer, Delaware, which fell to 11th overall. Bankrate’s Best and Worst States to Retire Study revealed that New Hampshire is the best state for retirees in 2025, followed by Maine (2), Wyoming (3), Vermont (4) and Idaho (5). Let’s run through some of the key reasons that states topped the rankings of Bankrate’s latest Best and Worst States to Retire Study. Other major and minor categories matched the state’s low overall ranking: affordability (45th), people of a similar age (44th), arts (46th), health care (41st) and safety (37th). To rank the best and worst states for retirees, Bankrate compared all 50 states across 15 data points spanning eight categories.",
      "ai_analysis": "No specific analysis was generated for this source."
    }
  ],
  "metadata": {
    "retrieval_query_used": "When it comes to income taxes, Wisconsin is one of the best places in the country to be poor but top 4 or 5 worst for middle-income earners.",
    "fallback_used": false,
    "search_raw_evidence_count": 8,
    "selected_evidence_count": 2
  }
}
========================================================================================================================
{
  "claim_group_id": 458,
  "fact_claim_id": 1,
  "original_sentence": "The Congressional Budget Office estimates that for every $1 we spend on unemployment benefits, $1.90 is put into our economy.",
  "text_feature_text": "The Congressional Budget Office estimates that for every $1 we spend on unemployment benefits, $1.90 is put into our economy.",
  "claim": "The Congressional Budget Office estimates that for every $1 we spend on unemployment benefits, $1.90 is put into our economy.",
  "status": "insufficient_evidence",
  "truth_score": null,
  "verdict": null,
  "explanation": "Retrieved evidence discussed the topic, but key claim details pointed in a different direction.",
  "decision_confidence": "low",
  "evidence_sufficiency": "insufficient",
  "evidence": [],
  "metadata": {
    "retrieval_query_used": "The Congressional Budget Office estimates that for every $1 we spend on unemployment benefits, $1.90 is put into our economy.",
    "fallback_used": false,
    "search_raw_evidence_count": 2,
    "selected_evidence_count": 0
  }
}
========================================================================================================================
{
  "claim_group_id": 502,
  "fact_claim_id": 1,
  "original_sentence": "In the city of Milwaukee, weve still got a mayor and a police chief who are furloughing police officers at a time when we have violence all across the city.",
  "text_feature_text": "In the city of Milwaukee, weve still got a mayor and a police chief who are furloughing police officers at a time when we have violence all across the city.",
  "claim": "In the city of Milwaukee, weve still got a mayor and a police chief who are furloughing police officers at a time when we have violence all across the city.",
  "status": "insufficient_evidence",
  "truth_score": null,
  "verdict": null,
  "explanation": "Retrieved evidence was found, but it did not line up closely enough with the specific claim to support a verdict.",
  "decision_confidence": "low",
  "evidence_sufficiency": "insufficient",
  "evidence": [],
  "metadata": {
    "retrieval_query_used": "In the city of Milwaukee, weve still got a mayor and a police chief who are furloughing police officers at a time when we have violence all across the city.",
    "fallback_used": false,
    "search_raw_evidence_count": 1,
    "selected_evidence_count": 0
  }
}
========================================================================================================================
{
  "claim_group_id": 564,
  "fact_claim_id": 1,
  "original_sentence": "Says he came to the Republican Party sooner in age than Ronald Reagan.",
  "text_feature_text": "Says he came to the Republican Party sooner in age than Ronald Reagan.",
  "claim": "Says he came to the Republican Party sooner in age than Ronald Reagan.",
  "status": "degraded",
  "truth_score": null,
  "verdict": null,
  "explanation": "Gemini API key is missing.",
  "decision_confidence": "low",
  "evidence_sufficiency": "insufficient",
  "evidence": [
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "https://www.politifact.com/factchecks/2011/sep/06/rick-perry/rick-perry-says-he-switched-gop-younger-age-reagan/",
      "content": "On his Aug. 30 radio program, conservative commentator Sean Hannity noted that Texas Gov. Rick Perry’s years-ago switch from the Democratic to the Republican party Puts him in the same company as the nation’s 40th president. In March 2010, PolitiFact Florida rated True the claim that \"Reagan was a Democrat before he was a Republican.\". Historian Edward Yager, author of the 2006 biography *Ronald Reagan’s Journey: Democrat to Republican*, told PolitiFact Florida that Reagan, who was born Feb. 6, 1911, \"was registered Democrat from the time that he voted for (Democrat Franklin Roosevelt) in 1932, when he was 21.\". We’ve looked at Perry’s political past in previous fact-checks, reporting that Perry won his first election as a Democrat, taking a West Texas House district seat in 1984, when Democrats controlled the Legislature and the state had had just one Republican governor since Reconstruction. PolitiFact Florida, \"Crist says Reagan was a Democrat before converting to GOP,\" March 30, 2010. stated on April 13, 2012 in a Republican U.S. Senate debate:.",
      "ai_analysis": "No specific analysis was generated for this source."
    }
  ],
  "metadata": {
    "retrieval_query_used": "Says he came to the Republican Party sooner in age than Ronald Reagan.",
    "fallback_used": false,
    "search_raw_evidence_count": 7,
    "selected_evidence_count": 1
  }
}

## Cell 9: Smoke Test Summary Table
Build a small table from the same raw outputs so the smoke test is easier to scan.

In [11]:
smoke_summary_rows = [build_claim_summary_row(item) for item in smoke_raw_outputs]
smoke_summary_df = pd.DataFrame(smoke_summary_rows)
display(smoke_summary_df)

,claim_group_id,fact_claim_id,claim,gold_label,mapped_gold_label,status,truth_score,verdict,decision_confidence,evidence_sufficiency,selected_evidence_count,fallback_used,search_raw_evidence_count,retrieval_query_used
0,52,1,Hillary Clinton said gun confiscation would be...,None,None,degraded,None,None,low,sufficient,3,False,8,Hillary Clinton said gun confiscation would be...
1,229,1,"When it comes to income taxes, Wisconsin is on...",None,None,degraded,None,None,low,insufficient,2,False,8,"When it comes to income taxes, Wisconsin is on..."
2,458,1,The Congressional Budget Office estimates that...,None,None,insufficient_evidence,None,None,low,insufficient,0,False,2,The Congressional Budget Office estimates that...
3,502,1,"In the city of Milwaukee, weve still got a may...",None,None,insufficient_evidence,None,None,low,insufficient,0,False,1,"In the city of Milwaukee, weve still got a may..."
4,564,1,Says he came to the Republican Party sooner in...,None,None,degraded,None,None,low,insufficient,1,False,7,Says he came to the Republican Party sooner in...

## Cell 10: Batch Sample for LIAR Evaluation
Prepare a slightly larger LIAR sample for batch testing and simple label mapping.

In [12]:
RANDOM_SEED = 42
BATCH_SAMPLE_SIZE = 10

random.seed(RANDOM_SEED)
batch_indices = random.sample(range(total_rows), BATCH_SAMPLE_SIZE)
batch_indices.sort()

batch_sampled_df = build_sampled_claims_df(liar_df.iloc[batch_indices].copy())
batch_sampled_claims = batch_sampled_df.to_dict(orient='records')

liar_to_verdict = {
    'pants-fire': 'False',
    'false': 'False',
    'barely-true': 'Mostly False',
    'half-true': 'Neutral',
    'mostly-true': 'Mostly True',
    'true': 'True',
}

verdict_order = ['False', 'Mostly False', 'Neutral', 'Mostly True', 'True']
verdict_to_index = {label: index for index, label in enumerate(verdict_order)}

display(batch_sampled_df)

   row_index        label                                              claim
0         52  barely-true  Hillary Clinton said gun confiscation would be...
1        179    half-true  President Obama and Nancy Pelosi said Obamacar...
2        210        false  Says an Obama administration policy prohibits ...
3        229  mostly-true  When it comes to income taxes, Wisconsin is on...
4        286        false  Says House Democrats voted to use your tax dol...
5        458    half-true  The Congressional Budget Office estimates that...
6        502  mostly-true  In the city of Milwaukee, weve still got a may...
7        564         true  Says he came to the Republican Party sooner in...
8       1117        false  Scott Walker had a 2.3 GPA when he was asked t...
9       1210    half-true  Says he brought 1,200 jobs to Texas by moving ...

## Cell 11: Batch Test Raw `EachFactualClaim` Outputs
Run the batch sample and keep the full raw outputs.

This is still the main source of truth; later tables are only summaries of these objects.

In [13]:
batch_raw_outputs = []

for item in batch_sampled_claims:
    factual_claim = run_claim(
        item['claim'],
        claim_group_id=int(item['row_index']),
        fact_claim_id=1,
    )
    factual_claim_dict = factual_claim_to_dict(factual_claim)

    gold_label = item['label'].strip().lower()
    mapped_gold_label = liar_to_verdict.get(gold_label, 'Unknown')
    predicted_verdict = factual_claim_dict.get('verdict') or 'Unknown'

    strict_correct = mapped_gold_label == predicted_verdict

    if mapped_gold_label in verdict_to_index and predicted_verdict in verdict_to_index:
        relaxed_correct = abs(verdict_to_index[mapped_gold_label] - verdict_to_index[predicted_verdict]) <= 1
    else:
        relaxed_correct = False

    batch_raw_outputs.append({
        'gold_label': gold_label,
        'mapped_gold_label': mapped_gold_label,
        'strict_correct': strict_correct,
        'relaxed_correct': relaxed_correct,
        'factual_claim': factual_claim_dict,
    })

for item in batch_raw_outputs:
    print('=' * 120)
    print('gold_label:', item['gold_label'])
    print('mapped_gold_label:', item['mapped_gold_label'])
    print('strict_correct:', item['strict_correct'])
    print('relaxed_correct:', item['relaxed_correct'])
    print(json.dumps(item['factual_claim'], indent=2, ensure_ascii=False))

[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 3 results | Filtered shell: 0 | Deduplicated: 0
[NLI Filter] Warning: Evidence was somewhat related, but still not close enough to the claim.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 2 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 2 results | Filtered shell: 0 | Deduplicated: 0
[NLI Filter] Warning: Evidence discussed the topic, but key claim details conflicted.
[Search] Retrieved 1 results | Filtered shell: 0 | Deduplicated: 0
[Search] Retrieved 1 results | Filtered shell: 0 | Deduplicated: 0
[NLI Filter] Warning: Evidence was somewhat related, but still not close enough to the claim.
[Search] Retrieved 8 results | Filtered shell: 1 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 2 | Deduplicated: 0
[Search] Retrieved 8 results | Filtered shell: 1 | Deduplicated: 0
========================================================================================================================
gold_label: barely-true
mapped_gold_label: Mostly False
strict_correct: False
relaxed_correct: False
{
  "claim_group_id": 52,
  "fact_claim_id": 1,
  "original_sentence": "Hillary Clinton said gun confiscation would be worth considering.",
  "text_feature_text": "Hillary Clinton said gun confiscation would be worth considering.",
  "claim": "Hillary Clinton said gun confiscation would be worth considering.",
  "status": "degraded",
  "truth_score": null,
  "verdict": null,
  "explanation": "Gemini API key is missing.",
  "decision_confidence": "low",
  "evidence_sufficiency": "sufficient",
  "evidence": [
    {
      "stance": "background",
      "evidence_quality": "strong",
      "url": "https://www.politifact.com/factchecks/2016/oct/17/national-rifle-association/nra-weakly-claims-clinton-said-gun-confiscation-wo/",
      "content": "# NRA weakly claims that Clinton said gun confiscation is 'worth considering'. The NRA and other pro-gun groups instantly seized on Clinton’s comment, saying the buyback program Clinton lauded is tantamount to a confiscation program, because it backed many gun owners into a corner: They either could sell their firearms to the government or risk prosecution for keeping them. The NRA says that when Clinton was asked about gun confiscation, she said \"I think it would be worth doing it on a national level, if that can be arranged.\". Clinton made that statement last year at a New Hampshire campaign stop, when she was asked a vague question about an Australian program that gave gun owners one year to sell certain firearms to the government before those weapons became illegal. CNN, \"NRA slams Hillary Clinton, claims she supports confiscating guns,\" Oct. 16, 2015. ### NRA weakly claims that Clinton said gun confiscation is 'worth considering'.",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "strong",
      "url": "https://www.ydr.com/story/opinion/columnists/2016/10/24/hillary-bad-news-gun-owners-column/92688738/",
      "content": "Hillary is bad news for gun owners (column). # Hillary is bad news for gun owners (column). I encourage every gun owner to do the same. Secretary Clinton said during a Democratic primary debate that Australia's gun confiscation program was \"worth looking at.\" An example gun outlawed in Australia? That is the kind of gun control Hillary Clinton thinks is \"worth looking at.\". In addition, Secretary Clinton has repeatedly refused to accept the Supreme Court's decision in the Heller gun rights case. The law overturned in Heller required guns kept in a home to be disassembled or fitted with trigger locks. Even an adult living alone had to have the gun disassembled or fitted with a trigger lock. If you are one of America's 100 million gun owners or if you are one of Pennsylvania's 750,000 hunters, you must vote against Hillary Clinton on Nov. 8 to protect your Second Amendment rights. Facebook) Twitter https://www.ydr.com/story/opinion/columnists/2016/10/24/hillary-bad-news-gun-owners-column/92688738/ via @ydrcom) Email.",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "https://shared.nrapvf.org/sharedmedia/1509247/nra-hillary-clinton-postcard.pdf",
      "content": "Presorted First Class Mail US Postage Paid Permit No. 3905 Suburban MD WHAT DID HILLARY CLINTON SAY WHEN SHE WAS ASKED ABOUT GUN CONFISCATION IN AMERICA? HER OWN WORDS CONFIRM HER PLANS TO BAN YOUR GUNS When it comes to banning guns and eliminating your rights, Hillary Clinton has big plans. And I’m going to make that case every chance I get.” (Washington Free Beacon, 10/1/15) “We’re going to start the very first day and tackle the gun lobby.” (MSNBC, 4/25/2016) “When it comes to guns, we have just too many guns.” (USA Today, 4/20/2016) Hillary Clinton wants to overturn the Heller decision, which held that you have right to keep a gun in your home for self-defense. If elected president, she will immediately nominate an anti-gun justice for the Supreme Court and overturn your right to own a gun. Hillary Clinton’s first priority in office would be to attack your rights.",
      "ai_analysis": "No specific analysis was generated for this source."
    }
  ],
  "metadata": {
    "retrieval_query_used": "Hillary Clinton said gun confiscation would be worth considering.",
    "fallback_used": false,
    "search_raw_evidence_count": 8,
    "selected_evidence_count": 3
  }
}
========================================================================================================================
gold_label: half-true
mapped_gold_label: Neutral
strict_correct: False
relaxed_correct: False
{
  "claim_group_id": 179,
  "fact_claim_id": 1,
  "original_sentence": "President Obama and Nancy Pelosi said Obamacare would save money because they factored in 10 years worth of tax revenue and only six and half years worth of expenses.",
  "text_feature_text": "President Obama and Nancy Pelosi said Obamacare would save money because they factored in 10 years worth of tax revenue and only six and half years worth of expenses.",
  "claim": "President Obama and Nancy Pelosi said Obamacare would save money because they factored in 10 years worth of tax revenue and only six and half years worth of expenses.",
  "status": "insufficient_evidence",
  "truth_score": null,
  "verdict": null,
  "explanation": "Retrieved evidence was found, but it did not line up closely enough with the specific claim to support a verdict.",
  "decision_confidence": "low",
  "evidence_sufficiency": "insufficient",
  "evidence": [],
  "metadata": {
    "retrieval_query_used": "President Obama and Nancy Pelosi said Obamacare would save money because they factored in 10 years worth of tax revenue and only six and half years worth of expenses.",
    "fallback_used": false,
    "search_raw_evidence_count": 3,
    "selected_evidence_count": 0
  }
}
========================================================================================================================
gold_label: false
mapped_gold_label: False
strict_correct: False
relaxed_correct: False
{
  "claim_group_id": 210,
  "fact_claim_id": 1,
  "original_sentence": "Says an Obama administration policy prohibits people who work with at-risk youth from promoting marriage as a way to avoid poverty.",
  "text_feature_text": "Says an Obama administration policy prohibits people who work with at-risk youth from promoting marriage as a way to avoid poverty.",
  "claim": "Says an Obama administration policy prohibits people who work with at-risk youth from promoting marriage as a way to avoid poverty.",
  "status": "degraded",
  "truth_score": null,
  "verdict": null,
  "explanation": "Gemini API key is missing.",
  "decision_confidence": "low",
  "evidence_sufficiency": "limited",
  "evidence": [
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "https://www.madinamerica.com/2017/06/do-psychiatrists-harm-patients-out-of-stupidity/",
      "content": "Dozens of people over the decades have basically asked me the same kind of anguished question: “How can someone like my psychiatrist who is very smart, someone with a medical degree, who has been sitting a few feet away from me for years, keep on totally missing what I need as they persist in treating me like I’m invisible?”. Furthermore, I am told that it is written, “Robert, what do you see when you look in the mirror?” While, a good ‘existential’ therapist, desiring to demonstrate just how and why the post-modern social world is ‘alienating’ of the human sense of self, might ask Robert, “do see your eyes and mistake a word for the reality of and the function of your eyes?” Furthermore, can you admit the ‘habituated’ nature of your behaviour and why, in addressing psychiatrists with well-chosen words, you find yourself (existentially) behaving like a well initiated Jew standing before a famous wall in a famous city, where words are repeated in parrot-like fashion, with a heartfelt hope of personal transformation.",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "https://www.justice-integrity.org/2176-april-25-news",
      "content": "Until now, she said, officials did not have to worry about repercussions from “taking a strong stance on policy issues in ways that are inconsistent with the president’s agenda.” But that was the sort of pressure that Mr. Powell faced as Mr. Trump sought to force rates down. “I was never much in favor of it,” Mr. Trump said from the Oval Office, when asked about concerns that federal employees might be leveraging insider information on the prediction markets. In a letter filed in Manhattan federal court, the U.S. attorney for the Southern District of New York, Jay Clayton, said that the Treasury Department had issued amended licenses that would allow defense lawyers for Mr. Maduro, the former president of Venezuela, and his wife, Cilia Flores, to receive payments from their country’s government. *Vice President JD Vance, right, shares words with President Trump in a February event at the White House Oval Office (New York Times photo).*.",
      "ai_analysis": "No specific analysis was generated for this source."
    }
  ],
  "metadata": {
    "retrieval_query_used": "Says an Obama administration policy prohibits people who work with at-risk youth from promoting marriage as a way to avoid poverty.",
    "fallback_used": false,
    "search_raw_evidence_count": 8,
    "selected_evidence_count": 2
  }
}
========================================================================================================================
gold_label: mostly-true
mapped_gold_label: Mostly True
strict_correct: False
relaxed_correct: False
{
  "claim_group_id": 229,
  "fact_claim_id": 1,
  "original_sentence": "When it comes to income taxes, Wisconsin is one of the best places in the country to be poor but top 4 or 5 worst for middle-income earners.",
  "text_feature_text": "When it comes to income taxes, Wisconsin is one of the best places in the country to be poor but top 4 or 5 worst for middle-income earners.",
  "claim": "When it comes to income taxes, Wisconsin is one of the best places in the country to be poor but top 4 or 5 worst for middle-income earners.",
  "status": "degraded",
  "truth_score": null,
  "verdict": null,
  "explanation": "Gemini API key is missing.",
  "decision_confidence": "low",
  "evidence_sufficiency": "insufficient",
  "evidence": [
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "http://www.logandaily.com/comment/columns/can-child-care-reforms-help-families-overcome-benefit-cliffs/article_542f289d-455f-4677-a740-1b72cbec4a81.html",
      "content": "In general, the bill would expand eligibility for child care for more low- and middle-income families that are above the federal poverty line.",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "weak",
      "url": "https://www.bankrate.com/retirement/best-and-worst-states-for-retirement/",
      "content": "According to Bankrate’s 2025 Best and Worst States to Retire Study, the answer is — New Hampshire, where the state’s motto is “Live Free or Die.” The Granite State unseats last year’s top scorer, Delaware, which fell to 11th overall. Bankrate’s Best and Worst States to Retire Study revealed that New Hampshire is the best state for retirees in 2025, followed by Maine (2), Wyoming (3), Vermont (4) and Idaho (5). Let’s run through some of the key reasons that states topped the rankings of Bankrate’s latest Best and Worst States to Retire Study. Other major and minor categories matched the state’s low overall ranking: affordability (45th), people of a similar age (44th), arts (46th), health care (41st) and safety (37th). To rank the best and worst states for retirees, Bankrate compared all 50 states across 15 data points spanning eight categories.",
      "ai_analysis": "No specific analysis was generated for this source."
    }
  ],
  "metadata": {
    "retrieval_query_used": "When it comes to income taxes, Wisconsin is one of the best places in the country to be poor but top 4 or 5 worst for middle-income earners.",
    "fallback_used": false,
    "search_raw_evidence_count": 8,
    "selected_evidence_count": 2
  }
}
========================================================================================================================
gold_label: false
mapped_gold_label: False
strict_correct: False
relaxed_correct: False
{
  "claim_group_id": 286,
  "fact_claim_id": 1,
  "original_sentence": "Says House Democrats voted to use your tax dollars for abortions by voting against bill defunding Planned Parenthood.",
  "text_feature_text": "Says House Democrats voted to use your tax dollars for abortions by voting against bill defunding Planned Parenthood.",
  "claim": "Says House Democrats voted to use your tax dollars for abortions by voting against bill defunding Planned Parenthood.",
  "status": "degraded",
  "truth_score": null,
  "verdict": null,
  "explanation": "Gemini API key is missing.",
  "decision_confidence": "low",
  "evidence_sufficiency": "sufficient",
  "evidence": [
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "https://www.nytimes.com/interactive/2025/06/30/upshot/senate-republican-megabill.html",
      "content": "| Excise tax on money sent abroad  Impose new excise tax on remittance transfers, with exceptions for transfers funded with a debit or credit card issued in the U.S. or made through certain financial institutions | –$10.0 bil. | Medicaid managed care taxes  Prevent states from using taxes on managed care plans to increase federal funding | –$34 bil. | Premium tax credits for immigrants  Limit eligibility to green card holders and certain other immigrants (current law includes all who are “lawfully present”) | –$75 bil. | “Climate Change Action Plans” for state, local and tribal governments  Rescind Inflation Reduction Act funds | –$0.1 bil. | Clean heavy-duty vehicles rescission  Rescind Inflation Reduction Act funds that help states and localities adopt zero-emission vehicles | –$0.4 bil. | Green federal buildings rescissions  Rescind Inflation Reduction Act funds | –$0.7 bil. | Energy rescissions  Rescind Inflation Reduction Act funds for home, facility, transmission and other energy programs | –$7.1 bil.",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "https://lancasteronline.com/news/politics/",
      "content": "HARRISBURG — Pennsylvania Senate Democrats slammed the Republican majority Tuesday for focusing on “culture war issues” instead of affordability amid state",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "https://www.eurasiareview.com/24042026-us-senate-gop-adopts-budget-blueprint-laying-path-to-finance-ice-border-patrol/",
      "content": "One amendment adopted, 15 turned down. Senators ultimately debated 16 amendments, 12 offered by Democrats and four proposed by Republicans. The",
      "ai_analysis": "No specific analysis was generated for this source."
    }
  ],
  "metadata": {
    "retrieval_query_used": "Says House Democrats voted to use your tax dollars for abortions by voting against bill defunding Planned Parenthood.",
    "fallback_used": false,
    "search_raw_evidence_count": 8,
    "selected_evidence_count": 3
  }
}
========================================================================================================================
gold_label: half-true
mapped_gold_label: Neutral
strict_correct: False
relaxed_correct: False
{
  "claim_group_id": 458,
  "fact_claim_id": 1,
  "original_sentence": "The Congressional Budget Office estimates that for every $1 we spend on unemployment benefits, $1.90 is put into our economy.",
  "text_feature_text": "The Congressional Budget Office estimates that for every $1 we spend on unemployment benefits, $1.90 is put into our economy.",
  "claim": "The Congressional Budget Office estimates that for every $1 we spend on unemployment benefits, $1.90 is put into our economy.",
  "status": "insufficient_evidence",
  "truth_score": null,
  "verdict": null,
  "explanation": "Retrieved evidence discussed the topic, but key claim details pointed in a different direction.",
  "decision_confidence": "low",
  "evidence_sufficiency": "insufficient",
  "evidence": [],
  "metadata": {
    "retrieval_query_used": "The Congressional Budget Office estimates that for every $1 we spend on unemployment benefits, $1.90 is put into our economy.",
    "fallback_used": false,
    "search_raw_evidence_count": 2,
    "selected_evidence_count": 0
  }
}
========================================================================================================================
gold_label: mostly-true
mapped_gold_label: Mostly True
strict_correct: False
relaxed_correct: False
{
  "claim_group_id": 502,
  "fact_claim_id": 1,
  "original_sentence": "In the city of Milwaukee, weve still got a mayor and a police chief who are furloughing police officers at a time when we have violence all across the city.",
  "text_feature_text": "In the city of Milwaukee, weve still got a mayor and a police chief who are furloughing police officers at a time when we have violence all across the city.",
  "claim": "In the city of Milwaukee, weve still got a mayor and a police chief who are furloughing police officers at a time when we have violence all across the city.",
  "status": "insufficient_evidence",
  "truth_score": null,
  "verdict": null,
  "explanation": "Retrieved evidence was found, but it did not line up closely enough with the specific claim to support a verdict.",
  "decision_confidence": "low",
  "evidence_sufficiency": "insufficient",
  "evidence": [],
  "metadata": {
    "retrieval_query_used": "In the city of Milwaukee, weve still got a mayor and a police chief who are furloughing police officers at a time when we have violence all across the city.",
    "fallback_used": false,
    "search_raw_evidence_count": 1,
    "selected_evidence_count": 0
  }
}
========================================================================================================================
gold_label: true
mapped_gold_label: True
strict_correct: False
relaxed_correct: False
{

## Cell 12: Batch Summary Table
Create a compact claim-level table from the raw batch outputs.

In [14]:
batch_summary_rows = []

for item in batch_raw_outputs:
    row = build_claim_summary_row(
        item['factual_claim'],
        gold_label=item['gold_label'],
        mapped_gold_label=item['mapped_gold_label'],
    )
    row['strict_correct'] = item['strict_correct']
    row['relaxed_correct'] = item['relaxed_correct']
    batch_summary_rows.append(row)

batch_summary_df = pd.DataFrame(batch_summary_rows)
display(batch_summary_df)

,claim_group_id,fact_claim_id,claim,gold_label,mapped_gold_label,status,truth_score,verdict,decision_confidence,evidence_sufficiency,selected_evidence_count,fallback_used,search_raw_evidence_count,retrieval_query_used,strict_correct,relaxed_correct
0,52,1,Hillary Clinton said gun confiscation would be...,barely-true,Mostly False,degraded,None,None,low,sufficient,3,False,8,Hillary Clinton said gun confiscation would be...,False,False
1,179,1,President Obama and Nancy Pelosi said Obamacar...,half-true,Neutral,insufficient_evidence,None,None,low,insufficient,0,False,3,President Obama and Nancy Pelosi said Obamacar...,False,False
2,210,1,Says an Obama administration policy prohibits ...,false,False,degraded,None,None,low,limited,2,False,8,Says an Obama administration policy prohibits ...,False,False
3,229,1,"When it comes to income taxes, Wisconsin is on...",mostly-true,Mostly True,degraded,None,None,low,insufficient,2,False,8,"When it comes to income taxes, Wisconsin is on...",False,False
4,286,1,Says House Democrats voted to use your tax dol...,false,False,degraded,None,None,low,sufficient,3,False,8,Says House Democrats voted to use your tax dol...,False,False
5,458,1,The Congressional Budget Office estimates that...,half-true,Neutral,insufficient_evidence,None,None,low,insufficient,0,False,2,The Congressional Budget Office estimates that...,False,False
6,502,1,"In the city of Milwaukee, weve still got a may...",mostly-true,Mostly True,insufficient_evidence,None,None,low,insufficient,0,False,1,"In the city of Milwaukee, weve still got a may...",False,False
7,564,1,Says he came to the Republican Party sooner in...,true,True,degraded,None,None,low,insufficient,1,False,7,Says he came to the Republican Party sooner in...,False,False
8,1117,1,Scott Walker had a 2.3 GPA when he was asked t...,false,False,degraded,None,None,low,sufficient,3,False,6,Scott Walker had a 2.3 GPA when he was asked t...,False,False
9,1210,1,"Says he brought 1,200 jobs to Texas by moving ...",half-true,Neutral,degraded,None,None,low,sufficient,3,False,7,"Says he brought 1,200 jobs to Texas by moving ...",False,False

## Cell 13: Overall Batch Metrics
Build a small overall summary from the claim-level table.

In [15]:
summary_df = pd.DataFrame([{
    'sample_size': len(batch_summary_df),
    'success_count': int((batch_summary_df['status'] == 'success').sum()),
    'insufficient_evidence_count': int((batch_summary_df['status'] == 'insufficient_evidence').sum()),
    'degraded_count': int((batch_summary_df['status'] == 'degraded').sum()),
    'invalid_request_count': int((batch_summary_df['status'] == 'invalid_request').sum()),
    'strict_accuracy': round(batch_summary_df['strict_correct'].mean(), 3),
    'relaxed_accuracy': round(batch_summary_df['relaxed_correct'].mean(), 3),
    'avg_search_raw_evidence_count': round(batch_summary_df['search_raw_evidence_count'].mean(), 3),
    'avg_selected_evidence_count': round(batch_summary_df['selected_evidence_count'].mean(), 3),
    'fallback_used_count': int(batch_summary_df['fallback_used'].fillna(False).sum()),
    'neutral_count': int((batch_summary_df['verdict'] == 'Neutral').sum()),
    'unknown_count': int(batch_summary_df['verdict'].isna().sum() + (batch_summary_df['verdict'] == 'Unknown').sum()),
}])

display(summary_df)

,sample_size,success_count,insufficient_evidence_count,degraded_count,invalid_request_count,strict_accuracy,relaxed_accuracy,avg_search_raw_evidence_count,avg_selected_evidence_count,fallback_used_count,neutral_count,unknown_count
0,10,0,3,7,0,0.0,0.0,5.8,1.7,0,0,10

## Cell 14: Failure and Status Breakdown
View the most common failure/status patterns without losing the raw outputs.

In [16]:
failure_reason_rows = []
for item in batch_raw_outputs:
    factual_claim = item['factual_claim']
    explanation = factual_claim.get('explanation', '') or ''
    failure_reason_rows.append({
        'status': factual_claim.get('status', ''),
        'explanation': explanation,
    })

failure_reason_df = pd.DataFrame(failure_reason_rows)
status_df = failure_reason_df['status'].value_counts(dropna=False).reset_index()
status_df.columns = ['status', 'count']

display(status_df)

                  status  count
0               degraded      7
1  insufficient_evidence      3

## Cell 15: Flatten Evidence into a Table
Build one row per `EachEvidence` so the evidence is easy to scan across claims.

This is the main table for checking whether the selected evidence makes sense.

In [17]:
evidence_rows = []
for item in batch_raw_outputs:
    evidence_rows.extend(build_evidence_rows(item['factual_claim']))

evidence_df = pd.DataFrame(evidence_rows)
display(evidence_df)

,claim_group_id,fact_claim_id,claim,evidence_index,stance,evidence_quality,url,content,ai_analysis
0,52,1,Hillary Clinton said gun confiscation would be...,1,background,strong,https://www.politifact.com/factchecks/2016/oct...,# NRA weakly claims that Clinton said gun conf...,No specific analysis was generated for this so...
1,52,1,Hillary Clinton said gun confiscation would be...,2,background,strong,https://www.ydr.com/story/opinion/columnists/2...,Hillary is bad news for gun owners (column). #...,No specific analysis was generated for this so...
2,52,1,Hillary Clinton said gun confiscation would be...,3,background,usable,https://shared.nrapvf.org/sharedmedia/1509247/...,Presorted First Class Mail US Postage Paid Per...,No specific analysis was generated for this so...
3,210,1,Says an Obama administration policy prohibits ...,1,background,usable,https://www.madinamerica.com/2017/06/do-psychi...,Dozens of people over the decades have basical...,No specific analysis was generated for this so...
4,210,1,Says an Obama administration policy prohibits ...,2,background,usable,https://www.justice-integrity.org/2176-april-2...,"Until now, she said, officials did not have to...",No specific analysis was generated for this so...
5,229,1,"When it comes to income taxes, Wisconsin is on...",1,background,usable,http://www.logandaily.com/comment/columns/can-...,"In general, the bill would expand eligibility ...",No specific analysis was generated for this so...
6,229,1,"When it comes to income taxes, Wisconsin is on...",2,background,weak,https://www.bankrate.com/retirement/best-and-w...,According to Bankrate’s 2025 Best and Worst St...,No specific analysis was generated for this so...
7,286,1,Says House Democrats voted to use your tax dol...,1,background,usable,https://www.nytimes.com/interactive/2025/06/30...,| Excise tax on money sent abroad Impose new ...,No specific analysis was generated for this so...
8,286,1,Says House Democrats voted to use your tax dol...,2,background,usable,https://lancasteronline.com/news/politics/,HARRISBURG — Pennsylvania Senate Democrats sla...,No specific analysis was generated for this so...
9,286,1,Says House Democrats voted to use your tax dol...,3,background,usable,https://www.eurasiareview.com/24042026-us-sena...,"One amendment adopted, 15 turned down. Senator...",No specific analysis was generated for this so...
10,564,1,Says he came to the Republican Party sooner in...,1,background,usable,https://www.politifact.com/factchecks/2011/sep...,"On his Aug. 30 radio program, conservative com...",No specific analysis was generated for this so...
11,1117,1,Scott Walker had a 2.3 GPA when he was asked t...,1,background,strong,https://www.politifact.com/factchecks/2015/aug...,"Scott Walker ""had a 2.3 GPA when he was asked ...",No specific analysis was generated for this so...
12,1117,1,Scott Walker had a 2.3 GPA when he was asked t...,2,background,usable,https://www.politifact.com/factchecks/2016/nov...,"Says Scott Walker left college ""under an ethic...",No specific analysis was generated for this so...
13,1117,1,Scott Walker had a 2.3 GPA when he was asked t...,3,background,weak,https://democraticunderground.com/1251396288,"*(60,536 posts)* Mon Feb 23, 2015, 06:11 PM Fe...",No specific analysis was generated for this so...
14,1210,1,"Says he brought 1,200 jobs to Texas by moving ...",1,background,strong,https://www.politifact.com/factchecks/2011/oct...,"In his campaign, Shami said in a TV ad that he...",No specific analysis was generated for this so...
15,1210,1,"Says he brought 1,200 jobs to Texas by moving ...",2,background,strong,https://www.politifact.com/factchecks/2010/jan...,"# Shami claims he's created 1,200 jobs in Texa...",No specific analysis was generated for this so...
16,1210,1,"Says he brought 1,200 jobs to Texas by moving ...",3,background,weak,https://www.studentnewsdaily.com/daily-news-ar...,"**(by Timothy Aeppel, WSJ.com) HOUSTON —** Far...",No specific analysis was generated for this so...

## Cell 16: Inspect Specific Claims as Full Objects
Pick a few row indices and print the full current `EachFactualClaim` objects for close reading.

In [18]:
TARGET_ROW_INDEXES = [item['factual_claim']['claim_group_id'] for item in batch_raw_outputs[:3]]

for target_row_index in TARGET_ROW_INDEXES:
    target_output = next(item['factual_claim'] for item in batch_raw_outputs if item['factual_claim']['claim_group_id'] == target_row_index)
    print('=' * 120)
    print('target_row_index:', target_row_index)
    print(json.dumps(target_output, indent=2, ensure_ascii=False))

========================================================================================================================
target_row_index: 52
{
  "claim_group_id": 52,
  "fact_claim_id": 1,
  "original_sentence": "Hillary Clinton said gun confiscation would be worth considering.",
  "text_feature_text": "Hillary Clinton said gun confiscation would be worth considering.",
  "claim": "Hillary Clinton said gun confiscation would be worth considering.",
  "status": "degraded",
  "truth_score": null,
  "verdict": null,
  "explanation": "Gemini API key is missing.",
  "decision_confidence": "low",
  "evidence_sufficiency": "sufficient",
  "evidence": [
    {
      "stance": "background",
      "evidence_quality": "strong",
      "url": "https://www.politifact.com/factchecks/2016/oct/17/national-rifle-association/nra-weakly-claims-clinton-said-gun-confiscation-wo/",
      "content": "# NRA weakly claims that Clinton said gun confiscation is 'worth considering'. The NRA and other pro-gun groups instantly seized on Clinton’s comment, saying the buyback program Clinton lauded is tantamount to a confiscation program, because it backed many gun owners into a corner: They either could sell their firearms to the government or risk prosecution for keeping them. The NRA says that when Clinton was asked about gun confiscation, she said \"I think it would be worth doing it on a national level, if that can be arranged.\". Clinton made that statement last year at a New Hampshire campaign stop, when she was asked a vague question about an Australian program that gave gun owners one year to sell certain firearms to the government before those weapons became illegal. CNN, \"NRA slams Hillary Clinton, claims she supports confiscating guns,\" Oct. 16, 2015. ### NRA weakly claims that Clinton said gun confiscation is 'worth considering'.",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "strong",
      "url": "https://www.ydr.com/story/opinion/columnists/2016/10/24/hillary-bad-news-gun-owners-column/92688738/",
      "content": "Hillary is bad news for gun owners (column). # Hillary is bad news for gun owners (column). I encourage every gun owner to do the same. Secretary Clinton said during a Democratic primary debate that Australia's gun confiscation program was \"worth looking at.\" An example gun outlawed in Australia? That is the kind of gun control Hillary Clinton thinks is \"worth looking at.\". In addition, Secretary Clinton has repeatedly refused to accept the Supreme Court's decision in the Heller gun rights case. The law overturned in Heller required guns kept in a home to be disassembled or fitted with trigger locks. Even an adult living alone had to have the gun disassembled or fitted with a trigger lock. If you are one of America's 100 million gun owners or if you are one of Pennsylvania's 750,000 hunters, you must vote against Hillary Clinton on Nov. 8 to protect your Second Amendment rights. Facebook) Twitter https://www.ydr.com/story/opinion/columnists/2016/10/24/hillary-bad-news-gun-owners-column/92688738/ via @ydrcom) Email.",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "https://shared.nrapvf.org/sharedmedia/1509247/nra-hillary-clinton-postcard.pdf",
      "content": "Presorted First Class Mail US Postage Paid Permit No. 3905 Suburban MD WHAT DID HILLARY CLINTON SAY WHEN SHE WAS ASKED ABOUT GUN CONFISCATION IN AMERICA? HER OWN WORDS CONFIRM HER PLANS TO BAN YOUR GUNS When it comes to banning guns and eliminating your rights, Hillary Clinton has big plans. And I’m going to make that case every chance I get.” (Washington Free Beacon, 10/1/15) “We’re going to start the very first day and tackle the gun lobby.” (MSNBC, 4/25/2016) “When it comes to guns, we have just too many guns.” (USA Today, 4/20/2016) Hillary Clinton wants to overturn the Heller decision, which held that you have right to keep a gun in your home for self-defense. If elected president, she will immediately nominate an anti-gun justice for the Supreme Court and overturn your right to own a gun. Hillary Clinton’s first priority in office would be to attack your rights.",
      "ai_analysis": "No specific analysis was generated for this source."
    }
  ],
  "metadata": {
    "retrieval_query_used": "Hillary Clinton said gun confiscation would be worth considering.",
    "fallback_used": false,
    "search_raw_evidence_count": 8,
    "selected_evidence_count": 3
  }
}
========================================================================================================================
target_row_index: 179
{
  "claim_group_id": 179,
  "fact_claim_id": 1,
  "original_sentence": "President Obama and Nancy Pelosi said Obamacare would save money because they factored in 10 years worth of tax revenue and only six and half years worth of expenses.",
  "text_feature_text": "President Obama and Nancy Pelosi said Obamacare would save money because they factored in 10 years worth of tax revenue and only six and half years worth of expenses.",
  "claim": "President Obama and Nancy Pelosi said Obamacare would save money because they factored in 10 years worth of tax revenue and only six and half years worth of expenses.",
  "status": "insufficient_evidence",
  "truth_score": null,
  "verdict": null,
  "explanation": "Retrieved evidence was found, but it did not line up closely enough with the specific claim to support a verdict.",
  "decision_confidence": "low",
  "evidence_sufficiency": "insufficient",
  "evidence": [],
  "metadata": {
    "retrieval_query_used": "President Obama and Nancy Pelosi said Obamacare would save money because they factored in 10 years worth of tax revenue and only six and half years worth of expenses.",
    "fallback_used": false,
    "search_raw_evidence_count": 3,
    "selected_evidence_count": 0
  }
}
========================================================================================================================
target_row_index: 210
{
  "claim_group_id": 210,
  "fact_claim_id": 1,
  "original_sentence": "Says an Obama administration policy prohibits people who work with at-risk youth from promoting marriage as a way to avoid poverty.",
  "text_feature_text": "Says an Obama administration policy prohibits people who work with at-risk youth from promoting marriage as a way to avoid poverty.",
  "claim": "Says an Obama administration policy prohibits people who work with at-risk youth from promoting marriage as a way to avoid poverty.",
  "status": "degraded",
  "truth_score": null,
  "verdict": null,
  "explanation": "Gemini API key is missing.",
  "decision_confidence": "low",
  "evidence_sufficiency": "limited",
  "evidence": [
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "https://www.madinamerica.com/2017/06/do-psychiatrists-harm-patients-out-of-stupidity/",
      "content": "Dozens of people over the decades have basically asked me the same kind of anguished question: “How can someone like my psychiatrist who is very smart, someone with a medical degree, who has been sitting a few feet away from me for years, keep on totally missing what I need as they persist in treating me like I’m invisible?”. Furthermore, I am told that it is written, “Robert, what do you see when you look in the mirror?” While, a good ‘existential’ therapist, desiring to demonstrate just how and why the post-modern social world is ‘alienating’ of the human sense of self, might ask Robert, “do see your eyes and mistake a word for the reality of and the function of your eyes?” Furthermore, can you admit the ‘habituated’ nature of your behaviour and why, in addressing psychiatrists with well-chosen words, you find yourself (existentially) behaving like a well initiated Jew standing before a famous wall in a famous city, where words are repeated in parrot-like fashion, with a heartfelt hope of personal transformation.",
      "ai_analysis": "No specific analysis was generated for this source."
    },
    {
      "stance": "background",
      "evidence_quality": "usable",
      "url": "https://www.justice-integrity.org/2176-april-25-news",
      "content": "Until now, she said, officials did not have to worry about repercussions from “taking a strong stance on policy issues in ways that are inconsistent with the president’s agenda.” But that was the sort of pressure that Mr. Powell faced as Mr. Trump sought to force rates down. “I was never much in favor of it,” Mr. Trump said from the Oval Office, when asked about concerns that federal employees might be leveraging insider information on the prediction markets. In a letter filed in Manhattan federal court, the U.S. attorney for the Southern District of New York, Jay Clayton, said that the Treasury Department had issued amended licenses that would allow defense lawyers for Mr. Maduro, the former president of Venezuela, and his wife, Cilia Flores, to receive payments from their country’s government. *Vice President JD Vance, right, shares words with President Trump in a February event at the White House Oval Office (New York Times photo).*.",
      "ai_analysis": "No specific analysis was generated for this source."
    }
  ],
  "metadata": {
    "retrieval_query_used": "Says an Obama administration policy prohibits people who work with at-risk youth from promoting marriage as a way to avoid poverty.",
    "fallback_used": false,
    "search_raw_evidence_count": 8,
    "selected_evidence_count": 2
  }
}

## Cell 17: Optional Raw Retrieval vs Selected Evidence Diagnostic
Use this only when we want to inspect the filter behavior itself.

It compares raw retrieved evidence with the final selected evidence for a few chosen rows.

In [19]:
from fact_checking.gemini_agent import prepare_claim_for_fact_checking
from fact_checking.retrieval_service import retrieve_evidence
from fact_checking.nli_filter import filter_top_evidence

TARGET_ROWS = [item['factual_claim']['claim_group_id'] for item in batch_raw_outputs[:3]]

def build_raw_scored_df(filter_debug, selected_urls):
    scored_rows = []
    for item in filter_debug.get('scored_evidence', []):
        scored_rows.append({
            'url': item.get('url', ''),
            'selected_for_verdict': item.get('url', '') in selected_urls,
            'filter_reason': item.get('filter_reason', ''),
            'passed_threshold': item.get('passed_threshold', False),
            'source_quality': item.get('source_quality', ''),
            'source_quality_score': item.get('source_quality_score', 0.0),
            'relevance_score': item.get('relevance_score', None),
            'claim_match_score': item.get('claim_match_score', None),
            'number_score': item.get('number_score', None),
            'number_status': item.get('number_status', ''),
            'final_match_score': item.get('final_match_score', None),
            'selection_priority': item.get('selection_priority', None),
            'evidence_quality': item.get('evidence_quality', ''),
            'content_preview': item.get('content_preview', ''),
        })
    return pd.DataFrame(scored_rows)

for row_index in TARGET_ROWS:
    target_item = next(item for item in batch_sampled_claims if item['row_index'] == row_index)
    claim = target_item['claim']

    print('=' * 120)
    print('ROW', row_index)
    print('=' * 120)
    print('Claim:', claim)

    claim_check = prepare_claim_for_fact_checking(claim, use_query_rewrite=True)
    final_claim = claim_check.final_claim if claim_check.is_valid_claim else claim

    retrieval = retrieve_evidence(
        original_claim=claim,
        final_claim=final_claim,
        retrieval_results=8,
        use_oversampling_retry=True,
    )

    print('Claim valid:', claim_check.is_valid_claim)
    print('Final claim used:', retrieval.final_claim)
    print('Search raw count:', retrieval.search_raw_count)
    print('Fallback used:', retrieval.fallback_used)
    print()

    if retrieval.error_type:
        print('Retrieval error type:', retrieval.error_type)
        print('Retrieval error message:', retrieval.error_message)
        print()
        continue

    selected_evidence, filter_debug = filter_top_evidence(
        retrieval.final_claim,
        retrieval.raw_evidence,
        relevance_threshold=0.1,
        top_k=3,
        use_all_eligible_evidence=False,
        return_debug_info=True,
    )

    selected_urls = {item.get('url', '') for item in selected_evidence}
    raw_scored_df = build_raw_scored_df(filter_debug, selected_urls)

    print('Raw scored evidence')
    display(raw_scored_df)

    selected_rows = []
    for idx, item in enumerate(selected_evidence, start=1):
        selected_rows.append({
            'selected_index': idx,
            'url': item.get('url', ''),
            'source_quality': item.get('source_quality', ''),
            'source_quality_score': item.get('source_quality_score', 0.0),
            'evidence_quality': item.get('evidence_quality', ''),
            'content_preview': item.get('content', '')[:300],
        })

    selected_df = pd.DataFrame(selected_rows)
    print('Final selected evidence')
    display(selected_df)

========================================================================================================================
ROW 52
========================================================================================================================
Claim: Hillary Clinton said gun confiscation would be worth considering.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
Claim valid: True
Final claim used: Hillary Clinton said gun confiscation would be worth considering.
Search raw count: 8
Fallback used: False

Raw scored evidence

,url,selected_for_verdict,filter_reason,passed_threshold,source_quality,source_quality_score,relevance_score,claim_match_score,number_score,number_status,final_match_score,selection_priority,evidence_quality,content_preview
0,https://www.politifact.com/factchecks/2016/oct...,True,passed,True,fact_check,0.95,0.840623,1.000000,0.5,not_needed,0.837343,0.848280,strong,# NRA weakly claims that Clinton said gun conf...
1,https://www.ydr.com/story/opinion/columnists/2...,True,passed,True,general_web,0.65,0.888471,0.750000,0.5,not_needed,0.788659,0.764812,strong,Hillary is bad news for gun owners (column). #...
2,https://shared.nrapvf.org/sharedmedia/1509247/...,True,passed,True,general_web,0.65,0.516198,0.647059,0.5,not_needed,0.553026,0.566407,usable,Presorted First Class Mail US Postage Paid Per...
3,https://time.com/4445591/nra-ad-hillary-clinto...,False,passed,True,general_web,0.65,0.319694,0.852941,0.5,not_needed,0.506714,0.539745,usable,The National Rifle Association on Tuesday bega...
4,https://thehill.com/blogs/blog-briefing-room/n...,False,passed,True,general_web,0.65,0.006086,0.727941,0.5,not_needed,0.296730,0.361121,weak,Clinton last week said an Australian-style gun...
5,https://www.aljazeera.com/news/2015/10/17/clin...,False,passed,True,general_web,0.65,0.033649,0.573529,0.5,not_needed,0.265566,0.327201,weak,"*NRA angered by Democrat frontrunner, who said..."
6,https://www.nbcphiladelphia.com/news/national-...,False,passed,True,general_web,0.65,0.134675,0.352941,0.5,not_needed,0.254954,0.306486,weak,"**Johnson:** “What difference, at this point, ..."
7,https://www.cnn.com/2015/10/16/politics/nra-hi...,False,low_claim_match,False,general_web,0.65,0.001339,0.323529,0.5,not_needed,0.172796,0.237662,weak,The nation's largest gun organization unleashe...

Final selected evidence

,selected_index,url,source_quality,source_quality_score,evidence_quality,content_preview
0,1,https://www.politifact.com/factchecks/2016/oct...,fact_check,0.95,strong,# NRA weakly claims that Clinton said gun conf...
1,2,https://www.ydr.com/story/opinion/columnists/2...,general_web,0.65,strong,Hillary is bad news for gun owners (column). #...
2,3,https://shared.nrapvf.org/sharedmedia/1509247/...,general_web,0.65,usable,Presorted First Class Mail US Postage Paid Per...

========================================================================================================================
ROW 179
========================================================================================================================
Claim: President Obama and Nancy Pelosi said Obamacare would save money because they factored in 10 years worth of tax revenue and only six and half years worth of expenses.
[Search] Retrieved 3 results | Filtered shell: 0 | Deduplicated: 0
Claim valid: True
Final claim used: President Obama and Nancy Pelosi said Obamacare would save money because they factored in 10 years worth of tax revenue and only six and half years worth of expenses.
Search raw count: 3
Fallback used: False

[NLI Filter] Warning: Evidence was somewhat related, but still not close enough to the claim.
Raw scored evidence

,url,selected_for_verdict,filter_reason,passed_threshold,source_quality,source_quality_score,relevance_score,claim_match_score,number_score,number_status,final_match_score,selection_priority,evidence_quality,content_preview
0,https://www.alternet.org/msn/,False,conflicting_claim_details,False,general_web,0.65,0.001532,0.323944,0.2,conflict,0.128026,0.192873,weak,“They're lying to him like there's no tomorrow...
1,https://www.unz.com/mhudson/iran-war-ignites-g...,False,low_claim_match,False,general_web,0.65,0.839577,0.028169,0.4,missing,0.530218,0.511260,weak,We are joined today by Professor Michael Hudso...
2,https://immigrationcourtside.com/category/immi...,False,low_claim_match,False,general_web,0.65,0.998633,0.056338,0.4,missing,0.626150,0.591286,weak,This report is based on the experiences of imm...

Final selected evidence

Empty DataFrame
Columns: []
Index: []

========================================================================================================================
ROW 210
========================================================================================================================
Claim: Says an Obama administration policy prohibits people who work with at-risk youth from promoting marriage as a way to avoid poverty.
[Search] Retrieved 8 results | Filtered shell: 0 | Deduplicated: 0
Claim valid: True
Final claim used: Says an Obama administration policy prohibits people who work with at-risk youth from promoting marriage as a way to avoid poverty.
Search raw count: 8
Fallback used: False

Raw scored evidence

,url,selected_for_verdict,filter_reason,passed_threshold,source_quality,source_quality_score,relevance_score,claim_match_score,number_score,number_status,final_match_score,selection_priority,evidence_quality,content_preview
0,https://www.madinamerica.com/2017/06/do-psychi...,True,passed,True,general_web,0.65,0.997864,0.247525,0.5,not_needed,0.698083,0.663296,usable,Dozens of people over the decades have basical...
1,https://www.justice-integrity.org/2176-april-2...,True,passed,True,general_web,0.65,0.928667,0.247525,0.5,not_needed,0.660024,0.632158,usable,"Until now, she said, officials did not have to..."
2,https://www.instagram.com/balleralert/related_...,False,low_claim_match,False,general_web,0.65,0.996621,0.033003,0.5,not_needed,0.633043,0.598381,weak,Trump DOJ Moves to Reinstate Firing Squad for ...
3,https://pure.ulster.ac.uk/ws/files/224640213/A...,False,low_claim_match,False,general_web,0.65,0.983974,0.000000,0.5,not_needed,0.616186,0.582788,weak,"R. Sprott School of Business, Carleton Univers..."
4,https://en.wikipedia.org/wiki/Supreme_Court_of...,False,low_claim_match,False,reference,0.72,0.948575,0.000000,0.5,not_needed,0.596717,0.573859,weak,| | * v * t * e Supreme Courts of the Americas...
5,https://www.nytimes.com/2017/04/04/us/civil-ri...,False,low_claim_match,False,major_news,0.82,0.000332,0.211221,0.5,not_needed,0.138549,0.220516,weak,You have a preview view of this article while ...
6,https://ognsc.com/wp-content/uploads/VNO-4.23....,False,low_claim_match,False,general_web,0.65,0.002690,0.178218,0.5,not_needed,0.129945,0.194676,weak,"Laura Lindberg, director of the Concentration ..."
7,https://www.politico.com/news/magazine/2019/12...,False,low_claim_match,False,general_web,0.65,0.027200,0.079208,0.5,not_needed,0.113722,0.176002,weak,We asked 23 top historians to write the paragr...

Final selected evidence

,selected_index,url,source_quality,source_quality_score,evidence_quality,content_preview
0,1,https://www.madinamerica.com/2017/06/do-psychi...,general_web,0.65,usable,Dozens of people over the decades have basical...
1,2,https://www.justice-integrity.org/2176-april-2...,general_web,0.65,usable,"Until now, she said, officials did not have to..."

In [20]:
from fact_checking.gemini_agent import is_gemini_available

print("Gemini available:", is_gemini_available())

Gemini available: False