In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import sys

# 1. Define paths
project_root = '/content/drive/MyDrive/UoP/COMP3000/fake-news-detector-v1'
search_function_root = os.path.join(project_root, 'backend', 'fact_checking')

print("⏳ Running system initialization check...")

# 2. Check if the main folder exists (still abort if missing)
if not os.path.exists(search_function_root):
    print(f"Can't find project root directory -> {search_function_root}")
    sys.exit("Please check if this starter is mounted to drive or if the directory is correct")
print(f"✅ Project root directory found -> {project_root}")
# 3. Now just check what files are inside the folder (no abort if files are missing)
print(f"\n📂 Looking inside: {search_function_root}")

# List all .py files in the directory
all_items = os.listdir(search_function_root)

if all_items:
    # Separate files and folders
    files = []
    folders = []

    for item in all_items:
        item_path = os.path.join(search_function_root, item)
        if os.path.isdir(item_path):
            folders.append(item)
        else:
            files.append(item)

    # Sort both lists alphabetically
    files.sort()
    folders.sort()

    # Print files first, then folders
    print("\n Files:")
    for file_name in files:
        print(f"   - {file_name}")

    print("\n Folders:")
    for folder_name in folders:
        print(f"   - {folder_name}")
else:
    print("No items found in this directory.")

try:
  os.chdir(search_function_root)
except Exception:
  print(f"Can't switch to directory -> {search_function_root}")
  sys.exit("Please check if this starter is mounted to drive or if the directory is correct")

⏳ Running system initialization check...
✅ Project root directory found -> /content/drive/MyDrive/UoP/COMP3000/fake-news-detector-v1

📂 Looking inside: /content/drive/MyDrive/UoP/COMP3000/fake-news-detector-v1/backend/fact_checking

 Files:
   - FINAL_EVALUATION_100.csv
   - Some notes.gdoc
   - app.py
   - decision_utils.py
   - evaluation_results_5.csv
   - fact_checking_function_experiment.ipynb
   - gemini_agent.py
   - nli_filter.py
   - num_evidence_adjust.ipynb
   - search.py
   - search_main.ipynb

 Folders:
   - __pycache__
   - v1

In [ ]:
!pip install fastapi pydantic uvicorn nest-asyncio pyngrok
!pip install google-genai

Requirement already satisfied: fastapi in /usr/local/lib/python3.12/dist-packages (0.135.3)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (2.12.3)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.12/dist-packages (0.44.0)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (1.6.0)
Collecting pyngrok
  Downloading pyngrok-8.0.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.52.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.0.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic) (2.41.4)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (8.3.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (0.16.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=0.46.0->fastapi) (4.13.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.11)
Downloading pyngrok-8.0.0-py3-none-any.whl (24 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.0.0
Requirement already satisfied: google-genai in /usr/local/lib/python3.12/dist-packages (1.68.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (4.13.0)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai) (2.47.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.9.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (2.12.3)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai) (2.32.4)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.5.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (0.6.3)

In [ ]:
import os
os.environ["TAVILY_API_KEY"] = "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"
os.environ["NGROK_TOKEN"] = "3AwEicqRQS6F4GesXCzu3EA5Drd_7mw2bZnc6pXeqhytJxeFy"
os.environ["GEMINI_API_KEY"] = "AIzaSyC5CfBmlrTDBPMqoDMe4OUaW_ODSduG_Lk"

In [ ]:
%run app.py

[NLI Filter] Loading model: cross-encoder/nli-deberta-v3-base

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

special_tokens_map.json:   0%|          | 0.00/301 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/738M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: cross-encoder/nli-deberta-v3-base
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[NLI Filter] Model loaded.
API is live at: https://chivalric-intermetallic-loma.ngrok-free.dev/docs
[Server] FastAPI is starting on port 8000...

In [ ]:
# ============================================================
# Experiment Cell: Query Rewriting Effectiveness Evaluation
#
# Purpose:
# This experiment evaluates whether the function
# `optimize_claim_for_search()` improves retrieval performance.
#
# We compare two retrieval pipelines:
# 1) Using the original user claim
# 2) Using the optimized claim produced by the rewrite module
#
# Metrics collected:
# - Retrieval success (whether usable evidence exists)
# - Number of selected evidence items after NLI filtering
#
# This experiment focuses only on the retrieval stage.
# It does NOT include final verdict generation.
#
# Files involved:
# - gemini_agent.py       (query rewriting module)
# - search.py             (retrieval module)
# - nli_filter.py         (evidence filtering module)
# ============================================================

from gemini_agent import optimize_claim_for_search
from search import fetch_oversampled_evidence
from nli_filter import filter_top_evidence


# ------------------------------------------------------------
# Test claims for the experiment
# These claims include different linguistic styles:
# - conversational claims
# - misinformation-style claims
# - factual statements
# ------------------------------------------------------------

test_claims = [
    "iran is still shooting bombs",
    "Albert Einstein failed math in school",
    "Drinking lemon water detoxifies the liver",
    "The earth is flat",
    "COVID vaccines cause infertility",
    "Barack Obama was born in Kenya",
    "Sharks do not get cancer",
    "China has the largest population in the world",
    "Coffee dehydrates you",
    "The Great Wall is visible from space"
]


# ------------------------------------------------------------
# Function: compare_original_vs_optimized
#
# This function runs the retrieval pipeline twice:
#   A) using the original claim
#   B) using the optimized claim
#
# It returns statistics for comparison.
# ------------------------------------------------------------

def compare_original_vs_optimized(claim_text: str, max_results: int = 8, top_k: int = 3):

    # Generate optimized claim using the rewrite module
    optimized_claim = optimize_claim_for_search(claim_text)

    # Retrieve raw evidence using the original claim
    original_raw_evidence = fetch_oversampled_evidence(claim_text, max_results=max_results)

    # Retrieve raw evidence using the optimized claim
    optimized_raw_evidence = fetch_oversampled_evidence(optimized_claim, max_results=max_results)

    # Apply NLI evidence filtering
    original_selected_evidence = filter_top_evidence(claim_text, original_raw_evidence, top_k=top_k)
    optimized_selected_evidence = filter_top_evidence(claim_text, optimized_raw_evidence, top_k=top_k)

    # Compute simple retrieval metrics
    original_retrieval_success = len(original_selected_evidence) > 0
    optimized_retrieval_success = len(optimized_selected_evidence) > 0

    return {
        "original_claim": claim_text,
        "optimized_claim": optimized_claim,
        "original_retrieval_success": original_retrieval_success,
        "optimized_retrieval_success": optimized_retrieval_success,
        "original_evidence_count": len(original_selected_evidence),
        "optimized_evidence_count": len(optimized_selected_evidence),
    }


# ------------------------------------------------------------
# Run the experiment
# ------------------------------------------------------------

experiment_results = []

for claim in test_claims:
    result = compare_original_vs_optimized(claim)
    experiment_results.append(result)


# ------------------------------------------------------------
# Print results in a readable format
# ------------------------------------------------------------

print("=" * 80)
print("Query Rewriting Experiment Results")
print("=" * 80)

for result in experiment_results:
    print("\nClaim:", result["original_claim"])
    print("Optimized Claim:", result["optimized_claim"])

    print("Original Retrieval Success:", result["original_retrieval_success"])
    print("Optimized Retrieval Success:", result["optimized_retrieval_success"])

    print("Original Evidence Count:", result["original_evidence_count"])
    print("Optimized Evidence Count:", result["optimized_evidence_count"])

INFO:     Started server process [3372]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
================================================================================
Query Rewriting Experiment Results
================================================================================

Claim: iran is still shooting bombs
Optimized Claim: Iran is still shooting bombs
Original Retrieval Success: False
Optimized Retrieval Success: False
Original Evidence Count: 0
Optimized Evidence Count: 0

Claim: Albert Einstein failed math in school
Optimized Claim: Albert Einstein failed math in school
Original Retrieval Success: False
Optimized Retrieval Success: False
Original Evidence Count: 0
Optimized Evidence Count: 0

Claim: Drinking lemon water detoxifies the liver
Optimized Claim: Drinking lemon water detoxifies the liver
Original Retrieval Success: False
Optimized Retrieval Success: False
Original Evidence Count: 0
Optimized Evidence Count: 0

Claim: The earth is flat
Optimized Claim: The earth is flat
Original Retrieval Success: False
Optimized Retrieval Success: False
Original Evidence Count: 0
Optimized Evidence Count: 0

Claim: COVID vaccines cause infertility
Optimized Claim: COVID vaccines cause infertility
Original Retrieval Success: False
Optimized Retrieval Success: False
Original Evidence Count: 0
Optimized Evidence Count: 0

Claim: Barack Obama was born in Kenya
Optimized Claim: Barack Obama was born in Kenya
Original Retrieval Success: False
Optimized Retrieval Success: False
Original Evidence Count: 0
Optimized Evidence Count: 0

Claim: Sharks do not get cancer
Optimized Claim: Sharks do not get cancer
Original Retrieval Success: False
Optimized Retrieval Success: False
Original Evidence Count: 0
Optimized Evidence Count: 0

Claim: China has the largest population in the world
Optimized Claim: China has the largest population in the world
Original Retrieval Success: False
Optimized Retrieval Success: False
Original Evidence Count: 0
Optimized Evidence Count: 0

Claim: Coffee dehydrates you
Optimized Claim: Coffee dehydrates you
Original Retrieval Success: False
Optimized Retrieval Success: False
Original Evidence Count: 0
Optimized Evidence Count: 0

Claim: The Great Wall is visible from space
Optimized Claim: The Great Wall is visible from space
Original Retrieval Success: False
Optimized Retrieval Success: False
Original Evidence Count: 0
Optimized Evidence Count: 0

In [ ]:
# ============================================================
# Experiment Cell: Clean Threshold Sweep with Fixed Intermediate Results
#
# Purpose:
# This experiment isolates the effect of relevance_threshold
# in nli_filter.py.
#
# Design:
# For each claim:
# 1. rewrite the claim only once
# 2. retrieve raw evidence only once
# 3. keep optimized_claim and raw_evidence fixed
# 4. sweep only the relevance_threshold
#
# Why this cell exists:
# The previous threshold experiment was contaminated because
# rewrite and retrieval were re-run for every threshold value.
# This cell removes that confound so we can measure only the
# effect of the NLI relevance threshold.
#
# Files involved:
# - gemini_agent.py   : query rewriting
# - search.py         : retrieval
# - nli_filter.py     : evidence filtering
#
# Report-ready metrics:
# - claims with surviving evidence
# - average surviving evidence count
# - per-claim evidence count by threshold
# ============================================================

from gemini_agent import optimize_claim_for_search
from search import fetch_oversampled_evidence
from nli_filter import filter_top_evidence

import pandas as pd


# ------------------------------------------------------------
# Step 1. Define evaluation claims and threshold grid
# ------------------------------------------------------------

test_claims = [
    "iran is still shooting bombs",
    "Albert Einstein failed math in school",
    "Drinking lemon water detoxifies the liver",
    "The earth is flat",
    "COVID vaccines cause infertility",
    "Barack Obama was born in Kenya",
    "Sharks do not get cancer",
    "China has the largest population in the world",
    "Coffee dehydrates you",
    "The Great Wall is visible from space"
]

threshold_values = [0.10, 0.20, 0.30, 0.40, 0.50]

max_results = 8
top_k = 3


# ------------------------------------------------------------
# Step 2. Build a fixed cache of intermediate results
#
# Important:
# Each claim is rewritten once and retrieved once only.
# These cached results will be reused across all thresholds.
# ------------------------------------------------------------

fixed_pipeline_cache = []

for claim_text in test_claims:
    optimized_claim = optimize_claim_for_search(claim_text)
    raw_evidence = fetch_oversampled_evidence(optimized_claim, max_results=max_results)

    retrieval_error = (
        len(raw_evidence) > 0 and raw_evidence[0].get("url") == "Error"
    )

    fixed_pipeline_cache.append({
        "original_claim": claim_text,
        "optimized_claim": optimized_claim,
        "raw_evidence": raw_evidence,
        "raw_evidence_count": 0 if retrieval_error else len(raw_evidence),
        "retrieval_error": retrieval_error
    })

print("=" * 80)
print("Cached intermediate results are ready.")
print("Each claim was rewritten once and retrieved once.")
print("=" * 80)

for item in fixed_pipeline_cache:
    print(
        f"Claim: {item['original_claim']}\n"
        f"Optimized Claim: {item['optimized_claim']}\n"
        f"Raw Evidence Count: {item['raw_evidence_count']}\n"
        f"Retrieval Error: {item['retrieval_error']}\n"
        + "-" * 80
    )


# ------------------------------------------------------------
# Step 3. Sweep thresholds on the same cached raw evidence
#
# This is the clean part of the experiment:
# only relevance_threshold changes here.
# ------------------------------------------------------------

threshold_experiment_rows = []

for cached_item in fixed_pipeline_cache:
    original_claim = cached_item["original_claim"]
    optimized_claim = cached_item["optimized_claim"]
    raw_evidence = cached_item["raw_evidence"]
    raw_evidence_count = cached_item["raw_evidence_count"]
    retrieval_error = cached_item["retrieval_error"]

    for threshold_value in threshold_values:
        if retrieval_error:
            selected_evidence = []
        else:
            selected_evidence = filter_top_evidence(
                user_claim=optimized_claim,
                oversampled_evidence=raw_evidence,
                relevance_threshold=threshold_value,
                top_k=top_k
            )

        threshold_experiment_rows.append({
            "original_claim": original_claim,
            "optimized_claim": optimized_claim,
            "threshold": threshold_value,
            "raw_evidence_count": raw_evidence_count,
            "retrieval_error": retrieval_error,
            "surviving_evidence_count": len(selected_evidence),
            "has_surviving_evidence": len(selected_evidence) > 0
        })

threshold_results_df = pd.DataFrame(threshold_experiment_rows)


# ------------------------------------------------------------
# Step 4. Create report-friendly summary table
# ------------------------------------------------------------

summary_rows = []

for threshold_value in threshold_values:
    threshold_group = threshold_results_df[
        threshold_results_df["threshold"] == threshold_value
    ]

    summary_rows.append({
        "threshold": threshold_value,
        "claims_tested": len(threshold_group),
        "claims_with_surviving_evidence": int(threshold_group["has_surviving_evidence"].sum()),
        "survival_rate": round(
            threshold_group["has_surviving_evidence"].mean(), 3
        ),
        "avg_surviving_evidence_count": round(
            threshold_group["surviving_evidence_count"].mean(), 3
        )
    })

summary_df = pd.DataFrame(summary_rows)


# ------------------------------------------------------------
# Step 5. Create a pivot table for per-claim comparison
# ------------------------------------------------------------

pivot_df = threshold_results_df.pivot_table(
    index=["original_claim", "optimized_claim", "raw_evidence_count"],
    columns="threshold",
    values="surviving_evidence_count",
    aggfunc="first"
).reset_index()

pivot_df.columns.name = None


# ------------------------------------------------------------
# Step 6. Print readable output
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("Clean Threshold Sweep Summary")
print("=" * 80)
print(summary_df.to_string(index=False))

print("\n" + "=" * 80)
print("Per-Claim Surviving Evidence Count by Threshold")
print("=" * 80)
print(pivot_df.to_string(index=False))


# ------------------------------------------------------------
# Optional:
# Keep the raw row-level results for later export or plotting
# ------------------------------------------------------------

threshold_results_df

[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
================================================================================
Cached intermediate results are ready.
Each claim was rewritten once and retrieved once.
================================================================================
Claim: iran is still shooting bombs
Optimized Claim: Iran is still shooting bombs
Raw Evidence Count: 0
Retrieval Error: True
--------------------------------------------------------------------------------
Claim: Albert Einstein failed math in school
Optimized Claim: Albert Einstein failed math in school
Raw Evidence Count: 0
Retrieval Error: True
--------------------------------------------------------------------------------
Claim: Drinking lemon water detoxifies the liver
Optimized Claim: Drinking lemon water detoxifies the liver
Raw Evidence Count: 0
Retrieval Error: True
--------------------------------------------------------------------------------
Claim: The earth is flat
Optimized Claim: The earth is flat
Raw Evidence Count: 0
Retrieval Error: True
--------------------------------------------------------------------------------
Claim: COVID vaccines cause infertility
Optimized Claim: COVID vaccines cause infertility
Raw Evidence Count: 0
Retrieval Error: True
--------------------------------------------------------------------------------
Claim: Barack Obama was born in Kenya
Optimized Claim: Barack Obama was born in Kenya
Raw Evidence Count: 0
Retrieval Error: True
--------------------------------------------------------------------------------
Claim: Sharks do not get cancer
Optimized Claim: Sharks do not get cancer
Raw Evidence Count: 0
Retrieval Error: True
--------------------------------------------------------------------------------
Claim: China has the largest population in the world
Optimized Claim: China has the largest population in the world
Raw Evidence Count: 0
Retrieval Error: True
--------------------------------------------------------------------------------
Claim: Coffee dehydrates you
Optimized Claim: Coffee dehydrates you
Raw Evidence Count: 0
Retrieval Error: True
--------------------------------------------------------------------------------
Claim: The Great Wall is visible from space
Optimized Claim: The Great Wall is visible from space
Raw Evidence Count: 0
Retrieval Error: True
--------------------------------------------------------------------------------

================================================================================
Clean Threshold Sweep Summary
================================================================================
 threshold  claims_tested  claims_with_surviving_evidence  survival_rate  avg_surviving_evidence_count
       0.1             10                               0            0.0                           0.0
       0.2             10                               0            0.0                           0.0
       0.3             10                               0            0.0                           0.0
       0.4             10                               0            0.0                           0.0
       0.5             10                               0            0.0                           0.0

================================================================================
Per-Claim Surviving Evidence Count by Threshold
================================================================================
                               original_claim                               optimized_claim  raw_evidence_count  0.1  0.2  0.3  0.4  0.5
        Albert Einstein failed math in school         Albert Einstein failed math in school                   0    0    0    0    0    0
               Barack Obama was born in Kenya                Barack Obama was born in Kenya                   0    0    0    0    0    0
             COVID vaccines cause infertility              COVID vaccines cause infertility                   0    0    0    0    0    0
China has the largest population in the world China has the largest population in the world                   0    0    0    0    0    0
                        Coffee dehydrates you                         Coffee dehydrates you                   0    0    0    0    0    0
    Drinking lemon water detoxifies the liver     Drinking lemon water detoxifies the liver                   0    0    0    0    0    0
                     Sharks do not get cancer                      Sharks do not get cancer                   0    0    0    0    0    0
         The Great Wall is visible from space          The Great Wall is visible from space                   0    0    0    0    0    0
                            The earth is flat                             The earth is flat                   0    0    0    0    0    0
                 iran is still shooting bombs                  Iran is still shooting bombs                   0    0    0    0    0    0

,original_claim,optimized_claim,threshold,raw_evidence_count,retrieval_error,surviving_evidence_count,has_surviving_evidence
0,iran is still shooting bombs,Iran is still shooting bombs,0.1,0,True,0,False
1,iran is still shooting bombs,Iran is still shooting bombs,0.2,0,True,0,False
2,iran is still shooting bombs,Iran is still shooting bombs,0.3,0,True,0,False
3,iran is still shooting bombs,Iran is still shooting bombs,0.4,0,True,0,False
4,iran is still shooting bombs,Iran is still shooting bombs,0.5,0,True,0,False
5,Albert Einstein failed math in school,Albert Einstein failed math in school,0.1,0,True,0,False
6,Albert Einstein failed math in school,Albert Einstein failed math in school,0.2,0,True,0,False
7,Albert Einstein failed math in school,Albert Einstein failed math in school,0.3,0,True,0,False
8,Albert Einstein failed math in school,Albert Einstein failed math in school,0.4,0,True,0,False
9,Albert Einstein failed math in school,Albert Einstein failed math in school,0.5,0,True,0,False
10,Drinking lemon water detoxifies the liver,Drinking lemon water detoxifies the liver,0.1,0,True,0,False
11,Drinking lemon water detoxifies the liver,Drinking lemon water detoxifies the liver,0.2,0,True,0,False
12,Drinking lemon water detoxifies the liver,Drinking lemon water detoxifies the liver,0.3,0,True,0,False
13,Drinking lemon water detoxifies the liver,Drinking lemon water detoxifies the liver,0.4,0,True,0,False
14,Drinking lemon water detoxifies the liver,Drinking lemon water detoxifies the liver,0.5,0,True,0,False
15,The earth is flat,The earth is flat,0.1,0,True,0,False
16,The earth is flat,The earth is flat,0.2,0,True,0,False
17,The earth is flat,The earth is flat,0.3,0,True,0,False
18,The earth is flat,The earth is flat,0.4,0,True,0,False
19,The earth is flat,The earth is flat,0.5,0,True,0,False
20,COVID vaccines cause infertility,COVID vaccines cause infertility,0.1,0,True,0,False
21,COVID vaccines cause infertility,COVID vaccines cause infertility,0.2,0,True,0,False
22,COVID vaccines cause infertility,COVID vaccines cause infertility,0.3,0,True,0,False
23,COVID vaccines cause infertility,COVID vaccines cause infertility,0.4,0,True,0,False
24,COVID vaccines cause infertility,COVID vaccines cause infertility,0.5,0,True,0,False
25,Barack Obama was born in Kenya,Barack Obama was born in Kenya,0.1,0,True,0,False
26,Barack Obama was born in Kenya,Barack Obama was born in Kenya,0.2,0,True,0,False
27,Barack Obama was born in Kenya,Barack Obama was born in Kenya,0.3,0,True,0,False
28,Barack Obama was born in Kenya,Barack Obama was born in Kenya,0.4,0,True,0,False
29,Barack Obama was born in Kenya,Barack Obama was born in Kenya,0.5,0,True,0,False
30,Sharks do not get cancer,Sharks do not get cancer,0.1,0,True,0,False
31,Sharks do not get cancer,Sharks do not get cancer,0.2,0,True,0,False
32,Sharks do not get cancer,Sharks do not get cancer,0.3,0,True,0,False
33,Sharks do not get cancer,Sharks do not get cancer,0.4,0,True,0,False
34,Sharks do not get cancer,Sharks do not get cancer,0.5,0,True,0,False
35,China has the largest population in the world,China has the largest population in the world,0.1,0,True,0,False
36,China has the largest population in the world,China has the largest population in the world,0.2,0,True,0,False
37,China has the largest population in the world,China has the largest population in the world,0.3,0,True,0,False
38,China has the largest population in the world,China has the largest population in the world,0.4,0,True,0,False
39,China has the largest population in the world,China has the largest population in the world,0.5,0,True,0,False
40,Coffee dehydrates you,Coffee dehydrates you,0.1,0,True,0,False
41,Coffee dehydrates you,Coffee dehydrates you,0.2,0,True,0,False
42,Coffee dehydrates you,Coffee dehydrates you,0.3,0,True,0,False
43,Coffee dehydrates you,Coffee dehydrates you,0.4,0,True,0,False
44,Coffee dehydrates you,Coffee dehydrates you,0.5,0,True,0,False
45,The Great Wall is visible from space,The Great Wall is visible from space,0.1,0,True,0,False
46,The Great Wall is visible from space,The Great Wall is visible from space,0.2,0,True,0,False
47,The Great Wall is visible from space,The Great Wall is visible from space,0.3,0,True,0,False
48,The Great Wall is visible from space,The Great Wall is visible from space,0.4,0,True,0,False
49,The Great Wall is visible from space,The Great Wall is visible from space,0.5,0,True,0,False

In [ ]:
# ============================================================
# Experiment Cell: API Behavior Sanity Check
#
# Purpose:
# This cell tests whether the /analyze API returns stable,
# product-friendly fields after the recent pipeline changes.
#
# What this cell checks:
# 1. status
# 2. decision_stage
# 3. failure_reason
# 4. optimized_claim
# 5. retrieval_strategy_used
# 6. retrieval_query_used
# 7. fallback_used
# 8. selected_evidence_count
# 9. verdict
#
# Why this cell exists:
# The earlier experiments focused on retrieval and filtering.
# This cell checks the end-to-end product behavior at the API layer.
# It is not an accuracy benchmark. It is a pipeline behavior check.
# ============================================================

import requests
import pandas as pd
import json

# ------------------------------------------------------------
# Step 1. Define API endpoint
# ------------------------------------------------------------

api_url = "http://0.0.0.0:8000/analyze"

# If you are calling through ngrok instead, replace api_url with:
# api_url = "https://your-ngrok-url/analyze"


# ------------------------------------------------------------
# Step 2. Define sanity-check claims
# ------------------------------------------------------------

api_test_claims = [
    "The earth is flat",
    "China has the largest population in the world",
    "COVID vaccines cause infertility",
    "Barack Obama was born in Kenya",
    "Coffee dehydrates you",
    "Drinking lemon water detoxifies the liver",
    "iran is still shooting bombs",
    "The Great Wall is visible from space",
    "What do you think about coffee?",
    ""
]


# ------------------------------------------------------------
# Step 3. Call /analyze for each claim
# ------------------------------------------------------------

api_results = []

for claim_text in api_test_claims:
    try:
        response = requests.post(api_url, json={"claim": claim_text}, timeout=60)
        response.raise_for_status()
        result_json = response.json()

        api_results.append({
            "input_claim": claim_text,
            "status": result_json.get("status", ""),
            "decision_stage": result_json.get("decision_stage", ""),
            "failure_reason": result_json.get("failure_reason", ""),
            "optimized_claim": result_json.get("optimized_claim", ""),
            "retrieval_strategy_used": result_json.get("retrieval_strategy_used", ""),
            "retrieval_query_used": result_json.get("retrieval_query_used", ""),
            "fallback_used": result_json.get("fallback_used", False),
            "selected_evidence_count": result_json.get("selected_evidence_count", 0),
            "verdict": result_json.get("verdict", ""),
            "truth_score": result_json.get("truth_score", 0.5),
            "source_count": len(result_json.get("sources", [])),
            "raw_response": result_json
        })

    except Exception as error:
        api_results.append({
            "input_claim": claim_text,
            "status": "request_failed",
            "decision_stage": "",
            "failure_reason": str(error),
            "optimized_claim": "",
            "retrieval_strategy_used": "",
            "retrieval_query_used": "",
            "fallback_used": False,
            "selected_evidence_count": 0,
            "verdict": "",
            "truth_score": None,
            "source_count": 0,
            "raw_response": None
        })


# ------------------------------------------------------------
# Step 4. Build summary table
# ------------------------------------------------------------

api_results_df = pd.DataFrame(api_results)

summary_columns = [
    "input_claim",
    "status",
    "decision_stage",
    "failure_reason",
    "optimized_claim",
    "retrieval_strategy_used",
    "retrieval_query_used",
    "fallback_used",
    "selected_evidence_count",
    "source_count",
    "verdict",
    "truth_score"
]

print("=" * 100)
print("API Behavior Sanity Check Summary")
print("=" * 100)
print(api_results_df[summary_columns].to_string(index=False))


# ------------------------------------------------------------
# Step 5. Print full JSON for manual inspection
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("Full API Responses")
print("=" * 100)

for item in api_results:
    print("\n" + "-" * 100)
    print(f"Input Claim: {item['input_claim']}")
    if item["raw_response"] is not None:
        print(json.dumps(item["raw_response"], indent=2, ensure_ascii=False))
    else:
        print("Request failed.")
        print(f"Error: {item['failure_reason']}")

[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
INFO:     127.0.0.1:57268 - "POST /analyze HTTP/1.1" 200 OK
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
INFO:     127.0.0.1:57278 - "POST /analyze HTTP/1.1" 200 OK
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
INFO:     127.0.0.1:57294 - "POST /analyze HTTP/1.1" 200 OK
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
INFO:     127.0.0.1:57306 - "POST /analyze HTTP/1.1" 200 OK
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
INFO:     127.0.0.1:57322 - "POST /analyze HTTP/1.1" 200 OK
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
INFO:     127.0.0.1:57336 - "POST /analyze HTTP/1.1" 200 OK
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
INFO:     127.0.0.1:57340 - "POST /analyze HTTP/1.1" 200 OK
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
INFO:     127.0.0.1:57342 - "POST /analyze HTTP/1.1" 200 OK
INFO:     127.0.0.1:50602 - "POST /analyze HTTP/1.1" 200 OK
INFO:     127.0.0.1:50618 - "POST /analyze HTTP/1.1" 200 OK
====================================================================================================
API Behavior Sanity Check Summary
====================================================================================================
                                  input_claim       status   decision_stage   failure_reason                               optimized_claim retrieval_strategy_used                          retrieval_query_used  fallback_used  selected_evidence_count  source_count verdict  truth_score
                            The earth is flat system_error        retrieval search_api_error                             The earth is flat          optimized_only                             The earth is flat          False                        0             0 Neutral          0.5
China has the largest population in the world system_error        retrieval search_api_error China has the largest population in the world          optimized_only China has the largest population in the world          False                        0             0 Neutral          0.5
             COVID vaccines cause infertility system_error        retrieval search_api_error              COVID vaccines cause infertility          optimized_only              COVID vaccines cause infertility          False                        0             0 Neutral          0.5
               Barack Obama was born in Kenya system_error        retrieval search_api_error                Barack Obama was born in Kenya          optimized_only                Barack Obama was born in Kenya          False                        0             0 Neutral          0.5
                        Coffee dehydrates you system_error        retrieval search_api_error                         Coffee dehydrates you          optimized_only                         Coffee dehydrates you          False                        0             0 Neutral          0.5
    Drinking lemon water detoxifies the liver system_error        retrieval search_api_error     Drinking lemon water detoxifies the liver          optimized_only     Drinking lemon water detoxifies the liver          False                        0             0 Neutral          0.5
                 iran is still shooting bombs system_error        retrieval search_api_error                  Iran is still shooting bombs          optimized_only                  Iran is still shooting bombs          False                        0             0 Neutral          0.5
         The Great Wall is visible from space system_error        retrieval search_api_error          The Great Wall is visible from space          optimized_only          The Great Wall is visible from space          False                        0             0 Neutral          0.5
              What do you think about coffee?      success claim_validation    invalid_claim                                 INVALID_CLAIM                    none                                                        False                        0             0 Neutral          0.5
                                                   success claim_validation      empty_claim                                                                  none                                                        False                        0             0 Neutral          0.5

====================================================================================================
Full API Responses
====================================================================================================

----------------------------------------------------------------------------------------------------
Input Claim: The earth is flat
{
  "status": "system_error",
  "original_claim": "The earth is flat",
  "optimized_claim": "The earth is flat",
  "decision_stage": "retrieval",
  "failure_reason": "search_api_error",
  "truth_score": 0.5,
  "verdict": "Neutral",
  "explanation": "No evidence found due to an unexpected search error.",
  "sources": [],
  "decision_confidence": "low",
  "stabilization_used": false,
  "stabilization_delta": 0.0,
  "stabilization_result": "not_triggered",
  "evidence_sufficiency": "insufficient",
  "evidence_quality": "weak",
  "retrieval_strategy_used": "optimized_only",
  "retrieval_query_used": "The earth is flat",
  "optimized_raw_evidence_count": 0,
  "original_raw_evidence_count": 0,
  "selected_evidence_count": 0,
  "fallback_used": false,
  "excluded_borderline_candidate_count": 0
}

----------------------------------------------------------------------------------------------------
Input Claim: China has the largest population in the world
{
  "status": "system_error",
  "original_claim": "China has the largest population in the world",
  "optimized_claim": "China has the largest population in the world",
  "decision_stage": "retrieval",
  "failure_reason": "search_api_error",
  "truth_score": 0.5,
  "verdict": "Neutral",
  "explanation": "No evidence found due to an unexpected search error.",
  "sources": [],
  "decision_confidence": "low",
  "stabilization_used": false,
  "stabilization_delta": 0.0,
  "stabilization_result": "not_triggered",
  "evidence_sufficiency": "insufficient",
  "evidence_quality": "weak",
  "retrieval_strategy_used": "optimized_only",
  "retrieval_query_used": "China has the largest population in the world",
  "optimized_raw_evidence_count": 0,
  "original_raw_evidence_count": 0,
  "selected_evidence_count": 0,
  "fallback_used": false,
  "excluded_borderline_candidate_count": 0
}

----------------------------------------------------------------------------------------------------
Input Claim: COVID vaccines cause infertility
{
  "status": "system_error",
  "original_claim": "COVID vaccines cause infertility",
  "optimized_claim": "COVID vaccines cause infertility",
  "decision_stage": "retrieval",
  "failure_reason": "search_api_error",
  "truth_score": 0.5,
  "verdict": "Neutral",
  "explanation": "No evidence found due to an unexpected search error.",
  "sources": [],
  "decision_confidence": "low",
  "stabilization_used": false,
  "stabilization_delta": 0.0,
  "stabilization_result": "not_triggered",
  "evidence_sufficiency": "insufficient",
  "evidence_quality": "weak",
  "retrieval_strategy_used": "optimized_only",
  "retrieval_query_used": "COVID vaccines cause infertility",
  "optimized_raw_evidence_count": 0,
  "original_raw_evidence_count": 0,
  "selected_evidence_count": 0,
  "fallback_used": false,
  "excluded_borderline_candidate_count": 0
}

----------------------------------------------------------------------------------------------------
Input Claim: Barack Obama was born in Kenya
{
  "status": "system_error",
  "original_claim": "Barack Obama was born in Kenya",
  "optimized_claim": "Barack Obama was born in Kenya",
  "decision_stage": "retrieval",
  "failure_reason": "search_api_error",
  "truth_score": 0.5,
  "verdict": "Neutral",
  "explanation": "No evidence found due to an unexpected search error.",
  "sources": [],
  "decision_confidence": "low",
  "stabilization_used": false,
  "stabilization_delta": 0.0,
  "stabilization_result": "not_triggered",
  "evidence_sufficiency": "insufficient",
  "evidence_quality": "weak",
  "retrieval_strategy_used": "optimized_only",
  "retrieval_query_used": "Barack Obama was born in Kenya",
  "optimized_raw_evidence_count": 0,
  "original_raw_evidence_count": 0,
  "selected_evidence_count": 0,
  "fallback_used": false,
  "excluded_borderline_candidate_count": 0
}

----------------------------------------------------------------------------------------------------
Input Claim: Coffee dehydrates you
{
  "status": "system_error",
  "original_claim": "Coffee dehydrates you",
  "optimized_claim": "Coffee dehydrates you",
  "decision_stage": "retrieval",
  "failure_reason": "search_api_error",
  "truth_score": 0.5,
  "verdict": "Neutral",
  "explanation": "No evidence found due to an unexpected search error.",
  "sources": [],
  "decision_confidence": "low",
  "stabilization_used": false,
  "stabilization_delta": 0.0,
  "stabilization_result": "not_triggered",
  "evidence_sufficiency": "insufficient",
  "evidence_quality": "weak",
  "retrieval_strategy_used": "optimized_only",
  "retrieval_query_used": "Coffee dehydrates you",
  "optimized_raw_evidence_count": 0,
  "original_raw_evidence_count": 0,
  "selected_evidence_count": 0,
  "fallback_used": false,
  "excluded_borderline_candidate_count": 0
}

----------------------------------------------------------------------------------------------------
Input Claim: Drinking lemon water detoxifies the liver
{
  "status": "system_error",
  "original_claim": "Drinking lemon water detoxifies the liver",
  "optimized_claim": "Drinking lemon water detoxifies the liver",
  "decision_stage": "retrieval",
  "failure_reason": "search_api_error",
  "truth_score": 0.5,
  "verdict": "Neutral",
  "explanation": "No evidence found due to an unexpected search error.",
  "sources": [],
  "decision_confidence": "low",
  "stabilization_used": false,
  "stabilization_delta": 0.0,
  "stabilization_result": "not_triggered",
  "evidence_sufficiency": "insufficient",
  "evidence_quality": "weak",
  "retrieval_strategy_used": "optimized_only",
  "retrieval_query_used": "Drinking lemon water detoxifies the liver",
  "optimized_raw_evidence_count": 0,
  "original_raw_evidence_count": 0,
  "selected_evidence_count": 0,
  "fallback_used": false,
  "excluded_borderline_candidate_count": 0
}

----------------------------------------------------------------------------------------------------
Input Claim: iran is still shooting bombs
{
  "status": "system_error",
  "original_claim": "iran is still shooting bombs",
  "optimized_claim": "Iran is still shooting bombs",
  "decision_stage": "retrieval",
  "failure_reason": "search_api_error",
  "truth_score": 0.5,
  "verdict": "Neutral",
  "explanation": "No evidence found due to an unexpected search error.",
  "sources": [],
  "decision_confidence": "low",
  "stabilization_used": false,
  "stabilization_delta": 0.0,
  "stabilization_result": "not_triggered",
  "evidence_sufficiency": "insufficient",
  "evidence_quality": "weak",
  "retrieval_strategy_used": "optimized_only",
  "retrieval_query_used": "Iran is still shooting bombs",
  "optimized_raw_evidence_count": 0,
  "original_raw_evidence_count": 0,
  "selected_evidence_count": 0,
  "fallback_used": false,
  "excluded_borderline_candidate_count": 0
}

----------------------------------------------------------------------------------------------------
Input Claim: The Great Wall is visible from space
{
  "status": "system_error",
  "original_claim": "The Great Wall is visible from space",
  "optimized_claim": "The Great Wall is visible from space",
  "decision_stage": "retrieval",
  "failure_reason": "search_api_error",
  "truth_score": 0.5,
  "verdict": "Neutral",
  "explanation": "No evidence found due to an unexpected search error.",
  "sources": [],
  "decision_confidence": "low",
  "stabilization_used": false,
  "stabilization_delta": 0.0,
  "stabilization_result": "not_triggered",
  "evidence_sufficiency": "insufficient",
  "evidence_quality": "weak",
  "retrieval_strategy_used": "optimized_only",
  "retrieval_query_used": "The Great Wall is visible from space",
  "optimized_raw_evidence_count": 0,
  "original_raw_evidence_count": 0,
  "selected_evidence_count": 0,
  "fallback_used": false,
  "excluded_borderline_candidate_count": 0
}

----------------------------------------------------------------------------------------------------
Input Claim: What do you think about coffee?
{
  "status": "success",
  "original_claim": "What do you think about coffee?",
  "optimized_claim": "INVALID_CLAIM",
  "decision_stage": "claim_validation",
  "failure_reason": "invalid_claim",
  "truth_score": 0.5,
  "verdict": "Neutral",
  "explanation": "The input does not look like a factual claim, so the system did not run fact-checking.",
  "sources": [],
  "decision_confidence": "low",
  "stabilization_used": false,
  "stabilization_delta": 0.0,
  "stabilization_result": "not_triggered",
  "evidence_sufficiency": "insufficient",
  "evidence_quality": "weak",
  "retrieval_strategy_used": "none",
  "retrieval_query_used": "",
  "optimized_raw_evidence_count": 0,
  "original_raw_evidence_count": 0,
  "selected_evidence_count": 0,
  "fallback_used": false,
  "excluded_borderline_candidate_count": 0
}

----------------------------------------------------------------------------------------------------
Input Claim:
{
  "status": "success",
  "original_claim": "",
  "optimized_claim": "",
  "decision_stage": "claim_validation",
  "failure_reason": "empty_claim",
  "truth_score": 0.5,
  "verdict": "Neutral",
  "explanation": "The input claim is empty.",
  "sources": [],
  "decision_confidence": "low",
  "stabilization_used": false,
  "stabilization_delta": 0.0,
  "stabilization_result": "not_triggered",
  "evidence_sufficiency": "insufficient",
  "evidence_quality": "weak",
  "retrieval_strategy_used": "none",
  "retrieval_query_used": "",
  "optimized_raw_evidence_count": 0,
  "original_raw_evidence_count": 0,
  "selected_evidence_count": 0,
  "fallback_used": false,
  "excluded_borderline_candidate_count": 0
}

In [ ]:
import os
import random
import pandas as pd
import requests

project_root = '/content/drive/MyDrive/UoP/COMP3000/fake-news-detector-v1'
test_dataset = os.path.join(project_root, 'data', 'LIAR', 'test.tsv')

SAMPLE_SIZE = 3
RANDOM_SEED = 42

api_url = "http://0.0.0.0:8000/analyze"


# ------------------------------------------------------------
# Step 2. Load LIAR test set
# LIAR TSV format:
# column 0 = label
# column 2 = claim text
# ------------------------------------------------------------

liar_df = pd.read_csv(test_dataset, sep="\t", header=None)
liar_df = liar_df[[0, 2]].copy()
liar_df.columns = ["liar_label", "claim"]

In [ ]:
# Small end-to-end test cell for the current score-driven verdict pipeline
# This cell belongs to notebook testing, not the core backend code.
# Its job is to run a few LIAR claims through app.py and print the key outputs.

import os
import csv

from app import analyze_claim, ClaimRequest

project_root = '/content/drive/MyDrive/UoP/COMP3000/fake-news-detector-v1'
test_dataset = os.path.join(project_root, 'data', 'LIAR', 'test.tsv')

max_cases = 5

def load_liar_claims(tsv_path: str, max_rows: int = 5) -> list[dict]:
    """
    Read a few claims from the LIAR test split.
    LIAR is tab-separated, and the claim text is in column index 2.
    """
    loaded_claims = []

    with open(tsv_path, "r", encoding="utf-8") as file:
        reader = csv.reader(file, delimiter="\t")

        for row_index, row in enumerate(reader, start=1):
            if len(row) < 3:
                continue

            loaded_claims.append({
                "row_index": row_index,
                "label": row[1].strip(),
                "claim": row[2].strip()
            })

            if len(loaded_claims) >= max_rows:
                break

    return loaded_claims

test_claims = load_liar_claims(test_dataset, max_rows=max_cases)

for test_item in test_claims:
    claim_text = test_item["claim"]
    liar_label = test_item["label"]
    row_index = test_item["row_index"]

    print("=" * 100)
    print(f"LIAR row: {row_index}")
    print(f"LIAR label: {liar_label}")
    print(f"Claim: {claim_text}")

    try:
        response = analyze_claim(ClaimRequest(claim=claim_text))

        print(f"Status: {response.status}")
        print(f"Optimized claim: {response.optimized_claim}")
        print(f"Decision stage: {response.decision_stage}")
        print(f"Failure reason: {response.failure_reason}")
        print(f"Retrieval strategy used: {response.retrieval_strategy_used}")
        print(f"Retrieval query used: {response.retrieval_query_used}")
        print(f"Optimized raw evidence count: {response.optimized_raw_evidence_count}")
        print(f"Original raw evidence count: {response.original_raw_evidence_count}")
        print(f"Selected evidence count: {response.selected_evidence_count}")
        print(f"Fallback used: {response.fallback_used}")
        print(f"Truth score: {response.truth_score}")
        print(f"Verdict: {response.verdict}")
        print(f"Explanation: {response.explanation}")

        if response.sources:
            print("-" * 100)
            print("Selected sources:")

            for source_index, source_item in enumerate(response.sources, start=1):
                print(f"[Source {source_index}] URL: {source_item.url}")
                print(f"[Source {source_index}] Content preview: {source_item.content[:300]}")
                print(f"[Source {source_index}] AI analysis: {source_item.ai_analysis}")
                print("-" * 100)

    except Exception as error:
        print(f"Error: {error}")

print("=" * 100)
print("Notebook test run completed.")

====================================================================================================
LIAR row: 1
LIAR label: true
Claim: Building a wall on the U.S.-Mexico border will take literally years.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Optimized claim: Building a wall on the U.S.-Mexico border will take literally years
Decision stage: retrieval
Failure reason: search_api_error
Retrieval strategy used: optimized_only
Retrieval query used: Building a wall on the U.S.-Mexico border will take literally years
Optimized raw evidence count: 0
Original raw evidence count: 0
Selected evidence count: 0
Fallback used: False
Truth score: 0.5
Verdict: Neutral
Explanation: No evidence found due to an unexpected search error.
====================================================================================================
LIAR row: 2
LIAR label: false
Claim: Wisconsin is on pace to double the number of layoffs this year.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Optimized claim: Wisconsin is on pace to double the number of layoffs this year
Decision stage: retrieval
Failure reason: search_api_error
Retrieval strategy used: optimized_only
Retrieval query used: Wisconsin is on pace to double the number of layoffs this year
Optimized raw evidence count: 0
Original raw evidence count: 0
Selected evidence count: 0
Fallback used: False
Truth score: 0.5
Verdict: Neutral
Explanation: No evidence found due to an unexpected search error.
====================================================================================================
LIAR row: 3
LIAR label: false
Claim: Says John McCain has done nothing to help the vets.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Optimized claim: John McCain has done nothing to help the vets
Decision stage: retrieval
Failure reason: search_api_error
Retrieval strategy used: optimized_only
Retrieval query used: John McCain has done nothing to help the vets
Optimized raw evidence count: 0
Original raw evidence count: 0
Selected evidence count: 0
Fallback used: False
Truth score: 0.5
Verdict: Neutral
Explanation: No evidence found due to an unexpected search error.
====================================================================================================
LIAR row: 4
LIAR label: half-true
Claim: Suzanne Bonamici supports a plan that will cut choice for Medicare Advantage seniors.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Optimized claim: Suzanne Bonamici supports a plan that will cut choice for Medicare Advantage seniors.
Decision stage: retrieval
Failure reason: search_api_error
Retrieval strategy used: optimized_only
Retrieval query used: Suzanne Bonamici supports a plan that will cut choice for Medicare Advantage seniors.
Optimized raw evidence count: 0
Original raw evidence count: 0
Selected evidence count: 0
Fallback used: False
Truth score: 0.5
Verdict: Neutral
Explanation: No evidence found due to an unexpected search error.
====================================================================================================
LIAR row: 5
LIAR label: pants-fire
Claim: When asked by a reporter whether hes at the center of a criminal scheme to violate campaign laws, Gov. Scott Walker nodded yes.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Optimized claim: Gov. Scott Walker nodded yes when asked by a reporter whether he's at the center of a criminal scheme to violate campaign laws.
Decision stage: retrieval
Failure reason: search_api_error
Retrieval strategy used: optimized_only
Retrieval query used: Gov. Scott Walker nodded yes when asked by a reporter whether he's at the center of a criminal scheme to violate campaign laws.
Optimized raw evidence count: 0
Original raw evidence count: 0
Selected evidence count: 0
Fallback used: False
Truth score: 0.5
Verdict: Neutral
Explanation: No evidence found due to an unexpected search error.
====================================================================================================
Notebook test run completed.

In [ ]:
# ============================================================
# Experiment Cell: Confidence Diagnostic on LIAR Test Claims
#
# Purpose:
# This experiment inspects cases where the current pipeline
# returns a completed decision with a truth score that is
# noticeably away from 0.5.
#
# Why this cell exists:
# The new score-driven design is working, but we still need to
# check whether the system becomes too confident when the
# selected evidence is weak, indirect, or noisy.
#
# What this cell does:
# 1. Run a batch of LIAR test claims through the pipeline
# 2. Keep only completed cases
# 3. Print cases where the truth score is relatively confident
# 4. Show evidence previews and AI analyses for manual review
#
# Files involved:
# - app.py              (orchestration and verdict mapping)
# - gemini_agent.py     (truth score generation)
# - search.py           (retrieval)
# - nli_filter.py       (evidence filtering)
# ============================================================

import os
import csv

from app import analyze_claim, ClaimRequest

project_root = '/content/drive/MyDrive/UoP/COMP3000/fake-news-detector-v1'
test_dataset = os.path.join(project_root, 'data', 'LIAR', 'test.tsv')

max_cases = 20
low_score_cutoff = 0.35
high_score_cutoff = 0.65

def load_liar_claims(tsv_path: str, max_rows: int = 20) -> list[dict]:
    """
    Read a small batch of claims from the LIAR test split.
    LIAR is tab-separated, and the claim text is in column index 2.
    """
    loaded_claims = []

    with open(tsv_path, "r", encoding="utf-8") as file:
        reader = csv.reader(file, delimiter="\t")

        for row_index, row in enumerate(reader, start=1):
            if len(row) < 3:
                continue

            loaded_claims.append({
                "row_index": row_index,
                "label": row[1].strip(),
                "claim": row[2].strip()
            })

            if len(loaded_claims) >= max_rows:
                break

    return loaded_claims

test_claims = load_liar_claims(test_dataset, max_rows=max_cases)

flagged_cases = []
completed_case_count = 0

for test_item in test_claims:
    claim_text = test_item["claim"]
    liar_label = test_item["label"]
    row_index = test_item["row_index"]

    try:
        response = analyze_claim(ClaimRequest(claim=claim_text))
    except Exception as error:
        print("=" * 100)
        print(f"LIAR row: {row_index}")
        print(f"Claim: {claim_text}")
        print(f"Error: {error}")
        continue

    if response.decision_stage != "completed":
        continue

    completed_case_count += 1

    is_confident_case = (
        response.truth_score <= low_score_cutoff or
        response.truth_score >= high_score_cutoff
    )

    if not is_confident_case:
        continue

    flagged_cases.append({
        "row_index": row_index,
        "liar_label": liar_label,
        "claim": claim_text,
        "response": response
    })

print("=" * 100)
print("Confidence Diagnostic Summary")
print("=" * 100)
print(f"Claims tested: {len(test_claims)}")
print(f"Completed cases: {completed_case_count}")
print(f"Flagged confident cases: {len(flagged_cases)}")
print(f"Low score cutoff: {low_score_cutoff}")
print(f"High score cutoff: {high_score_cutoff}")

for flagged_item in flagged_cases:
    response = flagged_item["response"]

    print("\n" + "=" * 100)
    print(f"LIAR row: {flagged_item['row_index']}")
    print(f"LIAR label: {flagged_item['liar_label']}")
    print(f"Claim: {flagged_item['claim']}")
    print(f"Optimized claim: {response.optimized_claim}")
    print(f"Truth score: {response.truth_score}")
    print(f"Verdict: {response.verdict}")
    print(f"Selected evidence count: {response.selected_evidence_count}")
    print(f"Retrieval strategy used: {response.retrieval_strategy_used}")
    print(f"Retrieval query used: {response.retrieval_query_used}")
    print(f"Explanation: {response.explanation}")

    if response.sources:
        print("-" * 100)
        print("Selected sources for manual review:")

        for source_index, source_item in enumerate(response.sources, start=1):
            print(f"[Source {source_index}] URL: {source_item.url}")
            print(f"[Source {source_index}] Content preview: {source_item.content[:280]}")
            print(f"[Source {source_index}] AI analysis: {source_item.ai_analysis}")
            print("-" * 100)

print("\n" + "=" * 100)
print("Confidence diagnostic completed.")

[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
====================================================================================================
Confidence Diagnostic Summary
====================================================================================================
Claims tested: 20
Completed cases: 0
Flagged confident cases: 0
Low score cutoff: 0.35
High score cutoff: 0.65

====================================================================================================
Confidence diagnostic completed.

In [ ]:
# ============================================================
# Experiment Cell: Stage 1 Validation on Product-Facing Fields
#
# Purpose:
# This cell validates the new structured evidence fields added
# in Stage 1, so we can inspect whether the pipeline is now
# separating usable evidence from insufficient evidence more clearly.
#
# What this cell checks:
# 1. evidence_sufficiency
# 2. evidence_quality
# 3. source-level evidence_quality
# 4. final truth_score and verdict
#
# Why this cell exists:
# The previous cells focused mainly on truth_score and verdict.
# This one checks whether the new structured product-facing
# evidence signals behave in a sensible way.
# ============================================================

import os
import csv

from app import analyze_claim, ClaimRequest

project_root = '/content/drive/MyDrive/UoP/COMP3000/fake-news-detector-v1'
test_dataset = os.path.join(project_root, 'data', 'LIAR', 'test.tsv')

target_rows = {1, 3, 5, 7, 10, 14, 18}

def load_selected_liar_claims(tsv_path: str, target_row_set: set[int]) -> list[dict]:
    """
    Read only a few selected LIAR rows for focused validation.
    """
    selected_claims = []

    with open(tsv_path, "r", encoding="utf-8") as file:
        reader = csv.reader(file, delimiter="\t")

        for row_index, row in enumerate(reader, start=1):
            if row_index not in target_row_set:
                continue

            if len(row) < 3:
                continue

            selected_claims.append({
                "row_index": row_index,
                "label": row[1].strip(),
                "claim": row[2].strip()
            })

    return selected_claims

print("# Experiment Cell: Stage 1 Validation on Product-Facing Fields output:\n")
selected_claims = load_selected_liar_claims(test_dataset, target_rows)

for test_item in selected_claims:
    claim_text = test_item["claim"]
    liar_label = test_item["label"]
    row_index = test_item["row_index"]

    print("=" * 100)
    print(f"LIAR row: {row_index}")
    print(f"LIAR label: {liar_label}")
    print(f"Claim: {claim_text}")

    try:
        response = analyze_claim(ClaimRequest(claim=claim_text))

        print(f"Status: {response.status}")
        print(f"Decision stage: {response.decision_stage}")
        print(f"Failure reason: {response.failure_reason}")
        print(f"Optimized claim: {response.optimized_claim}")
        print(f"Truth score: {response.truth_score}")
        print(f"Verdict: {response.verdict}")
        print(f"Evidence sufficiency: {response.evidence_sufficiency}")
        print(f"Evidence quality: {response.evidence_quality}")
        print(f"Selected evidence count: {response.selected_evidence_count}")
        print(f"Retrieval strategy used: {response.retrieval_strategy_used}")
        print(f"Retrieval query used: {response.retrieval_query_used}")
        print(f"Explanation: {response.explanation}")

        if response.sources:
            print("-" * 100)
            print("Selected sources:")

            for source_index, source_item in enumerate(response.sources, start=1):
                print(f"[Source {source_index}] URL: {source_item.url}")
                print(f"[Source {source_index}] Evidence quality: {source_item.evidence_quality}")
                print(f"[Source {source_index}] Content preview: {source_item.content[:260]}")
                print(f"[Source {source_index}] AI analysis: {source_item.ai_analysis}")
                print("-" * 100)
        print(f"Decision confidence: {response.decision_confidence}")
        print(f"Stabilization used: {response.stabilization_used}")
        print(f"Stabilization delta: {response.stabilization_delta}")


    except Exception as error:
        print(f"Error: {error}")

print("=" * 100)
print("Stage 1 validation completed.")

# Experiment Cell: Stage 1 Validation on Product-Facing Fields output:

====================================================================================================
LIAR row: 1
LIAR label: true
Claim: Building a wall on the U.S.-Mexico border will take literally years.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: Building a wall on the U.S.-Mexico border will take years
Truth score: 0.5
Verdict: Neutral
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: Building a wall on the U.S.-Mexico border will take years
Explanation: No evidence found due to an unexpected search error.
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
====================================================================================================
LIAR row: 3
LIAR label: false
Claim: Says John McCain has done nothing to help the vets.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: John McCain has done nothing to help the vets.
Truth score: 0.5
Verdict: Neutral
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: John McCain has done nothing to help the vets.
Explanation: No evidence found due to an unexpected search error.
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
====================================================================================================
LIAR row: 5
LIAR label: pants-fire
Claim: When asked by a reporter whether hes at the center of a criminal scheme to violate campaign laws, Gov. Scott Walker nodded yes.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: Governor Scott Walker nodded yes when asked by a reporter whether he was at the center of a criminal scheme to violate campaign laws.
Truth score: 0.5
Verdict: Neutral
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: Governor Scott Walker nodded yes when asked by a reporter whether he was at the center of a criminal scheme to violate campaign laws.
Explanation: No evidence found due to an unexpected search error.
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
====================================================================================================
LIAR row: 7
LIAR label: true
Claim: Says that Tennessee law requires that schools receive half of proceeds -- $31 million per year -- from a half-cent increase in the Shelby County sales tax.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: Tennessee law requires schools to receive half of proceeds from a half-cent increase in the Shelby County sales tax.
Truth score: 0.5
Verdict: Neutral
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: Tennessee law requires schools to receive half of proceeds from a half-cent increase in the Shelby County sales tax.
Explanation: No evidence found due to an unexpected search error.
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
====================================================================================================
LIAR row: 10
LIAR label: barely-true
Claim: We know that more than half of Hillary Clintons meetings while she was secretary of state were given to major contributors to the Clinton Foundation.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: More than half of Hillary Clinton's meetings as secretary of state were given to major contributors to the Clinton Foundation.
Truth score: 0.5
Verdict: Neutral
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: More than half of Hillary Clinton's meetings as secretary of state were given to major contributors to the Clinton Foundation.
Explanation: No evidence found due to an unexpected search error.
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
====================================================================================================
LIAR row: 14
LIAR label: false
Claim: Says 57 percent of federal spending goes to the military and just 1 percent goes to food and agriculture, including food stamps.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: 57 percent of federal spending goes to the military and 1 percent goes to food and agriculture, including food stamps
Truth score: 0.5
Verdict: Neutral
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: 57 percent of federal spending goes to the military and 1 percent goes to food and agriculture, including food stamps
Explanation: No evidence found due to an unexpected search error.
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
====================================================================================================
LIAR row: 18
LIAR label: half-true
Claim: A recent Gallup poll found that 72 percent of Americans and 56 percent of Democrats say the biggest threat to our nations security is big government.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: A recent Gallup poll found that 72 percent of Americans and 56 percent of Democrats say the biggest threat to our nations security is big government.
Truth score: 0.5
Verdict: Neutral
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: A recent Gallup poll found that 72 percent of Americans and 56 percent of Democrats say the biggest threat to our nations security is big government.
Explanation: No evidence found due to an unexpected search error.
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
====================================================================================================
Stage 1 validation completed.

In [ ]:
# ============================================================
# Experiment Cell: Before-vs-After Behaviour Review
#
# Purpose:
# This cell reviews the current pipeline behaviour on a small
# set of representative LIAR claims after the recent product
# and evidence-control changes.
#
# Why this cell exists:
# The recent updates were designed to reduce unsupported verdicts
# and make the system more product-safe. This review checks:
# 1. whether clearly weak-evidence cases are now handled more safely
# 2. whether some previously decidable cases are now filtered out
#
# This is a behaviour review cell, not an automatic benchmark.
# It is intended for manual inspection and report writing.
# ============================================================

import os
import csv

from app import analyze_claim, ClaimRequest

project_root = '/content/drive/MyDrive/UoP/COMP3000/fake-news-detector-v1'
test_dataset = os.path.join(project_root, 'data', 'LIAR', 'test.tsv')

target_rows = {1, 3, 5, 7, 10, 14, 18}

def load_selected_liar_claims(tsv_path: str, target_row_set: set[int]) -> list[dict]:
    """
    Read a small set of selected LIAR claims for manual behaviour review.
    """
    selected_claims = []

    with open(tsv_path, "r", encoding="utf-8") as file:
        reader = csv.reader(file, delimiter="\t")

        for row_index, row in enumerate(reader, start=1):
            if row_index not in target_row_set:
                continue

            if len(row) < 3:
                continue

            selected_claims.append({
                "row_index": row_index,
                "label": row[1].strip(),
                "claim": row[2].strip()
            })

    return selected_claims

selected_claims = load_selected_liar_claims(test_dataset, target_rows)

print("=" * 100)
print("Before-vs-After Behaviour Review")
print("=" * 100)
print("Manual review focus:")
print("- Did the system avoid unsupported verdicts?")
print("- Did the system become too conservative on clearly checkable claims?")
print("- Are the new product-facing fields sensible?")
print("=" * 100)

for test_item in selected_claims:
    claim_text = test_item["claim"]
    liar_label = test_item["label"]
    row_index = test_item["row_index"]

    print("\n" + "=" * 100)
    print(f"LIAR row: {row_index}")
    print(f"LIAR label: {liar_label}")
    print(f"Claim: {claim_text}")

    try:
        response = analyze_claim(ClaimRequest(claim=claim_text))

        print(f"Status: {response.status}")
        print(f"Decision stage: {response.decision_stage}")
        print(f"Failure reason: {response.failure_reason}")
        print(f"Optimized claim: {response.optimized_claim}")
        print(f"Truth score: {response.truth_score}")
        print(f"Verdict: {response.verdict}")
        print(f"Decision confidence: {response.decision_confidence}")
        print(f"Stabilization used: {response.stabilization_used}")
        print(f"Stabilization delta: {response.stabilization_delta}")
        print(f"Evidence sufficiency: {response.evidence_sufficiency}")
        print(f"Evidence quality: {response.evidence_quality}")
        print(f"Selected evidence count: {response.selected_evidence_count}")
        print(f"Retrieval strategy used: {response.retrieval_strategy_used}")
        print(f"Retrieval query used: {response.retrieval_query_used}")
        print(f"Explanation: {response.explanation}")

        if response.sources:
            print("-" * 100)
            print("Selected sources:")

            for source_index, source_item in enumerate(response.sources, start=1):
                print(f"[Source {source_index}] URL: {source_item.url}")
                print(f"[Source {source_index}] Evidence quality: {source_item.evidence_quality}")
                print(f"[Source {source_index}] Content preview: {source_item.content[:240]}")
                print(f"[Source {source_index}] AI analysis: {source_item.ai_analysis}")
                print("-" * 100)

        print("Manual note:")
        print("- Better than before / Worse than before / Similar")
        print("- Why?")

    except Exception as error:
        print(f"Error: {error}")

print("\n" + "=" * 100)
print("Behaviour review completed.")

====================================================================================================
Before-vs-After Behaviour Review
====================================================================================================
Manual review focus:
- Did the system avoid unsupported verdicts?
- Did the system become too conservative on clearly checkable claims?
- Are the new product-facing fields sensible?
====================================================================================================

====================================================================================================
LIAR row: 1
LIAR label: true
Claim: Building a wall on the U.S.-Mexico border will take literally years.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: Building a wall on the U.S.-Mexico border will take years
Truth score: 0.5
Verdict: Neutral
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: Building a wall on the U.S.-Mexico border will take years
Explanation: No evidence found due to an unexpected search error.
Manual note:
- Better than before / Worse than before / Similar
- Why?

====================================================================================================
LIAR row: 3
LIAR label: false
Claim: Says John McCain has done nothing to help the vets.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: John McCain has done nothing to help the vets
Truth score: 0.5
Verdict: Neutral
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: John McCain has done nothing to help the vets
Explanation: No evidence found due to an unexpected search error.
Manual note:
- Better than before / Worse than before / Similar
- Why?

====================================================================================================
LIAR row: 5
LIAR label: pants-fire
Claim: When asked by a reporter whether hes at the center of a criminal scheme to violate campaign laws, Gov. Scott Walker nodded yes.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: Gov. Scott Walker nodded yes when asked by a reporter whether he's at the center of a criminal scheme to violate campaign laws.
Truth score: 0.5
Verdict: Neutral
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: Gov. Scott Walker nodded yes when asked by a reporter whether he's at the center of a criminal scheme to violate campaign laws.
Explanation: No evidence found due to an unexpected search error.
Manual note:
- Better than before / Worse than before / Similar
- Why?

====================================================================================================
LIAR row: 7
LIAR label: true
Claim: Says that Tennessee law requires that schools receive half of proceeds -- $31 million per year -- from a half-cent increase in the Shelby County sales tax.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: Tennessee law requires schools to receive half of proceeds from a half-cent increase in the Shelby County sales tax, totaling $31 million per year.
Truth score: 0.5
Verdict: Neutral
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: Tennessee law requires schools to receive half of proceeds from a half-cent increase in the Shelby County sales tax, totaling $31 million per year.
Explanation: No evidence found due to an unexpected search error.
Manual note:
- Better than before / Worse than before / Similar
- Why?

====================================================================================================
LIAR row: 10
LIAR label: barely-true
Claim: We know that more than half of Hillary Clintons meetings while she was secretary of state were given to major contributors to the Clinton Foundation.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: More than half of Hillary Clinton's meetings as Secretary of State were given to major contributors to the Clinton Foundation.
Truth score: 0.5
Verdict: Neutral
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: More than half of Hillary Clinton's meetings as Secretary of State were given to major contributors to the Clinton Foundation.
Explanation: No evidence found due to an unexpected search error.
Manual note:
- Better than before / Worse than before / Similar
- Why?

====================================================================================================
LIAR row: 14
LIAR label: false
Claim: Says 57 percent of federal spending goes to the military and just 1 percent goes to food and agriculture, including food stamps.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: 57 percent of federal spending goes to the military and 1 percent goes to food and agriculture, including food stamps
Truth score: 0.5
Verdict: Neutral
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: 57 percent of federal spending goes to the military and 1 percent goes to food and agriculture, including food stamps
Explanation: No evidence found due to an unexpected search error.
Manual note:
- Better than before / Worse than before / Similar
- Why?

====================================================================================================
LIAR row: 18
LIAR label: half-true
Claim: A recent Gallup poll found that 72 percent of Americans and 56 percent of Democrats say the biggest threat to our nations security is big government.
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
Status: system_error
Decision stage: retrieval
Failure reason: search_api_error
Optimized claim: Gallup poll: 72 percent of Americans and 56 percent of Democrats say biggest threat to nation's security is big government
Truth score: 0.5
Verdict: Neutral
Decision confidence: low
Stabilization used: False
Stabilization delta: 0.0
Evidence sufficiency: insufficient
Evidence quality: weak
Selected evidence count: 0
Retrieval strategy used: optimized_only
Retrieval query used: Gallup poll: 72 percent of Americans and 56 percent of Democrats say biggest threat to nation's security is big government
Explanation: No evidence found due to an unexpected search error.
Manual note:
- Better than before / Worse than before / Similar
- Why?

====================================================================================================
Behaviour review completed.

In [ ]:
# ============================================================
# Experiment Cell: Batch Test for Selective Stabilization
#
# Purpose:
# Compare the current pipeline with stabilization OFF vs ON
# on the same small batch of LIAR claims.
#
# What this cell measures:
# 1. verdict and truth score changes
# 2. decision confidence changes
# 3. stabilization metadata
# 4. runtime cost
#
# Why this cell exists:
# This is a focused experiment for the stabilization mechanism
# itself, before making further recall-related changes.
# ============================================================

import os
import csv
import time
import pandas as pd

from app import (
    analyze_claim,
    ClaimRequest,
    set_selective_stabilization_enabled
)

project_root = '/content/drive/MyDrive/UoP/COMP3000/fake-news-detector-v1'
test_dataset = os.path.join(project_root, 'data', 'LIAR', 'test.tsv')

target_rows = [1, 3, 4, 5, 7, 10, 12, 14, 18, 19]

def load_selected_liar_claims(tsv_path: str, target_row_list: list[int]) -> list[dict]:
    """
    Read a fixed set of LIAR rows for batch comparison.
    """
    selected_claims = []
    target_row_set = set(target_row_list)

    with open(tsv_path, "r", encoding="utf-8") as file:
        reader = csv.reader(file, delimiter="\t")

        for row_index, row in enumerate(reader, start=1):
            if row_index not in target_row_set:
                continue

            if len(row) < 3:
                continue

            selected_claims.append({
                "row_index": row_index,
                "label": row[1].strip(),
                "claim": row[2].strip()
            })

    selected_claims.sort(key=lambda item: item["row_index"])
    return selected_claims

def run_batch(claim_batch: list[dict], enable_stabilization: bool) -> list[dict]:
    """
    Run one batch with stabilization either disabled or enabled.
    """
    set_selective_stabilization_enabled(enable_stabilization)

    batch_results = []

    for claim_item in claim_batch:
        start_time = time.perf_counter()
        response = analyze_claim(ClaimRequest(claim=claim_item["claim"]))
        end_time = time.perf_counter()

        batch_results.append({
            "row_index": claim_item["row_index"],
            "liar_label": claim_item["label"],
            "claim": claim_item["claim"],
            "status": response.status,
            "decision_stage": response.decision_stage,
            "truth_score": response.truth_score,
            "verdict": response.verdict,
            "decision_confidence": response.decision_confidence,
            "evidence_sufficiency": response.evidence_sufficiency,
            "evidence_quality": response.evidence_quality,
            "selected_evidence_count": response.selected_evidence_count,
            "stabilization_used": response.stabilization_used,
            "stabilization_delta": response.stabilization_delta,
            "stabilization_result": response.stabilization_result,
            "runtime_seconds": round(end_time - start_time, 3)
        })

    return batch_results

print("# Experiment Cell: Batch Test for Selective Stabilization output:\n")
selected_claims = load_selected_liar_claims(test_dataset, target_rows)

print("=" * 100)
print("Running batch with stabilization OFF")
print("=" * 100)
results_off = run_batch(selected_claims, enable_stabilization=False)

print("=" * 100)
print("Running batch with stabilization ON")
print("=" * 100)
results_on = run_batch(selected_claims, enable_stabilization=True)

comparison_rows = []

for off_result, on_result in zip(results_off, results_on):
    comparison_rows.append({
        "row": off_result["row_index"],
        "liar_label": off_result["liar_label"],
        "stage_off": off_result["decision_stage"],
        "stage_on": on_result["decision_stage"],
        "score_off": off_result["truth_score"],
        "score_on": on_result["truth_score"],
        "verdict_off": off_result["verdict"],
        "verdict_on": on_result["verdict"],
        "confidence_off": off_result["decision_confidence"],
        "confidence_on": on_result["decision_confidence"],
        "evidence_count_off": off_result["selected_evidence_count"],
        "evidence_count_on": on_result["selected_evidence_count"],
        "stabilization_used_on": on_result["stabilization_used"],
        "stabilization_delta_on": on_result["stabilization_delta"],
        "stabilization_result_on": on_result["stabilization_result"],
        "time_off_sec": off_result["runtime_seconds"],
        "time_on_sec": on_result["runtime_seconds"],
        "score_changed": off_result["truth_score"] != on_result["truth_score"],
        "verdict_changed": off_result["verdict"] != on_result["verdict"]
    })

comparison_df = pd.DataFrame(comparison_rows)

print("\n" + "=" * 100)
print("Batch Comparison Table")
print("=" * 100)
display(comparison_df)

summary_row = {
    "batch_size": len(comparison_df),
    "score_changed_cases": int(comparison_df["score_changed"].sum()),
    "verdict_changed_cases": int(comparison_df["verdict_changed"].sum()),
    "avg_time_off_sec": round(comparison_df["time_off_sec"].mean(), 3),
    "avg_time_on_sec": round(comparison_df["time_on_sec"].mean(), 3),
    "avg_extra_time_sec": round(
        comparison_df["time_on_sec"].mean() - comparison_df["time_off_sec"].mean(), 3
    ),
    "stabilization_triggered_cases": int(comparison_df["stabilization_used_on"].sum())
}

summary_df = pd.DataFrame([summary_row])

print("\n" + "=" * 100)
print("Batch Summary")
print("=" * 100)
display(summary_df)

set_selective_stabilization_enabled(True)

print("\n" + "=" * 100)
print("Selective stabilization batch test completed.")
print("Stabilization has been reset to ON for later notebook cells.")

# Experiment Cell: Batch Test for Selective Stabilization output:

====================================================================================================
Running batch with stabilization OFF
====================================================================================================
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
====================================================================================================
Running batch with stabilization ON
====================================================================================================
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search

====================================================================================================
Batch Comparison Table
====================================================================================================

,row,liar_label,stage_off,stage_on,score_off,score_on,verdict_off,verdict_on,confidence_off,confidence_on,evidence_count_off,evidence_count_on,stabilization_used_on,stabilization_delta_on,stabilization_result_on,time_off_sec,time_on_sec,score_changed,verdict_changed
0,1,true,retrieval,retrieval,0.5,0.5,Neutral,Neutral,low,low,0,0,False,0.0,not_triggered,0.944,1.092,False,False
1,3,false,retrieval,retrieval,0.5,0.5,Neutral,Neutral,low,low,0,0,False,0.0,not_triggered,0.999,0.901,False,False
2,4,half-true,retrieval,retrieval,0.5,0.5,Neutral,Neutral,low,low,0,0,False,0.0,not_triggered,0.673,0.661,False,False
3,5,pants-fire,retrieval,retrieval,0.5,0.5,Neutral,Neutral,low,low,0,0,False,0.0,not_triggered,1.050,1.155,False,False
4,7,true,retrieval,retrieval,0.5,0.5,Neutral,Neutral,low,low,0,0,False,0.0,not_triggered,1.040,1.109,False,False
5,10,barely-true,retrieval,retrieval,0.5,0.5,Neutral,Neutral,low,low,0,0,False,0.0,not_triggered,1.123,1.139,False,False
6,12,barely-true,retrieval,retrieval,0.5,0.5,Neutral,Neutral,low,low,0,0,False,0.0,not_triggered,1.011,1.027,False,False
7,14,false,retrieval,retrieval,0.5,0.5,Neutral,Neutral,low,low,0,0,False,0.0,not_triggered,1.080,1.067,False,False
8,18,half-true,retrieval,retrieval,0.5,0.5,Neutral,Neutral,low,low,0,0,False,0.0,not_triggered,0.901,1.006,False,False
9,19,true,retrieval,retrieval,0.5,0.5,Neutral,Neutral,low,low,0,0,False,0.0,not_triggered,0.919,0.984,False,False

====================================================================================================
Batch Summary
====================================================================================================

,batch_size,score_changed_cases,verdict_changed_cases,avg_time_off_sec,avg_time_on_sec,avg_extra_time_sec,stabilization_triggered_cases
0,10,0,0,0.974,1.014,0.04,0

====================================================================================================
Selective stabilization batch test completed.
Stabilization has been reset to ON for later notebook cells.

In [ ]:
# ============================================================
# Experiment Cell: Controlled Stabilization Comparison on Fixed Evidence
#
# Purpose:
# This experiment isolates the effect of selective stabilization
# by holding both the selected evidence and the first-pass score fixed.
#
# What this cell does:
# 1. Run the full pipeline once to obtain selected evidence
# 2. Run one fixed first-pass scoring per case
# 3. Use that same first-pass result for:
#    - OFF: direct output without stabilization
#    - ON: second-pass stabilization on top of the same first-pass result
# ============================================================

import os
import csv
import time
import copy
import pandas as pd

from app import analyze_claim, ClaimRequest, stabilize_result
from decision_utils import (
    aggregate_truth_score_from_source_judgments,
    apply_source_judgments_to_evidence,
    calculate_decision_confidence,
    map_truth_score_to_verdict,
)
from gemini_agent import generate_comprehensive_verdict

project_root = '/content/drive/MyDrive/UoP/COMP3000/fake-news-detector-v1'
test_dataset = os.path.join(project_root, 'data', 'LIAR', 'test.tsv')

target_rows = [1, 3, 4, 5, 7, 10, 12, 14, 18, 19]

def load_selected_liar_claims(tsv_path: str, target_row_list: list[int]) -> list[dict]:
    selected_claims = []
    target_row_set = set(target_row_list)

    with open(tsv_path, 'r', encoding='utf-8') as file:
        reader = csv.reader(file, delimiter='	')

        for row_index, row in enumerate(reader, start=1):
            if row_index not in target_row_set:
                continue
            if len(row) < 3:
                continue

            selected_claims.append({
                'row_index': row_index,
                'label': row[1].strip(),
                'claim': row[2].strip(),
            })

    selected_claims.sort(key=lambda item: item['row_index'])
    return selected_claims

def get_fixed_evidence_cases(claim_batch: list[dict]) -> list[dict]:
    fixed_cases = []

    for claim_item in claim_batch:
        response = analyze_claim(ClaimRequest(claim=claim_item['claim']))
        if response.decision_stage != 'completed':
            continue

        fixed_cases.append({
            'row_index': claim_item['row_index'],
            'liar_label': claim_item['label'],
            'claim': claim_item['claim'],
            'optimized_claim': response.optimized_claim,
            'selected_evidence': [
                {
                    'url': source_item.url,
                    'content': source_item.content,
                    'ai_analysis': source_item.ai_analysis,
                    'evidence_quality': source_item.evidence_quality,
                }
                for source_item in response.sources
            ],
            'selected_evidence_count': response.selected_evidence_count,
            'evidence_sufficiency': response.evidence_sufficiency,
            'evidence_quality': response.evidence_quality,
        })

    return fixed_cases

def run_fixed_first_pass(
    optimized_claim: str,
    selected_evidence: list[dict],
    evidence_sufficiency: str,
    evidence_quality: str,
) -> dict:
    scoring_evidence = copy.deepcopy(selected_evidence)

    start_time = time.perf_counter()

    first_report = generate_comprehensive_verdict(optimized_claim, scoring_evidence)
    source_judgments = first_report.get('source_judgments', [])
    apply_source_judgments_to_evidence(scoring_evidence, source_judgments)

    first_truth_score = aggregate_truth_score_from_source_judgments(
        selected_evidence=scoring_evidence,
        source_judgments=source_judgments,
    )
    first_explanation = first_report.get('explanation', 'No explanation was generated.')

    decision_confidence = calculate_decision_confidence(
        decision_stage='completed',
        truth_score=first_truth_score,
        selected_evidence_count=len(scoring_evidence),
        evidence_sufficiency=evidence_sufficiency,
        evidence_quality=evidence_quality,
    )

    end_time = time.perf_counter()

    return {
        'first_truth_score': first_truth_score,
        'first_explanation': first_explanation,
        'decision_confidence': decision_confidence,
        'runtime_seconds': round(end_time - start_time, 3),
    }

def run_stabilization_on_shared_first_pass(
    optimized_claim: str,
    selected_evidence: list[dict],
    first_truth_score: float,
    first_explanation: str,
    decision_confidence: str,
    evidence_quality: str,
) -> dict:
    scoring_evidence = copy.deepcopy(selected_evidence)

    start_time = time.perf_counter()

    stabilization = stabilize_result(
        claim_for_verdict=optimized_claim,
        selected_evidence=scoring_evidence,
        first_truth_score=first_truth_score,
        first_explanation=first_explanation,
        decision_confidence=decision_confidence,
        evidence_quality=evidence_quality,
    )

    end_time = time.perf_counter()

    return {
        'truth_score': stabilization.truth_score,
        'verdict': map_truth_score_to_verdict(stabilization.truth_score),
        'stabilization_used': stabilization.used,
        'stabilization_delta': stabilization.delta,
        'stabilization_result': stabilization.result,
        'runtime_seconds': round(end_time - start_time, 3),
        'explanation': stabilization.explanation,
    }

print("# Experiment Cell: Controlled Stabilization Comparison on Fixed Evidence output:")
selected_claims = load_selected_liar_claims(test_dataset, target_rows)
fixed_cases = get_fixed_evidence_cases(selected_claims)

print('=' * 100)
print('Controlled Stabilization Comparison on Fixed Evidence')
print('=' * 100)
print(f'Requested rows: {target_rows}')
print(f'Completed cases with reusable evidence: {len(fixed_cases)}')

comparison_rows = []

for fixed_case in fixed_cases:
    first_pass = run_fixed_first_pass(
        optimized_claim=fixed_case['optimized_claim'],
        selected_evidence=fixed_case['selected_evidence'],
        evidence_sufficiency=fixed_case['evidence_sufficiency'],
        evidence_quality=fixed_case['evidence_quality'],
    )

    off_truth_score = first_pass['first_truth_score']
    off_verdict = map_truth_score_to_verdict(off_truth_score)

    on_result = run_stabilization_on_shared_first_pass(
        optimized_claim=fixed_case['optimized_claim'],
        selected_evidence=fixed_case['selected_evidence'],
        first_truth_score=first_pass['first_truth_score'],
        first_explanation=first_pass['first_explanation'],
        decision_confidence=first_pass['decision_confidence'],
        evidence_quality=fixed_case['evidence_quality'],
    )

    comparison_rows.append({
        'row': fixed_case['row_index'],
        'liar_label': fixed_case['liar_label'],
        'evidence_count': fixed_case['selected_evidence_count'],
        'evidence_sufficiency': fixed_case['evidence_sufficiency'],
        'evidence_quality': fixed_case['evidence_quality'],
        'score_off': off_truth_score,
        'score_on': on_result['truth_score'],
        'verdict_off': off_verdict,
        'verdict_on': on_result['verdict'],
        'confidence_shared': first_pass['decision_confidence'],
        'stabilization_used_on': on_result['stabilization_used'],
        'stabilization_delta_on': on_result['stabilization_delta'],
        'stabilization_result_on': on_result['stabilization_result'],
        'time_off_sec': first_pass['runtime_seconds'],
        'time_on_sec': round(first_pass['runtime_seconds'] + on_result['runtime_seconds'], 3),
        'extra_stabilization_time_sec': on_result['runtime_seconds'],
        'score_changed': off_truth_score != on_result['truth_score'],
        'verdict_changed': off_verdict != on_result['verdict'],
    })

comparison_df = pd.DataFrame(comparison_rows)

print('' + '=' * 100)
print('Controlled Comparison Table')
print('=' * 100)
display(comparison_df)

summary_row = {
    'completed_cases_used': len(comparison_df),
    'score_changed_cases': int(comparison_df['score_changed'].sum()) if len(comparison_df) > 0 else 0,
    'verdict_changed_cases': int(comparison_df['verdict_changed'].sum()) if len(comparison_df) > 0 else 0,
    'stabilization_triggered_cases': int(comparison_df['stabilization_used_on'].sum()) if len(comparison_df) > 0 else 0,
    'avg_time_off_sec': round(comparison_df['time_off_sec'].mean(), 3) if len(comparison_df) > 0 else 0.0,
    'avg_time_on_sec': round(comparison_df['time_on_sec'].mean(), 3) if len(comparison_df) > 0 else 0.0,
    'avg_extra_stabilization_time_sec': round(comparison_df['extra_stabilization_time_sec'].mean(), 3) if len(comparison_df) > 0 else 0.0,
}

summary_df = pd.DataFrame([summary_row])

print('' + '=' * 100)
print('Controlled Comparison Summary')
print('=' * 100)
display(summary_df)

# Experiment Cell: Controlled Stabilization Comparison on Fixed Evidence output:
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
[Search API Error] 432 Client Error:  for url: https://api.tavily.com/search
====================================================================================================
Controlled Stabilization Comparison on Fixed Evidence
====================================================================================================
Requested rows: [1, 3, 4, 5, 7, 10, 12, 14, 18, 19]
Completed cases with reusable evidence: 0
====================================================================================================
Controlled Comparison Table
====================================================================================================

Empty DataFrame
Columns: []
Index: []

====================================================================================================
Controlled Comparison Summary
====================================================================================================

,completed_cases_used,score_changed_cases,verdict_changed_cases,stabilization_triggered_cases,avg_time_off_sec,avg_time_on_sec,avg_extra_stabilization_time_sec
0,0,0,0,0,0.0,0.0,0.0

In [ ]:
# ============================================================
# Experiment Cell: Source-Aware Scoring Validation
#
# Purpose:
# Validate the new source-aware scoring design, where the LLM
# outputs source-level judgments and the backend aggregates them
# into the final truth score.
#
# What this cell checks:
# 1. source_role
# 2. source_strength
# 3. source_specificity
# 4. final truth_score and verdict
# 5. whether the final result looks consistent with the source-level signals
# ============================================================

import os
import csv

from app import analyze_claim, ClaimRequest
from decision_utils import (
    normalize_truth_score,
    map_truth_score_to_verdict,
    calculate_decision_confidence,
)
from gemini_agent import generate_comprehensive_verdict
print("# Experiment Cell: Source-Aware Scoring Validation output:")
project_root = '/content/drive/MyDrive/UoP/COMP3000/fake-news-detector-v1'
test_dataset = os.path.join(project_root, 'data', 'LIAR', 'test.tsv')

target_rows = {1, 3, 5, 7, 10, 14, 18, 19}

def load_selected_liar_claims(tsv_path: str, target_row_set: set[int]) -> list[dict]:
    """
    Read a few selected LIAR rows for focused source-aware scoring review.
    """
    selected_claims = []

    with open(tsv_path, "r", encoding="utf-8") as file:
        reader = csv.reader(file, delimiter="\t")

        for row_index, row in enumerate(reader, start=1):
            if row_index not in target_row_set:
                continue

            if len(row) < 3:
                continue

            selected_claims.append({
                "row_index": row_index,
                "label": row[1].strip(),
                "claim": row[2].strip()
            })

    return selected_claims

selected_claims = load_selected_liar_claims(test_dataset, target_rows)

print("=" * 100)
print("Source-Aware Scoring Validation")
print("=" * 100)

for test_item in selected_claims:
    claim_text = test_item["claim"]
    liar_label = test_item["label"]
    row_index = test_item["row_index"]

    print("\n" + "=" * 100)
    print(f"LIAR row: {row_index}")
    print(f"LIAR label: {liar_label}")
    print(f"Claim: {claim_text}")

    try:
        response = analyze_claim(ClaimRequest(claim=claim_text))

        print(f"Status: {response.status}")
        print(f"Decision stage: {response.decision_stage}")
        print(f"Failure reason: {response.failure_reason}")
        print(f"Optimized claim: {response.optimized_claim}")
        print(f"Truth score: {response.truth_score}")
        print(f"Verdict: {response.verdict}")
        print(f"Decision confidence: {response.decision_confidence}")
        print(f"Evidence sufficiency: {response.evidence_sufficiency}")
        print(f"Evidence quality: {response.evidence_quality}")
        print(f"Selected evidence count: {response.selected_evidence_count}")
        print(f"Stabilization used: {response.stabilization_used}")
        print(f"Stabilization delta: {response.stabilization_delta}")
        print(f"Stabilization result: {response.stabilization_result}")
        print(f"Explanation: {response.explanation}")

        if response.sources:
            print("-" * 100)
            print("Selected sources with source-aware judgments:")

            for source_index, source_item in enumerate(response.sources, start=1):
                print(f"[Source {source_index}] URL: {source_item.url}")
                print(f"[Source {source_index}] Evidence quality: {source_item.evidence_quality}")
                print(f"[Source {source_index}] Source role: {source_item.source_role}")
                print(f"[Source {source_index}] Source strength: {source_item.source_strength}")
                print(f"[Source {source_index}] Source specificity: {source_item.source_specificity}")
                print(f"[Source {source_index}] Content preview: {source_item.content[:260]}")
                print(f"[Source {source_index}] AI analysis: {source_item.ai_analysis}")
                print("-" * 100)

    except Exception as error:
        print(f"Error: {error}")

print("\n" + "=" * 100)
print("Source-aware scoring validation completed.")